import { CpuBlockDefinition } from '../types/cpuBlock';

const REGISTER_OPTIONS = [
  { label: 'A (Accumulator)', labelHu: 'A (Akkumulátor)', value: 'A' },
  { label: 'B (General Reg)', labelHu: 'B (Általános Reg)', value: 'B' },
  { label: 'C (Counter / Ptr)', labelHu: 'C (Számláló / Cím)', value: 'C' },
  { label: 'D (Data Reg)', labelHu: 'D (Adat Reg)', value: 'D' },
];

const IO_PORT_OPTIONS = [
  { label: 'Port 1: 8x LED Sor', labelHu: 'Port 1: 8x LED Sor', value: '1' },
  { label: 'Port 2: ASCII Terminál', labelHu: 'Port 2: ASCII Terminál', value: '2' },
  { label: 'Port 3: 7-Szegmenses Kijelző', labelHu: 'Port 3: 7-Szegmenses Kijelző', value: '3' },
  { label: 'Port 4: Csipogó / Audio Beeper', labelHu: 'Port 4: Csipogó / Audio Beeper', value: '4' },
  { label: 'Port 5: 8x8 LED Mátrix Grafika', labelHu: 'Port 5: 8x8 LED Mátrix Grafika', value: '5' },
  { label: 'Port 0: DIP Kapcsolók (Bemenet)', labelHu: 'Port 0: DIP Kapcsolók (Bemenet)', value: '0' },
];

export const CPU_BLOCK_DEFINITIONS: CpuBlockDefinition[] = [
  // ==================== 1. HIGH-LEVEL STRUCTURES (BLOCKLY STYLE) ====================
  {
    id: 'block_loop_count',
    type: 'LOOP_COUNT',
    category: 'HIGH_LEVEL',
    name: 'Repeat Loop (N times)',
    nameHu: 'Ismételd Ciklus (N alkalommal)',
    description: 'Executes inner instructions N times using register C as counter.',
    descriptionHu: 'A belső utasításokat N-szer hajtja végre a C regiszter számlálóval.',
    color: 'border-amber-500/80 bg-amber-950/40 text-amber-200',
    accentColor: '#F59E0B',
    iconName: 'RotateCcw',
    hasChildren: true,
    defaultParams: { count: 5, loopLabel: 'loop_1' },
    paramSchema: [
      {
        key: 'count',
        label: 'Repeat Count (1..255)',
        labelHu: 'Ismétlések száma (1..255)',
        type: 'number',
        min: 1,
        max: 255,
      },
      {
        key: 'loopLabel',
        label: 'Loop Label Name',
        labelHu: 'Ciklus Címke Neve',
        type: 'text',
        placeholder: 'loop_1',
      },
    ],
  },
  {
    id: 'block_if_cmp',
    type: 'IF_CMP',
    category: 'HIGH_LEVEL',
    name: 'If Condition (Compare Reg & Branch)',
    nameHu: 'Ha Feltétel Teljesül (Összehasonlítás)',
    description: 'Compares register with a value and executes inner blocks if true.',
    descriptionHu: 'Összehasonlítja a regisztert az értékkel és ugrást végez a feltétel szerint.',
    color: 'border-amber-500/80 bg-amber-950/40 text-amber-200',
    accentColor: '#F59E0B',
    iconName: 'GitBranch',
    hasChildren: true,
    defaultParams: {
      reg: 'A',
      condition: 'JE',
      compareVal: 10,
      skipLabel: 'skip_1',
    },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register',
        labelHu: 'Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'condition',
        label: 'Condition When True',
        labelHu: 'Feltétel ha egyezik',
        type: 'select',
        options: [
          { label: 'JE (Equal / Egyenlő ==)', labelHu: 'JE (Equal / Egyenlő ==)', value: 'JE' },
          { label: 'JNE / JNZ (Not Equal / Nem egyenlő !=)', labelHu: 'JNE / JNZ (Not Equal / Nem egyenlő !=)', value: 'JNZ' },
          { label: 'JG (Greater Than / Nagyobb >)', labelHu: 'JG (Greater Than / Nagyobb >)', value: 'JG' },
          { label: 'JL (Less Than / Kisebb <)', labelHu: 'JL (Less Than / Kisebb <)', value: 'JL' },
          { label: 'JZ (Zero / Nulla Z=1)', labelHu: 'JZ (Zero / Nulla Z=1)', value: 'JZ' },
        ],
      },
      {
        key: 'compareVal',
        label: 'Compare Value (0..255)',
        labelHu: 'Összehasonlítási Érték',
        type: 'number',
        min: 0,
        max: 255,
      },
      {
        key: 'skipLabel',
        label: 'Branch Label',
        labelHu: 'Ág Címke',
        type: 'text',
      },
    ],
  },
  {
    id: 'block_comment',
    type: 'COMMENT',
    category: 'HIGH_LEVEL',
    name: 'Comment / Section Note',
    nameHu: 'Megjegyzés / Fejezet Cím',
    description: 'Inserts visual documentation comment (; comment) into assembly.',
    descriptionHu: 'Megjegyzést és magyarázatot szúr be a generált Assembly kódba.',
    color: 'border-slate-600 bg-slate-900/60 text-slate-300',
    accentColor: '#64748B',
    iconName: 'MessageSquare',
    defaultParams: { text: 'Adatok előkészítése és inicializálás' },
    paramSchema: [
      {
        key: 'text',
        label: 'Comment Text',
        labelHu: 'Megjegyzés szövege',
        type: 'text',
      },
    ],
  },

  // ==================== 2. DATA MOVEMENT & MEMORY (GREEN) ====================
  {
    id: 'block_ldi',
    type: 'LDI',
    mnemonic: 'LDI',
    category: 'DATA',
    name: 'Load Immediate (LDI reg, imm)',
    nameHu: 'Közvetlen Érték Betöltése (LDI)',
    description: 'Loads a constant 8-bit number into a register.',
    descriptionHu: 'Közvetlen 8 bites számot tölt a megadott regiszterbe (0..255).',
    color: 'border-emerald-500/80 bg-emerald-950/40 text-emerald-200',
    accentColor: '#10B981',
    iconName: 'Download',
    defaultParams: { reg: 'A', imm: 42 },
    paramSchema: [
      {
        key: 'reg',
        label: 'Target Register',
        labelHu: 'Cél Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'imm',
        label: 'Immediate Value (0..255)',
        labelHu: 'Érték (0..255)',
        type: 'number',
        min: 0,
        max: 255,
      },
    ],
  },
  {
    id: 'block_mov',
    type: 'MOV',
    mnemonic: 'MOV',
    category: 'DATA',
    name: 'Copy Register (MOV dst, src)',
    nameHu: 'Regiszter Másolás (MOV cél, forrás)',
    description: 'Copies value from source register to destination register.',
    descriptionHu: 'Átmásolja a forrás regiszter tartalmát a cél regiszterbe.',
    color: 'border-emerald-500/80 bg-emerald-950/40 text-emerald-200',
    accentColor: '#10B981',
    iconName: 'ArrowRightLeft',
    defaultParams: { dst: 'A', src: 'B' },
    paramSchema: [
      {
        key: 'dst',
        label: 'Destination Register',
        labelHu: 'Cél Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'src',
        label: 'Source Register',
        labelHu: 'Forrás Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_lda',
    type: 'LDA',
    mnemonic: 'LDA',
    category: 'DATA',
    name: 'Load RAM into A (LDA addr)',
    nameHu: 'Memóriacím Olvasása az A-ba (LDA)',
    description: 'Loads 8-bit value from memory address into Accumulator A.',
    descriptionHu: 'Közvetlen memóriacímről (0x00..0xFF) olvas az A regiszterbe.',
    color: 'border-emerald-500/80 bg-emerald-950/40 text-emerald-200',
    accentColor: '#10B981',
    iconName: 'Database',
    defaultParams: { addr: '0x80' },
    paramSchema: [
      {
        key: 'addr',
        label: 'RAM Address (Hex or Dec)',
        labelHu: 'Memóriacím (Hex / Dec, pl. 0x80)',
        type: 'text',
      },
    ],
  },
  {
    id: 'block_sta',
    type: 'STA',
    mnemonic: 'STA',
    category: 'DATA',
    name: 'Store A into RAM (STA addr)',
    nameHu: 'A Regiszter Mentése Memóriába (STA)',
    description: 'Stores Accumulator A value into specified memory address.',
    descriptionHu: 'Az A regiszter értékét elmenti a megadott memóriacímre.',
    color: 'border-emerald-500/80 bg-emerald-950/40 text-emerald-200',
    accentColor: '#10B981',
    iconName: 'Save',
    defaultParams: { addr: '0x80' },
    paramSchema: [
      {
        key: 'addr',
        label: 'RAM Address',
        labelHu: 'Memóriacím (pl. 0x80 vagy 128)',
        type: 'text',
      },
    ],
  },
  {
    id: 'block_ldr',
    type: 'LDR',
    mnemonic: 'LDR',
    category: 'DATA',
    name: 'Pointer Load (LDR dst, [src])',
    nameHu: 'Indirekt Betöltés Mutatóból (LDR)',
    description: 'Loads from address stored in source register (e.g. C pointer).',
    descriptionHu: 'Betölt a forrás regiszterben (pl. C) lévő memóriacímről.',
    color: 'border-emerald-500/80 bg-emerald-950/40 text-emerald-200',
    accentColor: '#10B981',
    iconName: 'CornerDownRight',
    defaultParams: { dst: 'A', src: 'C' },
    paramSchema: [
      {
        key: 'dst',
        label: 'Target Register',
        labelHu: 'Cél Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'src',
        label: 'Pointer Address Reg',
        labelHu: 'Cím Mutató Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_str',
    type: 'STR',
    mnemonic: 'STR',
    category: 'DATA',
    name: 'Pointer Store (STR [dst], src)',
    nameHu: 'Indirekt Mentés Mutatóba (STR)',
    description: 'Stores source value into RAM address pointed by destination reg.',
    descriptionHu: 'Elmenti az értéket a cél regiszter (pl. C) által mutatott memóriacímre.',
    color: 'border-emerald-500/80 bg-emerald-950/40 text-emerald-200',
    accentColor: '#10B981',
    iconName: 'CornerDownLeft',
    defaultParams: { dst: 'C', src: 'A' },
    paramSchema: [
      {
        key: 'dst',
        label: 'Pointer Address Reg',
        labelHu: 'Cím Mutató Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'src',
        label: 'Source Value Reg',
        labelHu: 'Forrás Érték Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },

  // ==================== 3. ARITHMETIC & LOGIC UNIT (ALU - BLUE) ====================
  {
    id: 'block_add',
    type: 'ADD',
    mnemonic: 'ADD',
    category: 'ALU',
    name: 'Add Registers (ADD dst, src)',
    nameHu: 'Összeadás Regiszterekkel (ADD)',
    description: 'Performs dst = dst + src and updates Z, C, N, V flags.',
    descriptionHu: 'Összeadja a két regisztert (dst += src), frissíti a Zero és Carry biteket.',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'Plus',
    defaultParams: { dst: 'A', src: 'B' },
    paramSchema: [
      {
        key: 'dst',
        label: 'Destination (+=)',
        labelHu: 'Cél Regiszter (+=)',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'src',
        label: 'Operand Register',
        labelHu: 'Hozzáadandó Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_addi',
    type: 'ADDI',
    mnemonic: 'ADDI',
    category: 'ALU',
    name: 'Add Immediate (ADDI reg, imm)',
    nameHu: 'Közvetlen Szám Hozzáadása (ADDI)',
    description: 'Adds an immediate constant value directly to register.',
    descriptionHu: 'Közvetlen számot ad hozzá a regiszterhez (reg += imm).',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'PlusCircle',
    defaultParams: { reg: 'A', imm: 1 },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register',
        labelHu: 'Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'imm',
        label: 'Value to Add (0..255)',
        labelHu: 'Hozzáadandó Érték',
        type: 'number',
        min: 0,
        max: 255,
      },
    ],
  },
  {
    id: 'block_sub',
    type: 'SUB',
    mnemonic: 'SUB',
    category: 'ALU',
    name: 'Subtract Registers (SUB dst, src)',
    nameHu: 'Kivonás Regiszterekkel (SUB)',
    description: 'Performs dst = dst - src and updates flags.',
    descriptionHu: 'Kivonja a forrást a célból (dst -= src) és frissíti a jelzőbiteket.',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'Minus',
    defaultParams: { dst: 'A', src: 'B' },
    paramSchema: [
      {
        key: 'dst',
        label: 'Destination (-=)',
        labelHu: 'Cél Regiszter (-=)',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'src',
        label: 'Subtract Reg',
        labelHu: 'Kivonandó Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_inc',
    type: 'INC',
    mnemonic: 'INC',
    category: 'ALU',
    name: 'Increment by 1 (INC reg)',
    nameHu: 'Regiszter Növelése 1-gyel (INC)',
    description: 'Adds 1 to register value (reg = reg + 1).',
    descriptionHu: 'Eggyel növeli a megadott regisztert (reg = reg + 1).',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'ArrowUp',
    defaultParams: { reg: 'A' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register',
        labelHu: 'Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_dec',
    type: 'DEC',
    mnemonic: 'DEC',
    category: 'ALU',
    name: 'Decrement by 1 (DEC reg)',
    nameHu: 'Regiszter Csökkentése 1-gyel (DEC)',
    description: 'Subtracts 1 from register (reg = reg - 1).',
    descriptionHu: 'Eggyel csökkenti a megadott regisztert (reg = reg - 1).',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'ArrowDown',
    defaultParams: { reg: 'C' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register',
        labelHu: 'Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_cmp',
    type: 'CMP',
    mnemonic: 'CMP',
    category: 'ALU',
    name: 'Compare Registers (CMP r1, r2)',
    nameHu: 'Regiszterek Összehasonlítása (CMP)',
    description: 'Compares r1 with r2 by virtual subtraction and sets Z, E, G, L flags.',
    descriptionHu: 'Összehasonlítja a két regisztert és beállítja az E (egyenlő), G, L biteket.',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'Scale',
    defaultParams: { r1: 'A', r2: 'B' },
    paramSchema: [
      {
        key: 'r1',
        label: 'Left Register',
        labelHu: 'Bal Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'r2',
        label: 'Right Register',
        labelHu: 'Jobb Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_cmpi',
    type: 'CMPI',
    mnemonic: 'CMPI',
    category: 'ALU',
    name: 'Compare Immediate (CMPI reg, imm)',
    nameHu: 'Összehasonlítás Számmal (CMPI)',
    description: 'Compares register with a constant value and sets comparison flags.',
    descriptionHu: 'Összehasonlítja a regisztert egy közvetlen számmal a jelzőbitekhez.',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'Sliders',
    defaultParams: { reg: 'A', imm: 10 },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register',
        labelHu: 'Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'imm',
        label: 'Immediate Value (0..255)',
        labelHu: 'Közvetlen Érték',
        type: 'number',
        min: 0,
        max: 255,
      },
    ],
  },
  {
    id: 'block_shl',
    type: 'SHL',
    mnemonic: 'SHL',
    category: 'ALU',
    name: 'Shift Left Bits (SHL reg)',
    nameHu: 'Bitek Léptetése Balra (SHL - reg << 1)',
    description: 'Shifts all 8 bits left by 1 position (multiplication by 2).',
    descriptionHu: 'Bitenkénti balra léptetés (2-vel való szorzás, futófényhez ideális).',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'ChevronsLeft',
    defaultParams: { reg: 'A' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register',
        labelHu: 'Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_shr',
    type: 'SHR',
    mnemonic: 'SHR',
    category: 'ALU',
    name: 'Shift Right Bits (SHR reg)',
    nameHu: 'Bitek Léptetése Jobbra (SHR - reg >> 1)',
    description: 'Shifts all 8 bits right by 1 position (division by 2).',
    descriptionHu: 'Bitenkénti jobbra léptetés (egész osztás 2-vel).',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'ChevronsRight',
    defaultParams: { reg: 'A' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register',
        labelHu: 'Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_and',
    type: 'AND',
    mnemonic: 'AND',
    category: 'ALU',
    name: 'Bitwise AND (AND dst, src)',
    nameHu: 'Bitenkénti ÉS Művelet (AND)',
    description: 'Performs bitwise AND logic (masking bits).',
    descriptionHu: 'Bitenkénti ÉS logikai művelet (bitek maszkolására).',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'Binary',
    defaultParams: { dst: 'A', src: 'B' },
    paramSchema: [
      {
        key: 'dst',
        label: 'Destination Reg',
        labelHu: 'Cél Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'src',
        label: 'Source Mask Reg',
        labelHu: 'Forrás Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_rand',
    type: 'RAND',
    mnemonic: 'RAND',
    category: 'ALU',
    name: 'Random Number (RAND reg)',
    nameHu: 'Véletlenszám Generálás (RAND)',
    description: 'Generates pseudo-random 8-bit byte (0..255) into register.',
    descriptionHu: '8 bites véletlenszámot generál a hardveres generátorral.',
    color: 'border-blue-500/80 bg-blue-950/40 text-blue-200',
    accentColor: '#3B82F6',
    iconName: 'Sparkles',
    defaultParams: { reg: 'A' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Target Register',
        labelHu: 'Cél Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },

  // ==================== 4. CONTROL FLOW & JUMPS (YELLOW / AMBER) ====================
  {
    id: 'block_label',
    type: 'LABEL',
    category: 'FLOW',
    name: 'Define Code Label (label:)',
    nameHu: 'Címke Elhelyezése (label:)',
    description: 'Defines a named jump target for loops and branches.',
    descriptionHu: 'Megnevezett ugrási célpontot határoz meg a programban.',
    color: 'border-amber-500/80 bg-amber-950/40 text-amber-200',
    accentColor: '#F59E0B',
    iconName: 'Tag',
    defaultParams: { name: 'main_loop' },
    paramSchema: [
      {
        key: 'name',
        label: 'Label Identifier',
        labelHu: 'Címke Azonosító',
        type: 'text',
        placeholder: 'my_label',
      },
    ],
  },
  {
    id: 'block_jmp',
    type: 'JMP',
    mnemonic: 'JMP',
    category: 'FLOW',
    name: 'Unconditional Jump (JMP label)',
    nameHu: 'Feltétel Nélküli Ugrás (JMP)',
    description: 'Jumps unconditionally to label or address.',
    descriptionHu: 'Feltétel nélkül az adott címkére vagy memóriacímre ugrik.',
    color: 'border-amber-500/80 bg-amber-950/40 text-amber-200',
    accentColor: '#F59E0B',
    iconName: 'FastForward',
    defaultParams: { target: 'main_loop' },
    paramSchema: [
      {
        key: 'target',
        label: 'Target Label / Address',
        labelHu: 'Cél Címke vagy Cím',
        type: 'text',
      },
    ],
  },
  {
    id: 'block_jnz',
    type: 'JNZ',
    mnemonic: 'JNZ',
    category: 'FLOW',
    name: 'Jump if Not Zero (JNZ label)',
    nameHu: 'Ugrás ha Nem Nulla (JNZ - Z=0)',
    description: 'Jumps to target if last operation result was not zero (Z=0).',
    descriptionHu: 'Ugrást hajt végre, ha az előző eredmény nem nulla (számláló ciklusokhoz).',
    color: 'border-amber-500/80 bg-amber-950/40 text-amber-200',
    accentColor: '#F59E0B',
    iconName: 'GitBranch',
    defaultParams: { target: 'loop_start' },
    paramSchema: [
      {
        key: 'target',
        label: 'Target Label',
        labelHu: 'Cél Címke',
        type: 'text',
      },
    ],
  },
  {
    id: 'block_jz',
    type: 'JZ',
    mnemonic: 'JZ',
    category: 'FLOW',
    name: 'Jump if Zero (JZ label)',
    nameHu: 'Ugrás ha Nulla (JZ - Z=1)',
    description: 'Jumps to target if Zero flag is active (Z=1).',
    descriptionHu: 'Ugrás, ha az ALU eredménye nulla lett.',
    color: 'border-amber-500/80 bg-amber-950/40 text-amber-200',
    accentColor: '#F59E0B',
    iconName: 'GitBranch',
    defaultParams: { target: 'done' },
    paramSchema: [
      {
        key: 'target',
        label: 'Target Label',
        labelHu: 'Cél Címke',
        type: 'text',
      },
    ],
  },
  {
    id: 'block_jc',
    type: 'JC',
    mnemonic: 'JC',
    category: 'FLOW',
    name: 'Jump if Carry / Overflow (JC)',
    nameHu: 'Ugrás ha Átvitel Történt (JC - C=1)',
    description: 'Jumps if addition overflowed past 255 (Carry flag set).',
    descriptionHu: 'Ugrás ha túlcsordulás történt (összeadás meghaladta a 255-öt).',
    color: 'border-amber-500/80 bg-amber-950/40 text-amber-200',
    accentColor: '#F59E0B',
    iconName: 'AlertCircle',
    defaultParams: { target: 'overflow_handler' },
    paramSchema: [
      {
        key: 'target',
        label: 'Target Label',
        labelHu: 'Cél Címke',
        type: 'text',
      },
    ],
  },

  // ==================== 5. STACK & SUBROUTINES (PURPLE) ====================
  {
    id: 'block_call',
    type: 'CALL',
    mnemonic: 'CALL',
    category: 'STACK',
    name: 'Call Subroutine (CALL name)',
    nameHu: 'Alprogram Meghívása (CALL)',
    description: 'Pushes return address to Stack and jumps to subroutine.',
    descriptionHu: 'Verembe menti a visszatérési címet és meghívja az alprogramot.',
    color: 'border-purple-500/80 bg-purple-950/40 text-purple-200',
    accentColor: '#A855F7',
    iconName: 'LogIn',
    defaultParams: { funcName: 'delay_fn' },
    paramSchema: [
      {
        key: 'funcName',
        label: 'Function / Label Name',
        labelHu: 'Függvény Címke Neve',
        type: 'text',
      },
    ],
  },
  {
    id: 'block_ret',
    type: 'RET',
    mnemonic: 'RET',
    category: 'STACK',
    name: 'Return from Subroutine (RET)',
    nameHu: 'Visszatérés Alprogramból (RET)',
    description: 'Pops return address from stack and resumes caller.',
    descriptionHu: 'Visszatér a hívóhoz a veremből kiolvasott címre.',
    color: 'border-purple-500/80 bg-purple-950/40 text-purple-200',
    accentColor: '#A855F7',
    iconName: 'LogOut',
    defaultParams: {},
    paramSchema: [],
  },
  {
    id: 'block_push',
    type: 'PUSH',
    mnemonic: 'PUSH',
    category: 'STACK',
    name: 'Push to Stack (PUSH reg)',
    nameHu: 'Regiszter Verembe Mentése (PUSH)',
    description: 'Pushes 8-bit register onto hardware stack.',
    descriptionHu: 'Elmenti a regisztert a hardveres verembe (SP mutató).',
    color: 'border-purple-500/80 bg-purple-950/40 text-purple-200',
    accentColor: '#A855F7',
    iconName: 'Layers',
    defaultParams: { reg: 'A' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Register to Push',
        labelHu: 'Mentendő Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_pop',
    type: 'POP',
    mnemonic: 'POP',
    category: 'STACK',
    name: 'Pop from Stack (POP reg)',
    nameHu: 'Regiszter Visszatöltése Veremből (POP)',
    description: 'Restores register value from hardware stack.',
    descriptionHu: 'Kiveszi a legfelső értéket a veremből a regiszterbe.',
    color: 'border-purple-500/80 bg-purple-950/40 text-purple-200',
    accentColor: '#A855F7',
    iconName: 'Layers',
    defaultParams: { reg: 'A' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Target Register',
        labelHu: 'Cél Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },

  // ==================== 6. I/O & PERIPHERALS (CYAN) ====================
  {
    id: 'block_out',
    type: 'OUT',
    mnemonic: 'OUT',
    category: 'IO',
    name: 'Output to Port (OUT port, reg)',
    nameHu: 'Kiírás I/O Portra (OUT)',
    description: 'Sends register value to peripheral (LEDs, 7-Segment, Terminal).',
    descriptionHu: 'Kiküldi a regiszter értékét a kiválasztott perifériára.',
    color: 'border-cyan-500/80 bg-cyan-950/40 text-cyan-200',
    accentColor: '#06B6D4',
    iconName: 'Tv',
    defaultParams: { port: '3', reg: 'A' },
    paramSchema: [
      {
        key: 'port',
        label: 'Target I/O Port',
        labelHu: 'Cél I/O Port',
        type: 'select',
        options: IO_PORT_OPTIONS,
      },
      {
        key: 'reg',
        label: 'Source Register',
        labelHu: 'Kiírandó Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
    ],
  },
  {
    id: 'block_outi',
    type: 'OUTI',
    mnemonic: 'OUTI',
    category: 'IO',
    name: 'Output Immediate (OUTI port, imm)',
    nameHu: 'Közvetlen Szám Kiírása Portra (OUTI)',
    description: 'Outputs a fixed number directly to an I/O port.',
    descriptionHu: 'Közvetlen számot küld ki egy I/O portra (pl. LED-ek bekapcsolása).',
    color: 'border-cyan-500/80 bg-cyan-950/40 text-cyan-200',
    accentColor: '#06B6D4',
    iconName: 'Zap',
    defaultParams: { port: '1', imm: 255 },
    paramSchema: [
      {
        key: 'port',
        label: 'Target Port',
        labelHu: 'Cél Port',
        type: 'select',
        options: IO_PORT_OPTIONS,
      },
      {
        key: 'imm',
        label: 'Value (0..255)',
        labelHu: 'Érték (0..255)',
        type: 'number',
        min: 0,
        max: 255,
      },
    ],
  },
  {
    id: 'block_in',
    type: 'IN',
    mnemonic: 'IN',
    category: 'IO',
    name: 'Read from I/O Port (IN reg, port)',
    nameHu: 'Beolvasás I/O Portról (IN)',
    description: 'Reads hardware switch/keypad inputs into a register.',
    descriptionHu: 'Beolvassa a hardveres DIP kapcsolók vagy tasztatúra állapotát.',
    color: 'border-cyan-500/80 bg-cyan-950/40 text-cyan-200',
    accentColor: '#06B6D4',
    iconName: 'Radio',
    defaultParams: { reg: 'A', port: '0' },
    paramSchema: [
      {
        key: 'reg',
        label: 'Destination Register',
        labelHu: 'Cél Regiszter',
        type: 'select',
        options: REGISTER_OPTIONS,
      },
      {
        key: 'port',
        label: 'Source Port',
        labelHu: 'Forrás Port',
        type: 'select',
        options: IO_PORT_OPTIONS,
      },
    ],
  },

  // ==================== 7. SYSTEM & EXECUTION (ROSE / RED) ====================
  {
    id: 'block_hlt',
    type: 'HLT',
    mnemonic: 'HLT',
    category: 'SYSTEM',
    name: 'Halt Execution (HLT)',
    nameHu: 'Program Leállítása (HLT)',
    description: 'Stops CPU clock generator and halts the processor.',
    descriptionHu: 'Leállítja a processzor órajel-generátorát és befejezi a futást.',
    color: 'border-rose-500/80 bg-rose-950/40 text-rose-200',
    accentColor: '#F43F5E',
    iconName: 'Square',
    defaultParams: {},
    paramSchema: [],
  },
  {
    id: 'block_sleep',
    type: 'SLEEP',
    mnemonic: 'SLEEP',
    category: 'SYSTEM',
    name: 'Sleep / Pause (SLEEP cycles)',
    nameHu: 'Várakozás / Késleltetés (SLEEP)',
    description: 'Pauses processor execution for N clock cycles.',
    descriptionHu: 'Szünetelteti a végrehajtást megadott órajelciklusig.',
    color: 'border-rose-500/80 bg-rose-950/40 text-rose-200',
    accentColor: '#F43F5E',
    iconName: 'Clock',
    defaultParams: { cycles: 5 },
    paramSchema: [
      {
        key: 'cycles',
        label: 'Clock Cycles',
        labelHu: 'Órajelciklusok száma',
        type: 'number',
        min: 1,
        max: 255,
      },
    ],
  },
  {
    id: 'block_nop',
    type: 'NOP',
    mnemonic: 'NOP',
    category: 'SYSTEM',
    name: 'No Operation (NOP)',
    nameHu: 'Üres Művelet (NOP)',
    description: 'Performs no action for 1 clock cycle.',
    descriptionHu: '1 órajelciklusig semmit nem csinál (időzítéshez).',
    color: 'border-slate-600 bg-slate-900/60 text-slate-400',
    accentColor: '#94A3B8',
    iconName: 'MinusCircle',
    defaultParams: {},
    paramSchema: [],
  },
];
