import { CpuPlacedBlock } from '../types/cpuBlock';

export interface CompilationResult {
  code: string;
  instructionCount: number;
  estimatedBytes: number;
  warnings: string[];
}

export function compileCpuBlocksToAssembly(
  blocks: CpuPlacedBlock[],
  language: 'hu' | 'en' = 'hu'
): CompilationResult {
  const lines: string[] = [];
  let instructionCount = 0;
  let estimatedBytes = 0;
  const warnings: string[] = [];

  lines.push('; ==========================================================');
  lines.push(
    language === 'hu'
      ? '; 🧩 VIZUÁLIS BLOKK-ÖSSZEÁLLÍTÓ ÁLTAL GENERÁLT ASSEMBLY KÓD'
      : '; 🧩 ASSEMBLY CODE GENERATED BY VISUAL BLOCK BUILDER'
  );
  lines.push(
    language === 'hu'
      ? '; Célarchitektúra: Edu8 / 6502 / Z80 / SAP-1 Moduláris CPU'
      : '; Target Architecture: Edu8 / 6502 / Z80 / SAP-1 Modular CPU'
  );
  lines.push('; ==========================================================');
  lines.push('');

  function compileBlock(block: CpuPlacedBlock, indent = '') {
    const { blockType, params, children } = block;

    switch (blockType) {
      // 1. HIGH-LEVEL STRUCTURES
      case 'LOOP_COUNT': {
        const count = params.count ?? 5;
        const loopLabel = params.loopLabel || 'loop_cnt';
        lines.push(
          `${indent}; --- ${language === 'hu' ? `Ciklus (${count} ismétlés, C regiszterrel)` : `Loop (${count} iterations with reg C)`} ---`
        );
        lines.push(`${indent}LDI C, ${count}`);
        lines.push(`${indent}${loopLabel}:`);
        instructionCount += 2;
        estimatedBytes += 3;

        if (children && children.length > 0) {
          children.forEach((child) => compileBlock(child, indent + '  '));
        } else {
          lines.push(`${indent}  NOP`);
          instructionCount += 1;
          estimatedBytes += 1;
        }

        lines.push(`${indent}  DEC C`);
        lines.push(`${indent}  JNZ ${loopLabel}`);
        lines.push(
          `${indent}; --- ${language === 'hu' ? 'Ciklus vége' : 'End of loop'} ---`
        );
        instructionCount += 2;
        estimatedBytes += 3;
        break;
      }

      case 'IF_CMP': {
        const reg = params.reg || 'A';
        const cond = params.condition || 'JE';
        const val = params.compareVal ?? 10;
        const skipLabel = params.skipLabel || 'skip_branch';

        lines.push(
          `${indent}; --- ${language === 'hu' ? `Feltétel vizsgálat (${reg} == ${val})` : `If condition (${reg} == ${val})`} ---`
        );
        lines.push(`${indent}CMPI ${reg}, ${val}`);
        instructionCount += 1;
        estimatedBytes += 3;

        // Invert condition to skip the block if false
        let jumpInst = 'JNZ';
        if (cond === 'JE') jumpInst = 'JNZ';
        else if (cond === 'JNZ') jumpInst = 'JZ';
        else if (cond === 'JG') jumpInst = 'JL';
        else if (cond === 'JL') jumpInst = 'JG';
        else if (cond === 'JZ') jumpInst = 'JNZ';

        lines.push(`${indent}${jumpInst} ${skipLabel}`);
        instructionCount += 1;
        estimatedBytes += 2;

        if (children && children.length > 0) {
          children.forEach((child) => compileBlock(child, indent + '  '));
        }

        lines.push(`${indent}${skipLabel}:`);
        lines.push(
          `${indent}; --- ${language === 'hu' ? 'Feltételes ág vége' : 'End of if branch'} ---`
        );
        break;
      }

      case 'COMMENT': {
        const text = params.text || '';
        lines.push(`${indent}; ${text}`);
        break;
      }

      // 2. DATA MOVEMENT
      case 'LDI': {
        const reg = params.reg || 'A';
        const imm = params.imm ?? 0;
        lines.push(`${indent}LDI ${reg}, ${imm}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'MOV': {
        const dst = params.dst || 'A';
        const src = params.src || 'B';
        lines.push(`${indent}MOV ${dst}, ${src}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'LDA': {
        const addr = params.addr || '0x80';
        lines.push(`${indent}LDA ${addr}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'STA': {
        const addr = params.addr || '0x80';
        lines.push(`${indent}STA ${addr}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'LDR': {
        const dst = params.dst || 'A';
        const src = params.src || 'C';
        lines.push(`${indent}LDR ${dst}, [${src}]`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'STR': {
        const dst = params.dst || 'C';
        const src = params.src || 'A';
        lines.push(`${indent}STR [${dst}], ${src}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      // 3. ALU OPERATIONS
      case 'ADD': {
        const dst = params.dst || 'A';
        const src = params.src || 'B';
        lines.push(`${indent}ADD ${dst}, ${src}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'ADDI': {
        const reg = params.reg || 'A';
        const imm = params.imm ?? 1;
        lines.push(`${indent}ADDI ${reg}, ${imm}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'SUB': {
        const dst = params.dst || 'A';
        const src = params.src || 'B';
        lines.push(`${indent}SUB ${dst}, ${src}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'INC': {
        const reg = params.reg || 'A';
        lines.push(`${indent}INC ${reg}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'DEC': {
        const reg = params.reg || 'C';
        lines.push(`${indent}DEC ${reg}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'CMP': {
        const r1 = params.r1 || 'A';
        const r2 = params.r2 || 'B';
        lines.push(`${indent}CMP ${r1}, ${r2}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'CMPI': {
        const reg = params.reg || 'A';
        const imm = params.imm ?? 0;
        lines.push(`${indent}CMPI ${reg}, ${imm}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'SHL': {
        const reg = params.reg || 'A';
        lines.push(`${indent}SHL ${reg}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'SHR': {
        const reg = params.reg || 'A';
        lines.push(`${indent}SHR ${reg}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'AND': {
        const dst = params.dst || 'A';
        const src = params.src || 'B';
        lines.push(`${indent}AND ${dst}, ${src}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'RAND': {
        const reg = params.reg || 'A';
        lines.push(`${indent}RAND ${reg}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      // 4. CONTROL FLOW
      case 'LABEL': {
        const name = params.name || 'label_1';
        lines.push(`${name}:`);
        break;
      }

      case 'JMP': {
        const target = params.target || 'main_loop';
        lines.push(`${indent}JMP ${target}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'JNZ': {
        const target = params.target || 'loop_start';
        lines.push(`${indent}JNZ ${target}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'JZ': {
        const target = params.target || 'done';
        lines.push(`${indent}JZ ${target}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'JC': {
        const target = params.target || 'overflow';
        lines.push(`${indent}JC ${target}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      // 5. STACK & SUBROUTINES
      case 'CALL': {
        const funcName = params.funcName || 'subroutine';
        lines.push(`${indent}CALL ${funcName}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'RET': {
        lines.push(`${indent}RET`);
        instructionCount += 1;
        estimatedBytes += 1;
        break;
      }

      case 'PUSH': {
        const reg = params.reg || 'A';
        lines.push(`${indent}PUSH ${reg}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'POP': {
        const reg = params.reg || 'A';
        lines.push(`${indent}POP ${reg}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      // 6. I/O & PERIPHERALS
      case 'OUT': {
        const port = params.port ?? '3';
        const reg = params.reg || 'A';
        lines.push(`${indent}OUT ${port}, ${reg}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'OUTI': {
        const port = params.port ?? '1';
        const imm = params.imm ?? 255;
        lines.push(`${indent}OUTI ${port}, ${imm}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      case 'IN': {
        const reg = params.reg || 'A';
        const port = params.port ?? '0';
        lines.push(`${indent}IN ${reg}, ${port}`);
        instructionCount += 1;
        estimatedBytes += 3;
        break;
      }

      // 7. SYSTEM
      case 'HLT': {
        lines.push(`${indent}HLT`);
        instructionCount += 1;
        estimatedBytes += 1;
        break;
      }

      case 'SLEEP': {
        const cycles = params.cycles ?? 5;
        lines.push(`${indent}SLEEP ${cycles}`);
        instructionCount += 1;
        estimatedBytes += 2;
        break;
      }

      case 'NOP': {
        lines.push(`${indent}NOP`);
        instructionCount += 1;
        estimatedBytes += 1;
        break;
      }

      default: {
        warnings.push(`Ismeretlen blokk típus: ${blockType}`);
      }
    }
  }

  // Iterate top-level blocks
  blocks.forEach((block) => compileBlock(block));

  // Check if ending has HLT or JMP
  const hasTermination = blocks.some(
    (b) => b.blockType === 'HLT' || b.blockType === 'JMP'
  );
  if (!hasTermination && blocks.length > 0) {
    lines.push('');
    lines.push(
      language === 'hu'
        ? '; Automatikus leállítás a program végén'
        : '; Automatic halt at program termination'
    );
    lines.push('HLT');
    instructionCount += 1;
    estimatedBytes += 1;
  }

  return {
    code: lines.join('\n'),
    instructionCount,
    estimatedBytes,
    warnings,
  };
}
