import { CpuCoreInfo, CpuCoreType } from '../types/hardware';

export const CPU_CORES: Record<CpuCoreType, CpuCoreInfo> = {
  EDU8: {
    type: 'EDU8',
    name: 'Edu8 Von Neumann Standard 8-bit',
    nameHu: 'Edu8 Von Neumann Oktató Mag (Standard 8-bit)',
    shortDesc: 'Balanced educational 8-bit RISC/CISC core with 4 general-purpose registers and visible datapath microsteps.',
    shortDescHu: 'Kiegyensúlyozott oktatási 8-bites RISC/CISC mag 4 általános regiszterrel és látható adatút mikrolépésekkel.',
    architecture: 'VON_NEUMANN',
    isaType: 'CISC',
    dataBusWidth: 8,
    addressBusWidth: 8,
    registers: ['A (Acc)', 'B (General)', 'C (Counter)', 'D (Data)', 'PC', 'SP', 'IR', 'MAR', 'MBR'],
    flags: ['Z (Zero)', 'C (Carry)', 'N (Negative)', 'V (Overflow)', 'E (Equal)', 'G (Greater)', 'L (Less)'],
    maxMemory: 256,
    featuresHu: [
      '4 Általános célú 8-bites regiszter (A, B, C, D)',
      '6 fázisú mikrolépés szekvenszer (Fetch MAR -> Fetch IR -> Decode -> Operands -> ALU -> Writeback)',
      'Egységes 256 bájtos Von Neumann memóriatérkép',
      'Gazdag aritmetikai és I/O port utasításkészlet',
    ],
    featuresEn: [
      '4 General-purpose 8-bit registers (A, B, C, D)',
      '6-phase microstep sequencer (Fetch MAR -> Fetch IR -> Decode -> Operands -> ALU -> Writeback)',
      'Unified 256-byte Von Neumann memory map',
      'Rich arithmetic and I/O port instruction set',
    ],
    suitableForHu: 'Alapvető számítógép-architektúra, assembly programozás, ALU és busz működésének megértéséhez.',
    suitableForEn: 'Understanding computer architecture, assembly programming, ALU operations, and bus interconnects.',
  },

  MOS6502: {
    type: 'MOS6502',
    name: 'MOS 6502 / 6510 Microprocessor',
    nameHu: 'MOS 6502 / 6510 Klasszikus Mag',
    shortDesc: 'Legendary accumulator-indexed architecture powering Commodore 64, Apple II, and NES.',
    shortDescHu: 'Legendás akkumulátor és indexregiszteres mikroprocesszor (Commodore 64, Apple II, NES).',
    architecture: 'VON_NEUMANN',
    isaType: 'CISC',
    dataBusWidth: 8,
    addressBusWidth: 16,
    registers: ['A (Accumulator)', 'X (Index)', 'Y (Index)', 'PC', 'SP ($01xx)', 'Status (P)', 'MAR', 'MBR'],
    flags: ['N (Negative)', 'V (Overflow)', 'B (Break)', 'D (Decimal)', 'I (Interrupt)', 'Z (Zero)', 'C (Carry)'],
    maxMemory: 65536,
    featuresHu: [
      'Akkumulátor (A) + X és Y 8-bites indexregiszterek',
      'Zero-Page ($00-$FF) gyors közvetlen memóriacímzés',
      'Dedikált $0100-$01FF hardveres verem lap',
      'Decimal (BCD) aritmetika és I/O megszakítás maszkolás',
    ],
    featuresEn: [
      'Accumulator (A) + X and Y 8-bit index registers',
      'Zero-Page ($00-$FF) high-speed memory addressing',
      'Dedicated $0100-$01FF hardware stack page',
      'Decimal (BCD) mode arithmetic and interrupt masking',
    ],
    suitableForHu: 'Retro 8-bites rendszerek, indexed memóriacímzés, valós mikrogépek működésének tanulmányozására.',
    suitableForEn: 'Studying retro 8-bit microcomputers, indexed memory addressing, and classic processor design.',
  },

  Z80: {
    type: 'Z80',
    name: 'Zilog Z80-Inspired Extended CISC',
    nameHu: 'Zilog Z80 Bővített CISC Mag',
    shortDesc: 'Powerhouse 8-bit architecture with register pairs (BC, DE, HL), (HL) pointer indirect addressing, and rich bit ops.',
    shortDescHu: 'Nagyhatású 8-bites architektúra regiszterpárokkal (BC, DE, HL), (HL) mutatós címzéssel és bitműveletekkel.',
    architecture: 'VON_NEUMANN',
    isaType: 'CISC',
    dataBusWidth: 8,
    addressBusWidth: 16,
    registers: ['A (Acc)', 'F (Flags)', 'B', 'C', 'D', 'E', 'H (High)', 'L (Low)', 'PC', 'SP', 'IR'],
    flags: ['S (Sign)', 'Z (Zero)', 'H (Half-Carry)', 'P/V (Parity/Overflow)', 'N (Add/Sub)', 'C (Carry)'],
    maxMemory: 65536,
    featuresHu: [
      '8 regiszter (A, F, B, C, D, E, H, L) és 16-bites regiszterpárok (BC, DE, HL)',
      '(HL) közvetett memóriacímzés mutatóként való használata',
      'DJNZ (Decrement and Jump if Not Zero) gyors ciklusszervezés',
      'Kiterjesztett bit-tesztelő és I/O port címzési támogatás',
    ],
    featuresEn: [
      '8 registers (A, F, B, C, D, E, H, L) with 16-bit pairs (BC, DE, HL)',
      '(HL) indirect memory pointer addressing',
      'DJNZ (Decrement and Jump if Not Zero) loop construct',
      'Extended bit testing and I/O port addressing support',
    ],
    suitableForHu: 'Haladó assembly programozás, pointeres adatstruktúrák, tömbök és memóriamanipulációk oktatására.',
    suitableForEn: 'Teaching advanced assembly, pointer-based structures, arrays, and complex system routines.',
  },

  SAP1: {
    type: 'SAP1',
    name: 'SAP-1 Minimal Accumulator Core',
    nameHu: 'SAP-1 (Simple-As-Possible / Ben Eater) Minimál Mag',
    shortDesc: 'Ultra-minimalist accumulator-based educational architecture created for breadboard and TTL learning.',
    shortDescHu: 'Ultra-minimalista akkumulátor-alapú oktató mag, TTL és próbapanel CPU építés megértéséhez.',
    architecture: 'VON_NEUMANN',
    isaType: 'ACCUMULATOR',
    dataBusWidth: 8,
    addressBusWidth: 8,
    registers: ['A (Accumulator)', 'B (Operand Reg)', 'PC (4-bit / 8-bit)', 'IR', 'MAR'],
    flags: ['Z (Zero)', 'C (Carry)'],
    maxMemory: 256,
    featuresHu: [
      'Csak 2 regiszter: A (Akkumulátor) és B (Segédregiszter)',
      'Minden művelet közvetlenül az A regiszterre és a memóriára korlátozódik',
      'Rendkívül letisztult, minimális vezérlővonal készlet (HLT, MI, RI, RO, IO, II, AI, AO, EO, SU, BI, BO, OI, CE, CO, J)',
      'Kezdőknek az abszolút alapok elsajátítására',
    ],
    featuresEn: [
      'Only 2 registers: A (Accumulator) and B (Operand Register)',
      'All operations restricted strictly to Accumulator and RAM',
      'Ultra-clean minimal control line matrix',
      'Ideal for absolute beginners grasping discrete TTL logic',
    ],
    suitableForHu: 'Az alapvető digitális áramköri és vezérlőlogikai működés legegyszerűbb megértésére.',
    suitableForEn: 'Best for learning foundational digital logic, micro-instructions, and discrete CPU hardware.',
  },

  HARVARD8: {
    type: 'HARVARD8',
    name: 'Harvard-8 Dual-Bus Architecture',
    nameHu: 'Harvard-8 Párhuzamos Kétbuszos Mag',
    shortDesc: 'Separated Instruction ROM bus and Data RAM bus, enabling simultaneous instruction fetch and data operand access.',
    shortDescHu: 'Szétválasztott Utasítás ROM és Adat RAM buszok, egyidejű kódlehívás és adatkezelés.',
    architecture: 'HARVARD',
    isaType: 'RISC',
    dataBusWidth: 8,
    addressBusWidth: 8,
    registers: ['A', 'B', 'C', 'D', 'PC', 'SP', 'IR', 'CodeMAR', 'DataMAR'],
    flags: ['Z', 'C', 'N', 'V', 'E', 'G', 'L'],
    maxMemory: 512, // 256 Code + 256 Data
    featuresHu: [
      'Külön fizikai Kód Cím/Adatbusz és külön Adat Cím/Adatbusz',
      'Nincs Von Neumann szűk keresztmetszet (Bus Bottleneck)',
      'Kódmemória (ROM) és Adatmemória (RAM) fizikai elválasztása (biztonságosabb)',
      'Gyorsabb mikrolépéses végrehajtás és párhuzamos adatút',
    ],
    featuresEn: [
      'Separate physical Code Bus and Data Bus',
      'Eliminates the classic Von Neumann bottleneck',
      'Physically isolated Code ROM and Data RAM (high security)',
      'Faster microstep pipelining with simultaneous memory accesses',
    ],
    suitableForHu: 'Mikrokontrollerek (AVR/PIC/DSP), Harvard architektúra és párhuzamos buszkezelés tanulmányozására.',
    suitableForEn: 'Learning modern microcontroller architectures (AVR/DSP), dual-bus pipelining, and memory security.',
  },
};
