import { InstructionDef } from '../types/cpu';

export const REGISTER_INDEX: Record<string, number> = {
  A: 0,
  B: 1,
  C: 2,
  D: 3,
};

export const INDEX_TO_REGISTER: string[] = ['A', 'B', 'C', 'D'];

export const INSTRUCTIONS: Record<number, InstructionDef> = {
  0x00: {
    opcode: 0x00,
    mnemonic: 'NOP',
    operands: 1,
    description: 'No operation (waits 1 cycle)',
    descriptionHu: 'Üres művelet (1 órajelciklus várakozás)',
    category: 'SYSTEM',
  },
  0x01: {
    opcode: 0x01,
    mnemonic: 'HLT',
    operands: 1,
    description: 'Halt execution of the CPU',
    descriptionHu: 'A processzor végrehajtásának leállítása',
    category: 'SYSTEM',
  },
  0x02: {
    opcode: 0x02,
    mnemonic: 'SLEEP',
    operands: 2,
    description: 'Pause execution for N cycles',
    descriptionHu: 'Végrehajtás szüneteltetése N ciklusig',
    category: 'SYSTEM',
  },
  0x10: {
    opcode: 0x10,
    mnemonic: 'MOV',
    operands: 3,
    description: 'Copy value between registers (MOV dst, src)',
    descriptionHu: 'Érték másolása regiszterek között (MOV cél, forrás)',
    category: 'DATA',
  },
  0x11: {
    opcode: 0x11,
    mnemonic: 'LDI',
    operands: 3,
    description: 'Load immediate value into register (LDI reg, imm)',
    descriptionHu: 'Közvetlen érték betöltése regiszterbe (LDI reg, szám)',
    category: 'DATA',
  },
  0x12: {
    opcode: 0x12,
    mnemonic: 'LDA',
    operands: 2,
    description: 'Load from memory address into Accumulator A (LDA addr)',
    descriptionHu: 'Memóriacím tartalmának betöltése az A regiszterbe (LDA cím)',
    category: 'DATA',
  },
  0x13: {
    opcode: 0x13,
    mnemonic: 'STA',
    operands: 2,
    description: 'Store Accumulator A into memory address (STA addr)',
    descriptionHu: 'Az A regiszter értékének mentése memóriacímre (STA cím)',
    category: 'DATA',
  },
  0x14: {
    opcode: 0x14,
    mnemonic: 'LDR',
    operands: 3,
    description: 'Load from address in register (LDR dst, [src])',
    descriptionHu: 'Betöltés a regiszterben tárolt memóriacímről (LDR cél, [forrás])',
    category: 'DATA',
  },
  0x15: {
    opcode: 0x15,
    mnemonic: 'STR',
    operands: 3,
    description: 'Store into address in register (STR [dst], src)',
    descriptionHu: 'Mentés a regiszterben tárolt memóriacímre (STR [cél], forrás)',
    category: 'DATA',
  },
  0x16: {
    opcode: 0x16,
    mnemonic: 'PUSH',
    operands: 2,
    description: 'Push register value onto the Stack (PUSH reg)',
    descriptionHu: 'Regiszter értékének verembe (Stack) mentése (PUSH reg)',
    category: 'STACK',
  },
  0x17: {
    opcode: 0x17,
    mnemonic: 'POP',
    operands: 2,
    description: 'Pop value from Stack into register (POP reg)',
    descriptionHu: 'Érték kivétele a veremből regiszterbe (POP reg)',
    category: 'STACK',
  },
  0x20: {
    opcode: 0x20,
    mnemonic: 'ADD',
    operands: 3,
    description: 'Add two registers (ADD dst, src => dst += src)',
    descriptionHu: 'Két regiszter összeadása (ADD cél, forrás => cél += forrás)',
    category: 'ALU',
  },
  0x21: {
    opcode: 0x21,
    mnemonic: 'ADDI',
    operands: 3,
    description: 'Add immediate value to register (ADDI reg, imm)',
    descriptionHu: 'Közvetlen szám hozzáadása regiszterhez (ADDI reg, szám)',
    category: 'ALU',
  },
  0x22: {
    opcode: 0x22,
    mnemonic: 'SUB',
    operands: 3,
    description: 'Subtract register from register (SUB dst, src => dst -= src)',
    descriptionHu: 'Regiszter kivonása (SUB cél, forrás => cél -= forrás)',
    category: 'ALU',
  },
  0x23: {
    opcode: 0x23,
    mnemonic: 'SUBI',
    operands: 3,
    description: 'Subtract immediate from register (SUBI reg, imm)',
    descriptionHu: 'Közvetlen szám kivonása (SUBI reg, szám)',
    category: 'ALU',
  },
  0x24: {
    opcode: 0x24,
    mnemonic: 'INC',
    operands: 2,
    description: 'Increment register by 1 (INC reg)',
    descriptionHu: 'Regiszter növelése 1-gyel (INC reg)',
    category: 'ALU',
  },
  0x25: {
    opcode: 0x25,
    mnemonic: 'DEC',
    operands: 2,
    description: 'Decrement register by 1 (DEC reg)',
    descriptionHu: 'Regiszter csökkentése 1-gyel (DEC reg)',
    category: 'ALU',
  },
  0x26: {
    opcode: 0x26,
    mnemonic: 'AND',
    operands: 3,
    description: 'Bitwise AND between registers (AND dst, src)',
    descriptionHu: 'Bitenkénti ÉS művelet regiszterek között (AND cél, forrás)',
    category: 'ALU',
  },
  0x27: {
    opcode: 0x27,
    mnemonic: 'ANDI',
    operands: 3,
    description: 'Bitwise AND with immediate value (ANDI reg, imm)',
    descriptionHu: 'Bitenkénti ÉS közvetlen értékkel (ANDI reg, szám)',
    category: 'ALU',
  },
  0x28: {
    opcode: 0x28,
    mnemonic: 'OR',
    operands: 3,
    description: 'Bitwise OR between registers (OR dst, src)',
    descriptionHu: 'Bitenkénti VAGY művelet (OR cél, forrás)',
    category: 'ALU',
  },
  0x29: {
    opcode: 0x29,
    mnemonic: 'ORI',
    operands: 3,
    description: 'Bitwise OR with immediate value (ORI reg, imm)',
    descriptionHu: 'Bitenkénti VAGY közvetlen értékkel (ORI reg, szám)',
    category: 'ALU',
  },
  0x2a: {
    opcode: 0x2a,
    mnemonic: 'XOR',
    operands: 3,
    description: 'Bitwise XOR between registers (XOR dst, src)',
    descriptionHu: 'Bitenkénti Kizáró VAGY művelet (XOR cél, forrás)',
    category: 'ALU',
  },
  0x2b: {
    opcode: 0x2b,
    mnemonic: 'XORI',
    operands: 3,
    description: 'Bitwise XOR with immediate value (XORI reg, imm)',
    descriptionHu: 'Bitenkénti Kizáró VAGY közvetlen számmal (XORI reg, szám)',
    category: 'ALU',
  },
  0x2c: {
    opcode: 0x2c,
    mnemonic: 'NOT',
    operands: 2,
    description: 'Bitwise NOT inversion of register (NOT reg)',
    descriptionHu: 'Bitenkénti NEM tagadás (inverzió) (NOT reg)',
    category: 'ALU',
  },
  0x2d: {
    opcode: 0x2d,
    mnemonic: 'SHL',
    operands: 2,
    description: 'Shift left bits by 1 (SHL reg => reg << 1)',
    descriptionHu: 'Bitek léptetése balra 1 pozícióval (SHL reg => reg << 1)',
    category: 'ALU',
  },
  0x2e: {
    opcode: 0x2e,
    mnemonic: 'SHR',
    operands: 2,
    description: 'Shift right bits by 1 (SHR reg => reg >> 1)',
    descriptionHu: 'Bitek léptetése jobbra 1 pozícióval (SHR reg => reg >> 1)',
    category: 'ALU',
  },
  0x2f: {
    opcode: 0x2f,
    mnemonic: 'CMP',
    operands: 3,
    description: 'Compare two registers and set flags (CMP r1, r2)',
    descriptionHu: 'Két regiszter összehasonlítása és jelzőbitek beállítása (CMP r1, r2)',
    category: 'ALU',
  },
  0x30: {
    opcode: 0x30,
    mnemonic: 'CMPI',
    operands: 3,
    description: 'Compare register with immediate value (CMPI reg, imm)',
    descriptionHu: 'Regiszter összehasonlítása közvetlen értékkel (CMPI reg, szám)',
    category: 'ALU',
  },
  0x40: {
    opcode: 0x40,
    mnemonic: 'JMP',
    operands: 2,
    description: 'Unconditional jump to address (JMP addr/label)',
    descriptionHu: 'Feltétel nélküli ugrás memóriacímre (JMP cím/címke)',
    category: 'FLOW',
  },
  0x41: {
    opcode: 0x41,
    mnemonic: 'JZ',
    operands: 2,
    description: 'Jump if Zero flag is set (JZ addr/label)',
    descriptionHu: 'Ugrás, ha az eredmény nulla (Z jelzőbit = 1) (JZ cím)',
    category: 'FLOW',
  },
  0x42: {
    opcode: 0x42,
    mnemonic: 'JNZ',
    operands: 2,
    description: 'Jump if Zero flag is not set (JNZ addr/label)',
    descriptionHu: 'Ugrás, ha az eredmény nem nulla (Z jelzőbit = 0) (JNZ cím)',
    category: 'FLOW',
  },
  0x43: {
    opcode: 0x43,
    mnemonic: 'JC',
    operands: 2,
    description: 'Jump if Carry flag is set (JC addr/label)',
    descriptionHu: 'Ugrás, ha átvitel történt (Carry = 1) (JC cím)',
    category: 'FLOW',
  },
  0x44: {
    opcode: 0x44,
    mnemonic: 'JNC',
    operands: 2,
    description: 'Jump if Carry flag is not set (JNC addr/label)',
    descriptionHu: 'Ugrás, ha nincs átvitel (Carry = 0) (JNC cím)',
    category: 'FLOW',
  },
  0x45: {
    opcode: 0x45,
    mnemonic: 'JN',
    operands: 2,
    description: 'Jump if Negative flag is set (JN addr/label)',
    descriptionHu: 'Ugrás, ha az eredmény negatív (N = 1) (JN cím)',
    category: 'FLOW',
  },
  0x46: {
    opcode: 0x46,
    mnemonic: 'JG',
    operands: 2,
    description: 'Jump if Greater (from CMP) (JG addr/label)',
    descriptionHu: 'Ugrás, ha nagyobb (CMP után) (JG cím)',
    category: 'FLOW',
  },
  0x47: {
    opcode: 0x47,
    mnemonic: 'JL',
    operands: 2,
    description: 'Jump if Less (from CMP) (JL addr/label)',
    descriptionHu: 'Ugrás, ha kisebb (CMP után) (JL cím)',
    category: 'FLOW',
  },
  0x48: {
    opcode: 0x48,
    mnemonic: 'JE',
    operands: 2,
    description: 'Jump if Equal (from CMP) (JE addr/label)',
    descriptionHu: 'Ugrás, ha egyenlő (CMP után) (JE cím)',
    category: 'FLOW',
  },
  0x49: {
    opcode: 0x49,
    mnemonic: 'CALL',
    operands: 2,
    description: 'Call subroutine (pushes return address to Stack)',
    descriptionHu: 'Alprogram hívása (visszatérési cím mentése a verembe)',
    category: 'STACK',
  },
  0x4a: {
    opcode: 0x4a,
    mnemonic: 'RET',
    operands: 1,
    description: 'Return from subroutine (pops address from Stack)',
    descriptionHu: 'Visszatérés alprogramból (cím visszatöltése a veremből)',
    category: 'STACK',
  },
  0x50: {
    opcode: 0x50,
    mnemonic: 'OUT',
    operands: 3,
    description: 'Write register to I/O port (OUT port, reg)',
    descriptionHu: 'Regiszter kiírása I/O portra (OUT port, reg)',
    category: 'IO',
  },
  0x51: {
    opcode: 0x51,
    mnemonic: 'OUTI',
    operands: 3,
    description: 'Write immediate value to I/O port (OUTI port, imm)',
    descriptionHu: 'Közvetlen érték kiírása I/O portra (OUTI port, szám)',
    category: 'IO',
  },
  0x52: {
    opcode: 0x52,
    mnemonic: 'IN',
    operands: 3,
    description: 'Read from I/O port into register (IN reg, port)',
    descriptionHu: 'Beolvasás I/O portról regiszterbe (IN reg, port)',
    category: 'IO',
  },
  0x53: {
    opcode: 0x53,
    mnemonic: 'RAND',
    operands: 2,
    description: 'Generate pseudo-random 8-bit number into register (RAND reg)',
    descriptionHu: 'Véletlenszerű 8 bites szám generálása regiszterbe (RAND reg)',
    category: 'ALU',
  },
};

export const MNEMONIC_TO_OPCODE: Record<string, number> = Object.values(
  INSTRUCTIONS
).reduce((acc, inst) => {
  acc[inst.mnemonic.toUpperCase()] = inst.opcode;
  return acc;
}, {} as Record<string, number>);
