import { BlockDefinition } from '../types/mcuBlock';

export const BLOCK_DEFINITIONS: BlockDefinition[] = [
  // ==================== 1. CONTROL & LOOPS ====================
  {
    id: 'setup_header',
    type: 'SETUP_HEADER',
    category: 'CONTROL',
    name: 'Setup Once at Startup',
    nameHu: 'Egyszer fut le induláskor (setup)',
    description: 'Initializes pins, baud rates, and hardware peripherals.',
    descriptionHu: 'Lábak, soros sebesség és hardveres perifériák inicializálása.',
    color: 'border-amber-500/60 bg-amber-950/30 text-amber-300',
    accentColor: '#F59E0B',
    iconName: 'Sparkles',
    hasChildren: true,
    defaultParams: {},
    paramSchema: [],
  },
  {
    id: 'main_loop',
    type: 'MAIN_LOOP',
    category: 'CONTROL',
    name: 'Infinite Main Loop',
    nameHu: 'Végtelen Főciklus (loop)',
    description: 'Repeats instructions continuously while powered.',
    descriptionHu: 'Folyamatosan, végtelenítve ismétli a benne lévő blokkokat.',
    color: 'border-amber-500/60 bg-amber-950/30 text-amber-300',
    accentColor: '#F59E0B',
    iconName: 'RotateCcw',
    hasChildren: true,
    defaultParams: {},
    paramSchema: [],
  },
  {
    id: 'delay_ms',
    type: 'DELAY_MS',
    category: 'CONTROL',
    name: 'Delay (Wait ms)',
    nameHu: 'Késleltetés / Várakozás (ms)',
    description: 'Pauses execution for a specified amount of milliseconds.',
    descriptionHu: 'Szünetelteti a programfutást megadott ezredmásodpercig.',
    color: 'border-amber-500/60 bg-amber-950/30 text-amber-300',
    accentColor: '#F59E0B',
    iconName: 'Clock',
    defaultParams: { ms: 100 },
    paramSchema: [
      {
        key: 'ms',
        label: 'Milliseconds',
        labelHu: 'Időtartam (ms)',
        type: 'number',
        min: 1,
        max: 10000,
        step: 50,
      },
    ],
  },
  {
    id: 'if_condition',
    type: 'IF_CONDITION',
    category: 'CONTROL',
    name: 'If Condition Then',
    nameHu: 'Ha Feltétel Teljesül (IF)',
    description: 'Executes inner blocks if condition is true.',
    descriptionHu: 'Csak akkor hajtja végre a belső blokkokat, ha a feltétel igaz.',
    color: 'border-amber-500/60 bg-amber-950/30 text-amber-300',
    accentColor: '#F59E0B',
    iconName: 'GitBranch',
    hasChildren: true,
    defaultParams: { leftVal: 'analogRead(A0)', operator: '>', rightVal: '500' },
    paramSchema: [
      {
        key: 'leftVal',
        label: 'Variable / Input',
        labelHu: 'Bemenet / Változó',
        type: 'select',
        options: [
          { label: 'Potentiometer (A0)', labelHu: 'Potenciométer (A0)', value: 'analogRead(A0)' },
          { label: 'Button Pressed (D2)', labelHu: 'Gomb Nyomva (D2)', value: 'digitalRead(2)' },
          { label: 'Sensor Temp', labelHu: 'Hőmérséklet Szenzor', value: 'tempCelsius' },
          { label: 'Custom Variable X', labelHu: 'Egyéni Változó X', value: 'valX' },
        ],
      },
      {
        key: 'operator',
        label: 'Operator',
        labelHu: 'Feltétel',
        type: 'select',
        options: [
          { label: '> Greater than', labelHu: '> Nagyobb mint', value: '>' },
          { label: '< Less than', labelHu: '< Kisebb mint', value: '<' },
          { label: '== Equals', labelHu: '== Egyenlő', value: '==' },
          { label: '!= Not equals', labelHu: '!= Nem egyenlő', value: '!=' },
        ],
      },
      {
        key: 'rightVal',
        label: 'Threshold / Value',
        labelHu: 'Küszöbérték',
        type: 'text',
      },
    ],
  },

  // ==================== 2. DIGITAL & ANALOG I/O ====================
  {
    id: 'pin_mode',
    type: 'PIN_MODE',
    category: 'IO',
    name: 'Configure Pin Mode',
    nameHu: 'Láb Üzemmód Beállítása',
    description: 'Sets GPIO pin direction (OUTPUT, INPUT, INPUT_PULLUP).',
    descriptionHu: 'Beállítja a GPIO láb irányát (Kimenet, Bemenet, Felhúzó ellenállás).',
    color: 'border-blue-500/60 bg-blue-950/30 text-blue-300',
    accentColor: '#3B82F6',
    iconName: 'Cpu',
    defaultParams: { pin: '13', mode: 'OUTPUT' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Pin',
        labelHu: 'Digitális Láb',
        type: 'select',
        options: [
          { label: 'D13 (Onboard LED)', labelHu: 'D13 (Beépített LED)', value: '13' },
          { label: 'D2 (Button / INT0)', labelHu: 'D2 (Gomb / INT0)', value: '2' },
          { label: 'D3 (PWM Out)', labelHu: 'D3 (PWM Kimenet)', value: '3' },
          { label: 'D5 (PWM Out)', labelHu: 'D5 (PWM Kimenet)', value: '5' },
          { label: 'D6 (PWM Out)', labelHu: 'D6 (PWM Kimenet)', value: '6' },
          { label: 'D7 (nRF24 CE)', labelHu: 'D7 (nRF24 CE)', value: '7' },
          { label: 'D8 (Relay / CSN)', labelHu: 'D8 (Relé / CSN)', value: '8' },
          { label: 'D9 (Servo PWM)', labelHu: 'D9 (Szervó PWM)', value: '9' },
        ],
      },
      {
        key: 'mode',
        label: 'Mode',
        labelHu: 'Üzemmód',
        type: 'select',
        options: [
          { label: 'OUTPUT (Kimenet)', labelHu: 'OUTPUT (Kimenet)', value: 'OUTPUT' },
          { label: 'INPUT (Bemenet)', labelHu: 'INPUT (Bemenet)', value: 'INPUT' },
          { label: 'INPUT_PULLUP (Felhúzott)', labelHu: 'INPUT_PULLUP (Felhúzott)', value: 'INPUT_PULLUP' },
        ],
      },
    ],
  },
  {
    id: 'digital_write',
    type: 'DIGITAL_WRITE',
    category: 'IO',
    name: 'Digital Write Pin',
    nameHu: 'Digitális Láb Írása (HIGH/LOW)',
    description: 'Outputs 5V (HIGH) or 0V (LOW) to a pin.',
    descriptionHu: '5V (HIGH) vagy 0V (LOW) logikai szintet kapcsol a kimeneti lábra.',
    color: 'border-blue-500/60 bg-blue-950/30 text-blue-300',
    accentColor: '#3B82F6',
    iconName: 'Zap',
    defaultParams: { pin: '13', state: 'HIGH' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Pin',
        labelHu: 'Láb',
        type: 'select',
        options: [
          { label: 'D13 (LED)', labelHu: 'D13 (LED)', value: '13' },
          { label: 'D8 (Relé)', labelHu: 'D8 (Relé)', value: '8' },
          { label: 'D7 (CE)', labelHu: 'D7 (CE)', value: '7' },
          { label: 'D2 (DE/RE RS485)', labelHu: 'D2 (DE/RE RS485)', value: '2' },
        ],
      },
      {
        key: 'state',
        label: 'State',
        labelHu: 'Szint',
        type: 'select',
        options: [
          { label: 'HIGH (5V - Be)', labelHu: 'HIGH (5V - Be)', value: 'HIGH' },
          { label: 'LOW (0V - Ki)', labelHu: 'LOW (0V - Ki)', value: 'LOW' },
        ],
      },
    ],
  },
  {
    id: 'analog_read_var',
    type: 'ANALOG_READ_VAR',
    category: 'IO',
    name: 'Read Analog Sensor (A0..A5)',
    nameHu: 'Analóg Bemenet Olvasása (0..1023)',
    description: 'Reads ADC 10-bit value from an analog channel into a variable.',
    descriptionHu: 'Beolvassa az analóg feszültséget egy változóba (10-bit ADC, 0..1023).',
    color: 'border-blue-500/60 bg-blue-950/30 text-blue-300',
    accentColor: '#3B82F6',
    iconName: 'Gauge',
    defaultParams: { pin: 'A0', varName: 'potValue' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Analog Pin',
        labelHu: 'Analóg Láb',
        type: 'select',
        options: [
          { label: 'A0 (Potentiometer / Joystick X)', labelHu: 'A0 (Potenciométer / Joystick X)', value: 'A0' },
          { label: 'A1 (Joystick Y / Sensor)', labelHu: 'A1 (Joystick Y / Szenzor)', value: 'A1' },
          { label: 'A2 (LM35 Hőmérő)', labelHu: 'A2 (LM35 Hőmérő)', value: 'A2' },
          { label: 'A3 (LDR Fényérzékelő)', labelHu: 'A3 (LDR Fényérzékelő)', value: 'A3' },
        ],
      },
      {
        key: 'varName',
        label: 'Store in Variable',
        labelHu: 'Változó Neve',
        type: 'text',
      },
    ],
  },

  // ==================== ADC (ANALOG-TO-DIGITAL CONVERTER) ====================
  {
    id: 'adc_config',
    type: 'ADC_CONFIG',
    category: 'ADC',
    name: 'Configure ADC Hardware Registers',
    nameHu: 'ADC Hardver Konfiguráció (Referencia, Előosztó, Igazítás)',
    description: 'Sets ADMUX reference voltage, ADCSRA clock prescaler, and ADLAR alignment.',
    descriptionHu: 'Beállítja az ADMUX referenciát, az ADCSRA előosztót és az ADLAR bitet.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Activity',
    defaultParams: { reference: 'DEFAULT', prescaler: '128', adlar: 'RIGHT' },
    paramSchema: [
      {
        key: 'reference',
        label: 'Voltage Reference',
        labelHu: 'Feszültség Referencia',
        type: 'select',
        options: [
          { label: 'AVCC (5.0V Supply)', labelHu: 'AVCC (5.0V Tápfeszültség)', value: 'DEFAULT' },
          { label: 'INTERNAL (1.1V Bandgap)', labelHu: 'INTERNAL (1.1V Belső Sávhéj)', value: 'INTERNAL' },
          { label: 'EXTERNAL (AREF Pin)', labelHu: 'EXTERNAL (Külső AREF Láb)', value: 'EXTERNAL' },
        ],
      },
      {
        key: 'prescaler',
        label: 'ADC Clock Prescaler',
        labelHu: 'ADC Órajel Előosztó',
        type: 'select',
        options: [
          { label: '/128 (125 kHz @ 16MHz - Ajánlott)', labelHu: '/128 (125 kHz @ 16MHz - Ajánlott)', value: '128' },
          { label: '/64 (250 kHz)', labelHu: '/64 (250 kHz)', value: '64' },
          { label: '/32 (500 kHz)', labelHu: '/32 (500 kHz)', value: '32' },
          { label: '/16 (1 MHz)', labelHu: '/16 (1 MHz)', value: '16' },
        ],
      },
      {
        key: 'adlar',
        label: 'Result Alignment',
        labelHu: 'Eredmény Igazítása',
        type: 'select',
        options: [
          { label: 'Right Adjusted (10-bit: ADCH:ADCL)', labelHu: 'Jobbra zárt (10-bit teljes pontosság)', value: 'RIGHT' },
          { label: 'Left Adjusted (8-bit: csak ADCH olvasás)', labelHu: 'Balra zárt (8-bit gyors olvasás ADCH)', value: 'LEFT' },
        ],
      },
    ],
  },
  {
    id: 'adc_read_voltage',
    type: 'ADC_READ_VOLTAGE',
    category: 'ADC',
    name: 'ADC Read Voltage (0.00V .. 5.00V)',
    nameHu: 'ADC Feszültség Beolvasása (Volt)',
    description: 'Reads ADC and mathematically converts 10-bit raw code into precise floating-point Volts.',
    descriptionHu: 'Beolvassa az ADC-t és lebegőpontos feszültséggé (Volt) konvertálja a referenciához képest.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Gauge',
    defaultParams: { pin: 'A0', vRef: '5.0', varName: 'sensorVoltage' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Analog Pin',
        labelHu: 'Analóg Láb',
        type: 'select',
        options: [
          { label: 'A0 (Potentiometer)', labelHu: 'A0 (Potenciométer)', value: 'A0' },
          { label: 'A1 (Joystick Y / Sensor)', labelHu: 'A1 (Joystick Y / Szenzor)', value: 'A1' },
          { label: 'A2 (LM35 Hőmérő)', labelHu: 'A2 (LM35 Hőmérő)', value: 'A2' },
          { label: 'A3 (LDR Fényérzékelő)', labelHu: 'A3 (LDR Fényérzékelő)', value: 'A3' },
          { label: 'A4 (I2C SDA / Analog)', labelHu: 'A4 (I2C SDA / Analóg)', value: 'A4' },
          { label: 'A5 (I2C SCL / Analog)', labelHu: 'A5 (I2C SCL / Analóg)', value: 'A5' },
        ],
      },
      {
        key: 'vRef',
        label: 'VREF Reference (V)',
        labelHu: 'VREF Referencia (Volt)',
        type: 'number',
        min: 1.0,
        max: 5.0,
        step: 0.1,
      },
      {
        key: 'varName',
        label: 'Store in Float Variable',
        labelHu: 'Változó Neve (float)',
        type: 'text',
      },
    ],
  },
  {
    id: 'adc_oversample_average',
    type: 'ADC_OVERSAMPLE_AVERAGE',
    category: 'ADC',
    name: 'ADC Oversampling & Averaging Filter',
    nameHu: 'ADC Túlmintavételezés & Átlagoló Zajszűrő',
    description: 'Reads multiple ADC samples in a burst and calculates moving average to suppress noise.',
    descriptionHu: 'Több egymást követő ADC mintát vesz és átlagolja a zajok kiszűrésére.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Sliders',
    defaultParams: { pin: 'A0', samples: '16', targetVar: 'filteredAdc' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Analog Pin',
        labelHu: 'Analóg Láb',
        type: 'select',
        options: [
          { label: 'A0 (Potenciométer)', labelHu: 'A0 (Potenciométer)', value: 'A0' },
          { label: 'A1 (Szenzor)', labelHu: 'A1 (Szenzor)', value: 'A1' },
          { label: 'A2 (LM35 Hőmérő)', labelHu: 'A2 (LM35 Hőmérő)', value: 'A2' },
          { label: 'A3 (LDR Fényérzékelő)', labelHu: 'A3 (LDR Fényérzékelő)', value: 'A3' },
        ],
      },
      {
        key: 'samples',
        label: 'Number of Samples',
        labelHu: 'Minták Száma (N)',
        type: 'select',
        options: [
          { label: '4 samples (Gyors)', labelHu: '4 minta (Gyors)', value: '4' },
          { label: '16 samples (+1 bit effektív pontosság)', labelHu: '16 minta (+1 bit ENOB)', value: '16' },
          { label: '64 samples (+2 bit túlmintavételezés)', labelHu: '64 minta (+2 bit ENOB)', value: '64' },
        ],
      },
      {
        key: 'targetVar',
        label: 'Target Variable',
        labelHu: 'Cél Változó Neve',
        type: 'text',
      },
    ],
  },
  {
    id: 'adc_start_async',
    type: 'ADC_START_ASYNC',
    category: 'ADC',
    name: 'ADC Start Async Conversion (ADSC)',
    nameHu: 'ADC Aszinkron Átalakítás Indítása (ADSC=1)',
    description: 'Triggers hardware Successive Approximation without blocking the CPU.',
    descriptionHu: 'Elindítja a hardveres SAR átalakítást a CPU blokkolása nélkül.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Play',
    defaultParams: { channel: '0' },
    paramSchema: [
      {
        key: 'channel',
        label: 'ADC Channel (0..7)',
        labelHu: 'ADC Csatorna (0..7)',
        type: 'select',
        options: [
          { label: 'ADC0 (A0)', labelHu: 'ADC0 (A0)', value: '0' },
          { label: 'ADC1 (A1)', labelHu: 'ADC1 (A1)', value: '1' },
          { label: 'ADC2 (A2)', labelHu: 'ADC2 (A2)', value: '2' },
          { label: 'ADC3 (A3)', labelHu: 'ADC3 (A3)', value: '3' },
        ],
      },
    ],
  },
  {
    id: 'adc_wait_complete',
    type: 'ADC_WAIT_COMPLETE',
    category: 'ADC',
    name: 'ADC Wait for Ready (Poll ADSC)',
    nameHu: 'ADC Várakozás Befejezésre (ADSC Polling)',
    description: 'Waits in a loop until the SAR conversion finishes and ADSC clears to 0.',
    descriptionHu: 'Ciklusban megvárja, amíg a hardveres átalakítás véget ér (ADSC bit 0 lesz).',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Clock',
    defaultParams: { targetVar: 'adcResult' },
    paramSchema: [
      {
        key: 'targetVar',
        label: 'Save 10-bit Result to',
        labelHu: '10-bites Eredmény Mentése Változóba',
        type: 'text',
      },
    ],
  },
  {
    id: 'adc_isr_block',
    type: 'ADC_ISR_BLOCK',
    category: 'ADC',
    name: 'ADC Interrupt Handler ISR(ADC_vect)',
    nameHu: 'ADC Megszakításkezelő ISR(ADC_vect)',
    description: 'Interrupt service routine executed automatically whenever an ADC conversion completes.',
    descriptionHu: 'Megszakítási alprogram, amely azonnal lefut, amint az ADC átalakítás kész.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Zap',
    hasChildren: true,
    defaultParams: { readAdcVar: 'lastAdcVal' },
    paramSchema: [
      {
        key: 'readAdcVar',
        label: 'Store Result in Variable',
        labelHu: 'Eredmény Mentése Változóba',
        type: 'text',
      },
    ],
  },

  // ==================== PWM & TIMERS (PULSE WIDTH MODULATION) ====================
  {
    id: 'pwm_config_timer',
    type: 'PWM_CONFIG_TIMER',
    category: 'PWM',
    name: 'Configure Hardware Timer PWM Registers',
    nameHu: 'Hardveres Timer PWM Konfiguráció (TCCRxA/B)',
    description: 'Sets timer mode (Fast PWM, Phase Correct, CTC), prescaler, and non-inverting compare match.',
    descriptionHu: 'Közvetlenül beállítja a mikrokontroller Timer regisztereit (Fast PWM, Phase Correct, Előosztó).',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Sliders',
    defaultParams: { timer: 'TIMER0', mode: 'FAST_PWM', prescaler: '64', pin: '6' },
    paramSchema: [
      {
        key: 'timer',
        label: 'Timer Unit',
        labelHu: 'Időzítő Egység',
        type: 'select',
        options: [
          { label: 'Timer0 (8-bit: D5, D6)', labelHu: 'Timer0 (8-bit: D5, D6)', value: 'TIMER0' },
          { label: 'Timer1 (16-bit: D9, D10)', labelHu: 'Timer1 (16-bit: D9, D10)', value: 'TIMER1' },
          { label: 'Timer2 (8-bit: D3, D11)', labelHu: 'Timer2 (8-bit: D3, D11)', value: 'TIMER2' },
        ],
      },
      {
        key: 'mode',
        label: 'PWM Mode',
        labelHu: 'PWM Működési Mód',
        type: 'select',
        options: [
          { label: 'Fast PWM (Single-slope ramp, Gyorsabb)', labelHu: 'Fast PWM (Fűrészfog jel, Nagy frekvencia)', value: 'FAST_PWM' },
          { label: 'Phase Correct PWM (Dual-slope háromszög jel)', labelHu: 'Phase Correct PWM (Szimmetrikus, Motorokhoz)', value: 'PHASE_CORRECT' },
          { label: 'CTC (Clear Timer on Compare - Frekvencia)', labelHu: 'CTC (Összehasonlításkor törlés - Hang)', value: 'CTC' },
        ],
      },
      {
        key: 'prescaler',
        label: 'Timer Clock Prescaler',
        labelHu: 'Órajel Előosztó',
        type: 'select',
        options: [
          { label: '/1 (Nincs osztás - 62.5 kHz Fast PWM)', labelHu: '/1 (Nincs osztás - 62.5 kHz Fast PWM)', value: '1' },
          { label: '/8 (7.8 kHz Fast PWM)', labelHu: '/8 (7.8 kHz Fast PWM)', value: '8' },
          { label: '/64 (976 Hz Fast PWM / 490 Hz Arduino alapértelmezett)', labelHu: '/64 (976 Hz Fast PWM / 490 Hz Standard)', value: '64' },
          { label: '/256 (244 Hz Fast PWM)', labelHu: '/256 (244 Hz Fast PWM)', value: '256' },
          { label: '/1024 (61 Hz Fast PWM)', labelHu: '/1024 (61 Hz Fast PWM)', value: '1024' },
        ],
      },
    ],
  },
  {
    id: 'pwm_write_duty',
    type: 'PWM_WRITE_DUTY',
    category: 'PWM',
    name: 'PWM Output Duty Cycle (analogWrite 0..255)',
    nameHu: 'PWM Kitöltési Tényező Írása (0..255 / OCRx)',
    description: 'Sets duty cycle on a PWM pin (D3, D5, D6, D9, D10, D11) using analogWrite or OCR register.',
    descriptionHu: 'Beállítja az analóg PWM kimeneti kitöltést (0 = 0V, 128 = 2.5V átlag, 255 = 5V).',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Gauge',
    defaultParams: { pin: '6', dutyVal: '128' },
    paramSchema: [
      {
        key: 'pin',
        label: 'PWM Pin',
        labelHu: 'PWM Láb',
        type: 'select',
        options: [
          { label: 'D3 (Timer2 - OC2B)', labelHu: 'D3 (Timer2 - OC2B)', value: '3' },
          { label: 'D5 (Timer0 - OC0B)', labelHu: 'D5 (Timer0 - OC0B)', value: '5' },
          { label: 'D6 (Timer0 - OC0A)', labelHu: 'D6 (Timer0 - OC0A)', value: '6' },
          { label: 'D9 (Timer1 - OC1A)', labelHu: 'D9 (Timer1 - OC1A)', value: '9' },
          { label: 'D10 (Timer1 - OC1B)', labelHu: 'D10 (Timer1 - OC1B)', value: '10' },
          { label: 'D11 (Timer2 - OC2A)', labelHu: 'D11 (Timer2 - OC2A)', value: '11' },
        ],
      },
      {
        key: 'dutyVal',
        label: 'Duty Value (0..255 or Var)',
        labelHu: 'Kitöltési Érték (0..255 vagy Változó)',
        type: 'text',
      },
    ],
  },
  {
    id: 'pwm_fade_breathe',
    type: 'PWM_FADE_BREATHE',
    category: 'PWM',
    name: 'PWM LED Fading / Breathing Cycle',
    nameHu: 'PWM LED Lágy Pulzálás / Fényerő Lélegeztetés',
    description: 'Smoothly cycles duty cycle up and down with logarithmic perception smoothing.',
    descriptionHu: 'Folyamatosan növeli és csökkenti a fényerőt finom, szembarát optikai görbével.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Activity',
    defaultParams: { pin: '6', stepDelayMs: '10', maxDuty: '255' },
    paramSchema: [
      {
        key: 'pin',
        label: 'PWM Pin',
        labelHu: 'PWM Láb',
        type: 'select',
        options: [
          { label: 'D6 (Timer0 LED)', labelHu: 'D6 (Timer0 LED)', value: '6' },
          { label: 'D9 (Timer1 LED)', labelHu: 'D9 (Timer1 LED)', value: '9' },
          { label: 'D3 (Timer2 LED)', labelHu: 'D3 (Timer2 LED)', value: '3' },
          { label: 'D5 (Timer0 LED)', labelHu: 'D5 (Timer0 LED)', value: '5' },
        ],
      },
      {
        key: 'stepDelayMs',
        label: 'Step Delay (ms)',
        labelHu: 'Lépésenkénti Késleltetés (ms)',
        type: 'number',
        min: 1,
        max: 50,
      },
    ],
  },
  {
    id: 'pwm_motor_hbridge',
    type: 'PWM_MOTOR_HBRIDGE',
    category: 'PWM',
    name: 'PWM H-Bridge DC Motor Speed & Direction',
    nameHu: 'PWM H-Híd DC Motor Fordulatszám & Forgásirány',
    description: 'Controls motor speed via PWM pin and direction via IN1/IN2 directional logic pins.',
    descriptionHu: 'Vezérli a motor sebességét PWM jellel és a forgásirányt az IN1/IN2 logikai lábakkal.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'RotateCcw',
    defaultParams: {
      pwmPin: '5',
      dirPinA: '7',
      dirPinB: '8',
      speedVal: '200',
      direction: 'FORWARD',
    },
    paramSchema: [
      {
        key: 'pwmPin',
        label: 'PWM Enable Pin',
        labelHu: 'PWM Sebesség Láb',
        type: 'select',
        options: [
          { label: 'D5 (PWM ENA)', labelHu: 'D5 (PWM ENA)', value: '5' },
          { label: 'D6 (PWM ENB)', labelHu: 'D6 (PWM ENB)', value: '6' },
          { label: 'D9 (PWM ENA)', labelHu: 'D9 (PWM ENA)', value: '9' },
        ],
      },
      {
        key: 'direction',
        label: 'Direction',
        labelHu: 'Forgásirány',
        type: 'select',
        options: [
          { label: 'Forward (Előre)', labelHu: 'Előre (Forward)', value: 'FORWARD' },
          { label: 'Reverse (Hátra)', labelHu: 'Hátra (Reverse)', value: 'REVERSE' },
          { label: 'Brake / Stop (Fék)', labelHu: 'Fék / Stop', value: 'BRAKE' },
        ],
      },
      {
        key: 'speedVal',
        label: 'Speed (0..255 or Var)',
        labelHu: 'Sebesség (0..255 vagy Változó)',
        type: 'text',
      },
    ],
  },
  {
    id: 'pwm_servo_angle',
    type: 'PWM_SERVO_ANGLE',
    category: 'PWM',
    name: 'PWM Precision Servo Position (0°..180°)',
    nameHu: 'PWM Szervómotor Pozíció (0°..180°)',
    description: 'Generates 50Hz 1.0ms-2.0ms pulse-width modulation for SG90 / MG996R servo positioners.',
    descriptionHu: '50Hz frekvenciájú 1.0ms - 2.0ms kitöltésű precíz szervó vezérlő impulzust állít elő.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Gauge',
    defaultParams: { pin: '9', angleVal: '90' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Servo PWM Pin',
        labelHu: 'Szervó PWM Láb',
        type: 'select',
        options: [
          { label: 'D9 (Timer1 OC1A)', labelHu: 'D9 (Timer1 OC1A)', value: '9' },
          { label: 'D10 (Timer1 OC1B)', labelHu: 'D10 (Timer1 OC1B)', value: '10' },
          { label: 'D3 (Timer2 OC2B)', labelHu: 'D3 (Timer2 OC2B)', value: '3' },
        ],
      },
      {
        key: 'angleVal',
        label: 'Angle (0..180 or Var)',
        labelHu: 'Szög (0..180° vagy Változó)',
        type: 'text',
      },
    ],
  },
  {
    id: 'pwm_tone_buzzer',
    type: 'PWM_TONE_BUZZER',
    category: 'PWM',
    name: 'PWM Audio Frequency Tone (Buzzer)',
    nameHu: 'PWM Audio Hangfrekvencia (Csipogó / CTC)',
    description: 'Generates square wave audio tone with specific frequency (Hz) and duration on piezo buzzer.',
    descriptionHu: 'Négyszögjel hangfrekvenciát (Hz) és időtartamot generál a piezo hangszóróra.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Activity',
    defaultParams: { pin: '3', frequency: '440', durationMs: '500' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Buzzer Pin',
        labelHu: 'Csipogó Láb',
        type: 'select',
        options: [
          { label: 'D3 (Piezo Buzzer)', labelHu: 'D3 (Piezo Csipogó)', value: '3' },
          { label: 'D5 (Audio Out)', labelHu: 'D5 (Audio Kimenet)', value: '5' },
          { label: 'D11 (Audio Out)', labelHu: 'D11 (Audio Kimenet)', value: '11' },
        ],
      },
      {
        key: 'frequency',
        label: 'Frequency in Hz (e.g. 440 = Note A4)',
        labelHu: 'Frekvencia Hz-ben (pl. 440 = A4 hang)',
        type: 'text',
      },
      {
        key: 'durationMs',
        label: 'Duration (ms)',
        labelHu: 'Időtartam (ms)',
        type: 'number',
        min: 10,
        max: 5000,
      },
    ],
  },

  // ==================== 3. COMMUNICATION & PROTOCOL BRIDGES ====================
  {
    id: 'nrf24_init',
    type: 'NRF24_INIT',
    category: 'PROTOCOLS',
    name: 'nRF24L01+ Radio Initialize',
    nameHu: 'nRF24L01+ Rádió Inicializálás (2.4GHz)',
    description: 'Sets up nRF24 radio module with channel, pipes, and transmission power.',
    descriptionHu: 'Beállítja az nRF24 rádiós adóvevőt csatornával és adatsebességgel.',
    color: 'border-cyan-500/60 bg-cyan-950/30 text-cyan-300',
    accentColor: '#06B6D4',
    iconName: 'Radio',
    defaultParams: { channel: '76', pipeAddress: 'NODE1', role: 'TX' },
    paramSchema: [
      {
        key: 'role',
        label: 'Role',
        labelHu: 'Üzemmód',
        type: 'select',
        options: [
          { label: 'Transmitter (Adó - MCU A)', labelHu: 'Transmitter (Adó - MCU A)', value: 'TX' },
          { label: 'Receiver (Vevő - MCU B)', labelHu: 'Receiver (Vevő - MCU B)', value: 'RX' },
        ],
      },
      {
        key: 'channel',
        label: 'RF Channel (0..125)',
        labelHu: 'RF Csatorna (0..125)',
        type: 'number',
        min: 0,
        max: 125,
      },
      {
        key: 'pipeAddress',
        label: 'Pipe Address',
        labelHu: 'Cső Cím (5 karakter)',
        type: 'text',
      },
    ],
  },
  {
    id: 'nrf24_send_packet',
    type: 'NRF24_SEND_PACKET',
    category: 'PROTOCOLS',
    name: 'nRF24 Send Telemetry Packet',
    nameHu: 'nRF24 Rádiós Adatcsomag Küldése',
    description: 'Transmits joystick, throttle, and button state over 2.4GHz with Auto-ACK.',
    descriptionHu: 'Kiküldi a botkormány, sebesség és gombállapotot 2.4GHz-en Auto-ACK-kal.',
    color: 'border-cyan-500/60 bg-cyan-950/30 text-cyan-300',
    accentColor: '#06B6D4',
    iconName: 'Radio',
    defaultParams: {
      joyXSource: 'analogRead(A0)',
      throttleSource: 'potValue',
      btnSource: 'digitalRead(2)',
    },
    paramSchema: [
      {
        key: 'joyXSource',
        label: 'Steering / JoyX Value',
        labelHu: 'Kormányzás / JoyX Bemenet',
        type: 'text',
      },
      {
        key: 'throttleSource',
        label: 'Throttle / Speed Value',
        labelHu: 'Sebesség / Gáz Bemenet',
        type: 'text',
      },
      {
        key: 'btnSource',
        label: 'Button / Headlights Switch',
        labelHu: 'Gomb / Lámpa Kapcsoló',
        type: 'text',
      },
    ],
  },
  {
    id: 'nrf24_receive_packet',
    type: 'NRF24_RECEIVE_PACKET',
    category: 'PROTOCOLS',
    name: 'nRF24 On Packet Received Event',
    nameHu: 'nRF24 Ha Új Rádiócsomag Érkezik',
    description: 'Triggers when a valid wireless packet arrives from MCU A.',
    descriptionHu: 'Akkor fut le, amikor érvényes 2.4GHz-es rádiócsomag érkezik az adótól.',
    color: 'border-cyan-500/60 bg-cyan-950/30 text-cyan-300',
    accentColor: '#06B6D4',
    iconName: 'Radio',
    hasChildren: true,
    defaultParams: {},
    paramSchema: [],
  },
  {
    id: 'i2c_master_write',
    type: 'I2C_MASTER_WRITE',
    category: 'PROTOCOLS',
    name: 'I2C Write to Slave (0x48)',
    nameHu: 'I2C Adatküldés Szolgának (0x48)',
    description: 'Transmits command and payload bytes over I2C (SCL=A5, SDA=A4).',
    descriptionHu: 'Parancsot és adatbájtokat küld I2C buszon keresztül a szolga eszköznek.',
    color: 'border-cyan-500/60 bg-cyan-950/30 text-cyan-300',
    accentColor: '#06B6D4',
    iconName: 'Network',
    defaultParams: { slaveAddr: '0x48', cmdByte: '0x01', dataVal: 'servoTarget' },
    paramSchema: [
      {
        key: 'slaveAddr',
        label: '7-bit Slave Address',
        labelHu: '7-bites Szolga Cím',
        type: 'text',
      },
      {
        key: 'cmdByte',
        label: 'Command Header',
        labelHu: 'Parancs Fejléc',
        type: 'text',
      },
      {
        key: 'dataVal',
        label: 'Data Payload',
        labelHu: 'Adattartalom (Változó/Érték)',
        type: 'text',
      },
    ],
  },
  {
    id: 'uart_send_cmd',
    type: 'UART_SEND_CMD',
    category: 'PROTOCOLS',
    name: 'UART Send Formatted String ($CMD)',
    nameHu: 'UART Soros Parancs Küldése ($CMD)',
    description: 'Prints structured ASCII packet like $CMD,SERVO,90*AA over TX line.',
    descriptionHu: 'Strukturált ASCII parancssort küld a TX vonalon keresztül.',
    color: 'border-cyan-500/60 bg-cyan-950/30 text-cyan-300',
    accentColor: '#06B6D4',
    iconName: 'Terminal',
    defaultParams: { cmdName: 'SERVO', paramVal: 'angle' },
    paramSchema: [
      {
        key: 'cmdName',
        label: 'Command Key',
        labelHu: 'Parancs Kulcsszó',
        type: 'select',
        options: [
          { label: 'SERVO (Kormány/Pozíció)', labelHu: 'SERVO (Kormány/Pozíció)', value: 'SERVO' },
          { label: 'LED (Világítás ki/be)', labelHu: 'LED (Világítás ki/be)', value: 'LED' },
          { label: 'RELAY (Relé vezérlés)', labelHu: 'RELAY (Relé vezérlés)', value: 'RELAY' },
          { label: 'GET_TELEMETRY', labelHu: 'GET_TELEMETRY', value: 'GET_TELEMETRY' },
        ],
      },
      {
        key: 'paramVal',
        label: 'Argument Value',
        labelHu: 'Paraméter Érték',
        type: 'text',
      },
    ],
  },

  // ==================== 4. ACTUATORS & OUTPUTS ====================
  {
    id: 'servo_write',
    type: 'SERVO_WRITE',
    category: 'ACTUATORS',
    name: 'Set Servo Motor Angle (0..180°)',
    nameHu: 'Szervómotor Pozíció (0..180°)',
    description: 'Outputs PWM pulse on D9 to position standard servo.',
    descriptionHu: 'D9-es PWM lábon szögbe állítja a szervómotort (0..180 fok).',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Compass',
    defaultParams: { pin: '9', angle: '90' },
    paramSchema: [
      {
        key: 'pin',
        label: 'PWM Pin',
        labelHu: 'PWM Láb',
        type: 'select',
        options: [
          { label: 'D9 (Servo Out)', labelHu: 'D9 (Szervó Kimenet)', value: '9' },
          { label: 'D10 (Servo 2)', labelHu: 'D10 (2. Szervó)', value: '10' },
        ],
      },
      {
        key: 'angle',
        label: 'Angle (0..180° or variable)',
        labelHu: 'Szög (0..180° vagy változó)',
        type: 'text',
      },
    ],
  },
  {
    id: 'rgb_set_color',
    type: 'RGB_SET_COLOR',
    category: 'ACTUATORS',
    name: 'Set RGB LED Color (PWM)',
    nameHu: 'RGB LED Szín Beállítása (PWM)',
    description: 'Drives R, G, B analog channels with 0..255 brightness.',
    descriptionHu: 'Beállítja az RGB LED piros, zöld és kék fényerejét (0..255).',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Palette',
    defaultParams: { r: '0', g: '180', b: '255' },
    paramSchema: [
      {
        key: 'r',
        label: 'Red (0..255)',
        labelHu: 'Piros (0..255)',
        type: 'number',
        min: 0,
        max: 255,
      },
      {
        key: 'g',
        label: 'Green (0..255)',
        labelHu: 'Zöld (0..255)',
        type: 'number',
        min: 0,
        max: 255,
      },
      {
        key: 'b',
        label: 'Blue (0..255)',
        labelHu: 'Kék (0..255)',
        type: 'number',
        min: 0,
        max: 255,
      },
    ],
  },
  {
    id: 'oled_print_line',
    type: 'OLED_PRINT_LINE',
    category: 'ACTUATORS',
    name: 'Print Line on OLED Display (SSD1306)',
    nameHu: 'Szöveg Kiírása OLED Kijelzőre',
    description: 'Renders text line on the 128x64 I2C graphic OLED screen.',
    descriptionHu: 'Soronkénti szöveg vagy telemetria kiírása a virtuális OLED kijelzőre.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Tv',
    defaultParams: { lineIndex: '0', textContent: 'SYSTEM ACTIVE' },
    paramSchema: [
      {
        key: 'lineIndex',
        label: 'Line Number (0..3)',
        labelHu: 'Sor Száma (0..3)',
        type: 'select',
        options: [
          { label: 'Line 0 (Fejléc)', labelHu: '0. Sor (Fejléc)', value: '0' },
          { label: 'Line 1 (Fő Adat)', labelHu: '1. Sor (Fő Adat)', value: '1' },
          { label: 'Line 2 (Telemetria)', labelHu: '2. Sor (Telemetria)', value: '2' },
          { label: 'Line 3 (Állapot)', labelHu: '3. Sor (Állapot)', value: '3' },
        ],
      },
      {
        key: 'textContent',
        label: 'Text or Expression',
        labelHu: 'Szöveg / Kifejezés',
        type: 'text',
      },
    ],
  },
  {
    id: 'relay_toggle',
    type: 'RELAY_TOGGLE',
    category: 'ACTUATORS',
    name: 'Switch Industrial Relay (ON/OFF)',
    nameHu: 'Ipari Relé Kapcsolása (BE/KI)',
    description: 'Switches high-power relay coil via transistor driver pin.',
    descriptionHu: 'Nagyfeszültségű vagy nagyáramú áramkör relés kapcsolása.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Power',
    defaultParams: { pin: '8', state: 'HIGH' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Relay Pin',
        labelHu: 'Relé Láb',
        type: 'select',
        options: [{ label: 'D8 (Relay 1)', labelHu: 'D8 (1. Relé)', value: '8' }],
      },
      {
        key: 'state',
        label: 'Relay State',
        labelHu: 'Relé Állapota',
        type: 'select',
        options: [
          { label: 'ON / Closed (Bekapcsolva)', labelHu: 'ON / Zárva (Bekapcsolva)', value: 'HIGH' },
          { label: 'OFF / Open (Kikapcsolva)', labelHu: 'OFF / Nyitva (Kikapcsolva)', value: 'LOW' },
        ],
      },
    ],
  },
  {
    id: 'buzzer_tone',
    type: 'BUZZER_TONE',
    category: 'ACTUATORS',
    name: 'Play Buzzer Tone (Frequency Hz)',
    nameHu: 'Hangjelzés / Csipogó (Frekvencia Hz)',
    description: 'Generates square wave audio tone on passive piezo buzzer.',
    descriptionHu: 'Hangfrekvenciás négyszögjelet generál a piezo hangszórón.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Volume2',
    defaultParams: { pin: '4', freqHz: '440', durationMs: '200' },
    paramSchema: [
      {
        key: 'pin',
        label: 'Buzzer Pin',
        labelHu: 'Csipogó Láb',
        type: 'select',
        options: [{ label: 'D4 (Piezo Buzzer)', labelHu: 'D4 (Piezo Hangszóró)', value: '4' }],
      },
      {
        key: 'freqHz',
        label: 'Tone Frequency (Hz)',
        labelHu: 'Frekvencia (Hz)',
        type: 'number',
        min: 100,
        max: 5000,
        step: 50,
      },
      {
        key: 'durationMs',
        label: 'Duration (ms)',
        labelHu: 'Hossz (ms)',
        type: 'number',
        min: 10,
        max: 2000,
        step: 50,
      },
    ],
  },

  // ==================== 5. VARIABLES (RAM / SRAM MEMORY) ====================
  {
    id: 'var_declare',
    type: 'VAR_DECLARE',
    category: 'VARIABLES',
    name: 'Declare Variable (Type & Name)',
    nameHu: 'Változó Deklarálása (Típus & Név)',
    description: 'Allocates memory in SRAM for a variable with initial value.',
    descriptionHu: 'Memóriát foglal az SRAM-ban a megadott típusnak (int, byte, float, bool) megfelelő méretben.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Variable',
    defaultParams: {
      dataType: 'int',
      varName: 'sensorValue',
      initValue: '0',
      scope: 'global',
    },
    paramSchema: [
      {
        key: 'dataType',
        label: 'Data Type (Size in RAM)',
        labelHu: 'Adattípus (SRAM Méret)',
        type: 'select',
        options: [
          { label: 'byte / uint8_t (1 Byte: 0..255)', labelHu: 'byte / uint8_t (1 Bájt: 0..255)', value: 'byte' },
          { label: 'int (2 Bytes: -32768..32767)', labelHu: 'int (2 Bájt: -32768..32767)', value: 'int' },
          { label: 'float (4 Bytes: IEEE 754)', labelHu: 'float (4 Bájt: Lebegőpontos)', value: 'float' },
          { label: 'bool (1 Byte: true/false)', labelHu: 'bool (1 Bájt: Igaz/Hamis)', value: 'bool' },
          { label: 'char (1 Byte: ASCII)', labelHu: 'char (1 Bájt: ASCII Karakter)', value: 'char' },
          { label: 'long (4 Bytes: 32-bit)', labelHu: 'long (4 Bájt: 32-bites egész)', value: 'long' },
        ],
      },
      {
        key: 'varName',
        label: 'Variable Name',
        labelHu: 'Változó Neve',
        type: 'text',
      },
      {
        key: 'initValue',
        label: 'Initial Value',
        labelHu: 'Kezdőérték',
        type: 'text',
      },
      {
        key: 'scope',
        label: 'Memory Scope',
        labelHu: 'Memória Terület',
        type: 'select',
        options: [
          { label: 'Global (SRAM .data/.bss section)', labelHu: 'Globális (SRAM .data/.bss)', value: 'global' },
          { label: 'Local (Stack Frame Memory)', labelHu: 'Lokális (Veremtár / Stack)', value: 'local' },
        ],
      },
    ],
  },
  {
    id: 'set_variable',
    type: 'SET_VARIABLE',
    category: 'VARIABLES',
    name: 'Set Variable Value (=, +=, -=)',
    nameHu: 'Változó Értékadás (x = érték)',
    description: 'Assigns or modifies a variable value in SRAM.',
    descriptionHu: 'Módosítja a változó értékét az SRAM memóriában (értékadás, hozzáadás, kivonás).',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Variable',
    defaultParams: {
      varName: 'sensorValue',
      operator: '=',
      expression: 'analogRead(A0)',
    },
    paramSchema: [
      {
        key: 'varName',
        label: 'Variable Name',
        labelHu: 'Változó Neve',
        type: 'text',
      },
      {
        key: 'operator',
        label: 'Operation',
        labelHu: 'Művelet',
        type: 'select',
        options: [
          { label: '= Assign value', labelHu: '= Értékadás', value: '=' },
          { label: '+= Add to variable', labelHu: '+= Hozzáadás (akkumulálás)', value: '+=' },
          { label: '-= Subtract', labelHu: '-= Kivonás', value: '-=' },
          { label: '*= Multiply', labelHu: '*= Szorzás', value: '*=' },
          { label: '/= Divide', labelHu: '/= Osztás', value: '/=' },
        ],
      },
      {
        key: 'expression',
        label: 'Value / Expression',
        labelHu: 'Érték vagy Kifejezés',
        type: 'text',
      },
    ],
  },
  {
    id: 'var_inc_dec',
    type: 'VAR_INC_DEC',
    category: 'VARIABLES',
    name: 'Increment / Decrement Variable (++ / --)',
    nameHu: 'Változó Növelése / Csökkentése (++ / --)',
    description: 'Adds 1 or subtracts 1 from a variable in memory.',
    descriptionHu: 'Eggyel növeli (++) vagy csökkenti (--) a memóriában lévő változót.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Sliders',
    defaultParams: { varName: 'counter', op: '++' },
    paramSchema: [
      {
        key: 'varName',
        label: 'Variable Name',
        labelHu: 'Változó Neve',
        type: 'text',
      },
      {
        key: 'op',
        label: 'Action',
        labelHu: 'Művelet',
        type: 'select',
        options: [
          { label: '++ Increment (+1)', labelHu: '++ Növelés (+1)', value: '++' },
          { label: '-- Decrement (-1)', labelHu: '-- Csökkentés (-1)', value: '--' },
        ],
      },
    ],
  },

  // ==================== 6. ARRAYS (CONTIGUOUS MEMORY BUFFERS) ====================
  {
    id: 'array_declare',
    type: 'ARRAY_DECLARE',
    category: 'ARRAYS',
    name: 'Declare Array Buffer (SRAM / PROGMEM)',
    nameHu: 'Tömb Létrehozása (Folytonos Memória Puffer)',
    description: 'Allocates contiguous memory cells in SRAM or Flash PROGMEM.',
    descriptionHu: 'Folytonos memóriaterületet foglal le a tömb elemeinek (címképzés: Alapcím + index * elemméret).',
    color: 'border-teal-500/60 bg-teal-950/30 text-teal-300',
    accentColor: '#14B8A6',
    iconName: 'Layers',
    defaultParams: {
      arrayName: 'readings',
      dataType: 'int',
      size: 8,
      initValues: '0, 0, 0, 0, 0, 0, 0, 0',
      location: 'SRAM',
    },
    paramSchema: [
      {
        key: 'arrayName',
        label: 'Array Name',
        labelHu: 'Tömb Neve',
        type: 'text',
      },
      {
        key: 'dataType',
        label: 'Element Type (Bytes/Element)',
        labelHu: 'Elemtípus (Bájt / Elem)',
        type: 'select',
        options: [
          { label: 'byte (1 Byte per cell)', labelHu: 'byte (1 Bájt cellánként)', value: 'byte' },
          { label: 'int (2 Bytes per cell)', labelHu: 'int (2 Bájt cellánként)', value: 'int' },
          { label: 'float (4 Bytes per cell)', labelHu: 'float (4 Bájt cellánként)', value: 'float' },
          { label: 'char (1 Byte ASCII)', labelHu: 'char (1 Bájt ASCII)', value: 'char' },
        ],
      },
      {
        key: 'size',
        label: 'Number of Elements (Length)',
        labelHu: 'Elemek Száma (Kapacitás)',
        type: 'number',
        min: 2,
        max: 64,
        step: 1,
      },
      {
        key: 'initValues',
        label: 'Initial Values (comma-separated)',
        labelHu: 'Kezdőértékek (vesszővel elválasztva)',
        type: 'text',
      },
      {
        key: 'location',
        label: 'Memory Placement',
        labelHu: 'Memória Helye',
        type: 'select',
        options: [
          { label: 'SRAM (Read/Write Data RAM)', labelHu: 'SRAM (Írható/Olvasható Memória)', value: 'SRAM' },
          { label: 'PROGMEM (Flash ROM Constant Table)', labelHu: 'PROGMEM (Flash ROM Konstans Tábla)', value: 'PROGMEM' },
        ],
      },
    ],
  },
  {
    id: 'array_set_element',
    type: 'ARRAY_SET_ELEMENT',
    category: 'ARRAYS',
    name: 'Write to Array Element (arr[index] = val)',
    nameHu: 'Tömbelem Írása (arr[index] = érték)',
    description: 'Writes value to a specific cell index: *(arr + index * sizeof(T)).',
    descriptionHu: 'Adott indexű cellába ír értéket. Mutató aritmetika: Alapcím + (index * elem_méret).',
    color: 'border-teal-500/60 bg-teal-950/30 text-teal-300',
    accentColor: '#14B8A6',
    iconName: 'Database',
    defaultParams: {
      arrayName: 'readings',
      index: '0',
      value: 'analogRead(A0)',
    },
    paramSchema: [
      {
        key: 'arrayName',
        label: 'Array Name',
        labelHu: 'Tömb Neve',
        type: 'text',
      },
      {
        key: 'index',
        label: 'Index (0 .. Size-1)',
        labelHu: 'Index (0 .. Hossz-1)',
        type: 'text',
      },
      {
        key: 'value',
        label: 'New Value / Expression',
        labelHu: 'Új Érték / Kifejezés',
        type: 'text',
      },
    ],
  },
  {
    id: 'array_get_element',
    type: 'ARRAY_GET_ELEMENT',
    category: 'ARRAYS',
    name: 'Read Array Element (var = arr[index])',
    nameHu: 'Tömbelem Olvasása (var = arr[index])',
    description: 'Fetches element at index and stores in a variable or sends to output.',
    descriptionHu: 'Kiolvassa az adott indexű memóriacímen tárolt értéket egy célváltozóba.',
    color: 'border-teal-500/60 bg-teal-950/30 text-teal-300',
    accentColor: '#14B8A6',
    iconName: 'Download',
    defaultParams: {
      targetVar: 'currentVal',
      arrayName: 'readings',
      index: '0',
    },
    paramSchema: [
      {
        key: 'targetVar',
        label: 'Target Variable',
        labelHu: 'Cél Változó',
        type: 'text',
      },
      {
        key: 'arrayName',
        label: 'Source Array',
        labelHu: 'Forrás Tömb',
        type: 'text',
      },
      {
        key: 'index',
        label: 'Index (0 .. Size-1)',
        labelHu: 'Index (0 .. Hossz-1)',
        type: 'text',
      },
    ],
  },
  {
    id: 'array_for_loop',
    type: 'ARRAY_FOR_LOOP',
    category: 'ARRAYS',
    name: 'For Loop Iterate Over Array (0..Size)',
    nameHu: 'Tömb Bejárása Ciklussal (For ciklus)',
    description: 'Loops through array indices 0 to (Size - 1) stepping through memory.',
    descriptionHu: 'Végigiterál a tömb összes memóriarekeszén 0-tól N-1-ig, egymás után.',
    color: 'border-teal-500/60 bg-teal-950/30 text-teal-300',
    accentColor: '#14B8A6',
    iconName: 'RotateCcw',
    hasChildren: true,
    defaultParams: {
      indexVar: 'i',
      arrayName: 'readings',
      limitCount: '8',
    },
    paramSchema: [
      {
        key: 'indexVar',
        label: 'Loop Index Variable',
        labelHu: 'Ciklusváltozó Neve',
        type: 'text',
      },
      {
        key: 'arrayName',
        label: 'Target Array',
        labelHu: 'Cél Tömb',
        type: 'text',
      },
      {
        key: 'limitCount',
        label: 'Number of Iterations',
        labelHu: 'Iterációk Száma',
        type: 'number',
        min: 1,
        max: 64,
      },
    ],
  },
  {
    id: 'array_rolling_avg',
    type: 'ARRAY_ROLLING_AVG',
    category: 'ARRAYS',
    name: 'Rolling Average Filter (Circular Buffer DSP)',
    nameHu: 'Futóátlag Szűrő (Körkörös Puffer DSP)',
    description: 'Inserts new sample, shifts circular index, and computes smoothed average.',
    descriptionHu: 'Új mintát szúr be a memóriapufferbe és kiszámítja a zajmentesített átlagot.',
    color: 'border-teal-500/60 bg-teal-950/30 text-teal-300',
    accentColor: '#14B8A6',
    iconName: 'Sparkles',
    defaultParams: {
      arrayName: 'readings',
      size: 8,
      newSampleExpr: 'analogRead(A0)',
      resultVar: 'smoothedAverage',
    },
    paramSchema: [
      {
        key: 'arrayName',
        label: 'Buffer Array',
        labelHu: 'Puffer Tömb',
        type: 'text',
      },
      {
        key: 'size',
        label: 'Buffer Size',
        labelHu: 'Puffer Méret',
        type: 'number',
        min: 2,
        max: 32,
      },
      {
        key: 'newSampleExpr',
        label: 'New Sensor Sample',
        labelHu: 'Új Szenzor Minta',
        type: 'text',
      },
      {
        key: 'resultVar',
        label: 'Smoothed Average Variable',
        labelHu: 'Simított Átlag Változó',
        type: 'text',
      },
    ],
  },

  // ==================== 7. LOGIC & MATH ====================
  {
    id: 'map_range',
    type: 'MAP_RANGE',
    category: 'LOGIC',
    name: 'Map Value Range (map)',
    nameHu: 'Értéktartomány Skálázás (map)',
    description: 'Scales a number from one range to another (e.g. 0..1023 to 0..180°).',
    descriptionHu: 'Átskáláz egy számot az egyik értéktartományból a másikba.',
    color: 'border-emerald-500/60 bg-emerald-950/30 text-emerald-300',
    accentColor: '#10B981',
    iconName: 'Sliders',
    defaultParams: {
      targetVar: 'servoTarget',
      sourceVal: 'analogRead(A0)',
      inMin: '0',
      inMax: '1023',
      outMin: '0',
      outMax: '180',
    },
    paramSchema: [
      {
        key: 'targetVar',
        label: 'Result Variable',
        labelHu: 'Eredmény Változó',
        type: 'text',
      },
      {
        key: 'sourceVal',
        label: 'Source Value',
        labelHu: 'Forrás Érték',
        type: 'text',
      },
      {
        key: 'outMin',
        label: 'Output Min',
        labelHu: 'Kimenet Min',
        type: 'number',
      },
      {
        key: 'outMax',
        label: 'Output Max',
        labelHu: 'Kimenet Max',
        type: 'number',
      },
    ],
  },

  // ==================== 8. 74HC595 SHIFT REGISTER ====================
  {
    id: 'shift595_config',
    type: 'SHIFT595_CONFIG',
    category: 'SHIFT_REGISTER',
    name: '74HC595 Setup Pins (DS, SH_CP, ST_CP)',
    nameHu: '74HC595 Lábak Beállítása (Adat, Órajel, Retesz)',
    description: 'Initializes MCU GPIO pins connected to 74HC595 Data (Pin 14), Clock (Pin 11), and Latch (Pin 12).',
    descriptionHu: 'Beállítja a mikrokontroller kimeneti lábait a 74HC595 Adat (DS), Órajel (SH_CP) és Retesz (ST_CP) vonalaihoz.',
    color: 'border-cyan-500/60 bg-cyan-950/30 text-cyan-300',
    accentColor: '#06B6D4',
    iconName: 'Cpu',
    defaultParams: { dataPin: '4', clockPin: '2', latchPin: '3' },
    paramSchema: [
      {
        key: 'dataPin',
        label: 'Data Pin (DS - Pin 14)',
        labelHu: 'Adat Láb (DS - Pin 14)',
        type: 'select',
        options: [
          { label: 'D4', labelHu: 'D4', value: '4' },
          { label: 'D8', labelHu: 'D8', value: '8' },
          { label: 'D11 (MOSI)', labelHu: 'D11 (MOSI)', value: '11' },
          { label: 'D12', labelHu: 'D12', value: '12' },
        ],
      },
      {
        key: 'clockPin',
        label: 'Clock Pin (SH_CP - Pin 11)',
        labelHu: 'Órajel Láb (SH_CP - Pin 11)',
        type: 'select',
        options: [
          { label: 'D2', labelHu: 'D2', value: '2' },
          { label: 'D7', labelHu: 'D7', value: '7' },
          { label: 'D13 (SCK)', labelHu: 'D13 (SCK)', value: '13' },
        ],
      },
      {
        key: 'latchPin',
        label: 'Latch Pin (ST_CP - Pin 12)',
        labelHu: 'Retesz Láb (ST_CP - Pin 12)',
        type: 'select',
        options: [
          { label: 'D3', labelHu: 'D3', value: '3' },
          { label: 'D9', labelHu: 'D9', value: '9' },
          { label: 'D10 (SS)', labelHu: 'D10 (SS)', value: '10' },
        ],
      },
    ],
  },
  {
    id: 'shift595_write_byte',
    type: 'SHIFT595_WRITE_BYTE',
    category: 'SHIFT_REGISTER',
    name: '74HC595 Write Byte (Auto Latch)',
    nameHu: '74HC595 Bájt Kiírása (Automatikus Reteszeléssel)',
    description: 'Pulls Latch LOW, shifts out 8 bits to 74HC595, and pulses Latch HIGH to update outputs.',
    descriptionHu: 'Alacsonyba húzza a reteszt, kiléptet 8 bitet a regiszterbe, majd magasba billenti a reteszt a kimenetek frissítéséhez.',
    color: 'border-cyan-500/60 bg-cyan-950/30 text-cyan-300',
    accentColor: '#06B6D4',
    iconName: 'FastForward',
    defaultParams: { valueExpr: '0b10101010', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
    paramSchema: [
      {
        key: 'valueExpr',
        label: 'Byte Value (0..255, 0xAA, 0b10101010)',
        labelHu: 'Bájt Érték (0..255 vagy változó)',
        type: 'text',
      },
      {
        key: 'bitOrder',
        label: 'Bit Order',
        labelHu: 'Bit Sorrend',
        type: 'select',
        options: [
          { label: 'MSBFIRST (Most Significant First)', labelHu: 'MSBFIRST (Legmagasabb bit először)', value: 'MSBFIRST' },
          { label: 'LSBFIRST (Least Significant First)', labelHu: 'LSBFIRST (Legalacsonyabb bit először)', value: 'LSBFIRST' },
        ],
      },
      {
        key: 'dataPin',
        label: 'Data Pin',
        labelHu: 'Adat Láb (DS)',
        type: 'select',
        options: [
          { label: 'D4', labelHu: 'D4', value: '4' },
          { label: 'D8', labelHu: 'D8', value: '8' },
        ],
      },
      {
        key: 'clockPin',
        label: 'Clock Pin',
        labelHu: 'Órajel Láb (SH_CP)',
        type: 'select',
        options: [
          { label: 'D2', labelHu: 'D2', value: '2' },
          { label: 'D7', labelHu: 'D7', value: '7' },
        ],
      },
      {
        key: 'latchPin',
        label: 'Latch Pin',
        labelHu: 'Retesz Láb (ST_CP)',
        type: 'select',
        options: [
          { label: 'D3', labelHu: 'D3', value: '3' },
          { label: 'D9', labelHu: 'D9', value: '9' },
        ],
      },
    ],
  },
  {
    id: 'shift595_cascade_16bit',
    type: 'SHIFT595_CASCADE_16BIT',
    category: 'SHIFT_REGISTER',
    name: '74HC595 Cascaded 16-Bit Write (2x Chips)',
    nameHu: '2x 74HC595 Kaszkádolt 16-Bites Kiírás (QH\' Láncolás)',
    description: 'Writes 16 bits to two daisy-chained 74HC595 registers through QH\' with a single latch pulse.',
    descriptionHu: '16 bitet léptet ki két kaszkádolt 74HC595 IC-be a QH\' vonalon keresztül, egyetlen retesz impulzussal.',
    color: 'border-purple-500/60 bg-purple-950/30 text-purple-300',
    accentColor: '#A855F7',
    iconName: 'Layers',
    defaultParams: { highByteExpr: '0xAA', lowByteExpr: '0x55', dataPin: '4', clockPin: '2', latchPin: '3' },
    paramSchema: [
      {
        key: 'highByteExpr',
        label: 'High Byte (Chip 2 Outputs)',
        labelHu: 'Felső Bájt (2. IC kimenetei)',
        type: 'text',
      },
      {
        key: 'lowByteExpr',
        label: 'Low Byte (Chip 1 Outputs)',
        labelHu: 'Alsó Bájt (1. IC kimenetei)',
        type: 'text',
      },
    ],
  },
  {
    id: 'shift595_sevenseg_digit',
    type: 'SHIFT595_SEVENSEG_DIGIT',
    category: 'SHIFT_REGISTER',
    name: '74HC595 7-Segment Digit Output',
    nameHu: '74HC595 7-Szegmenses Számkijelzés',
    description: 'Encodes and outputs a decimal number (0..9) or hex character (A..F) to a 7-segment display on 74HC595.',
    descriptionHu: 'Számot (0..9) vagy hexadecimális karaktert jelenít meg a 74HC595-re kötött 7-szegmenses kijelzőn.',
    color: 'border-rose-500/60 bg-rose-950/30 text-rose-300',
    accentColor: '#F43F5E',
    iconName: 'Sparkles',
    defaultParams: { digitExpr: 'counter % 10', dataPin: '4', clockPin: '2', latchPin: '3' },
    paramSchema: [
      {
        key: 'digitExpr',
        label: 'Digit Expression (0..9 / var)',
        labelHu: 'Megjelenítendő Számjegy (0..9 / változó)',
        type: 'text',
      },
    ],
  },
  {
    id: 'shift595_oe_pwm',
    type: 'SHIFT595_OE_PWM',
    category: 'SHIFT_REGISTER',
    name: '74HC595 Output Enable PWM Dimming (/OE)',
    nameHu: '74HC595 Fényerőszabályzás PWM-mel (/OE Láb)',
    description: 'Modulates brightness of all 74HC595 outputs by applying analogWrite PWM to the active-LOW /OE pin.',
    descriptionHu: 'Szabályozza az összes kimenet fényerejét a 13-as (/OE) lábra küldött PWM jellel.',
    color: 'border-amber-500/60 bg-amber-950/30 text-amber-300',
    accentColor: '#F59E0B',
    iconName: 'Gauge',
    defaultParams: { oePin: '5', brightness: '128' },
    paramSchema: [
      {
        key: 'oePin',
        label: 'PWM Pin for /OE (Pin 13)',
        labelHu: 'PWM Láb az /OE-hez (Pin 13)',
        type: 'select',
        options: [
          { label: 'D5 (Timer0 PWM)', labelHu: 'D5 (Timer0 PWM)', value: '5' },
          { label: 'D6 (Timer0 PWM)', labelHu: 'D6 (Timer0 PWM)', value: '6' },
          { label: 'D9 (Timer1 PWM)', labelHu: 'D9 (Timer1 PWM)', value: '9' },
        ],
      },
      {
        key: 'brightness',
        label: 'Brightness Level (0=Off, 255=Max)',
        labelHu: 'Fényerősség (0=Kikapcsolva, 255=Max)',
        type: 'text',
      },
    ],
  },
];
