import { BlockProgramPreset } from '../types/mcuBlock';

export const BLOCK_PRESETS: BlockProgramPreset[] = [
  {
    id: 'preset_shift595_cylon',
    title: '74HC595 8-LED Knight Rider / Cylon Scanner',
    titleHu: '74HC595 8-LED Knight Rider / Cylon Futófény',
    category: 'Shift Register',
    categoryHu: 'Shift-Regiszter 74HC595',
    description: 'Initializes 74HC595 pins and runs a smooth back-and-forth light scanner on 8 LEDs.',
    descriptionHu: 'Inicializálja a 74HC595 lábakat és oda-vissza pásztázó futófényt hajt végre a 8 LED kimeneten.',
    targetMcu: 'BREADBOARD',
    blocks: [
      {
        instanceId: 'b-595-cfg',
        blockType: 'SHIFT595_CONFIG',
        params: { dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-step-1',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x01', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-1',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
      {
        instanceId: 'b-595-step-2',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x02', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-2',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
      {
        instanceId: 'b-595-step-3',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x04', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-3',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
      {
        instanceId: 'b-595-step-4',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x08', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-4',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
      {
        instanceId: 'b-595-step-5',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x10', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-5',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
      {
        instanceId: 'b-595-step-6',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x20', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-6',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
      {
        instanceId: 'b-595-step-7',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x40', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-7',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
      {
        instanceId: 'b-595-step-8',
        blockType: 'SHIFT595_WRITE_BYTE',
        params: { valueExpr: '0x80', bitOrder: 'MSBFIRST', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-d-8',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
    ],
  },
  {
    id: 'preset_shift595_sevenseg',
    title: '74HC595 7-Segment Display Number Counter',
    titleHu: '74HC595 7-Szegmenses Számkijelző Számláló (0-9)',
    category: 'Shift Register',
    categoryHu: 'Shift-Regiszter 74HC595',
    description: 'Decodes digits 0 to 9 to segment bits and displays them via 74HC595 shift register.',
    descriptionHu: '0-tól 9-ig dekódolja a számjegyeket és megjeleníti a 74HC595-re kötött 7-szegmenses kijelzőn.',
    targetMcu: 'BREADBOARD',
    blocks: [
      {
        instanceId: 'b-595-cfg-seg',
        blockType: 'SHIFT595_CONFIG',
        params: { dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-seg-digit',
        blockType: 'SHIFT595_SEVENSEG_DIGIT',
        params: { digitExpr: 'millis() / 500 % 10', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-seg-delay',
        blockType: 'DELAY_MS',
        params: { ms: 200 },
      },
    ],
  },
  {
    id: 'preset_shift595_cascade16',
    title: 'Dual 74HC595 Cascaded 16-Bit Output Controller',
    titleHu: '2x 74HC595 Kaszkádolt 16-Bites Kimenet Vezérlő (QH\')',
    category: 'Shift Register',
    categoryHu: 'Shift-Regiszter 74HC595',
    description: 'Sends 16 bits through two chained 74HC595 ICs using only 3 microcontroller pins.',
    descriptionHu: '16 bitet továbbít két láncolt 74HC595-ön keresztül, mindössze 3 mikrokontroller lábbal.',
    targetMcu: 'BREADBOARD',
    blocks: [
      {
        instanceId: 'b-595-cfg-casc',
        blockType: 'SHIFT595_CONFIG',
        params: { dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-casc-1',
        blockType: 'SHIFT595_CASCADE_16BIT',
        params: { highByteExpr: '0xFF', lowByteExpr: '0x00', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-casc-d1',
        blockType: 'DELAY_MS',
        params: { ms: 400 },
      },
      {
        instanceId: 'b-595-casc-2',
        blockType: 'SHIFT595_CASCADE_16BIT',
        params: { highByteExpr: '0x00', lowByteExpr: '0xFF', dataPin: '4', clockPin: '2', latchPin: '3' },
      },
      {
        instanceId: 'b-595-casc-d2',
        blockType: 'DELAY_MS',
        params: { ms: 400 },
      },
    ],
  },
  {
    id: 'pwm_optical_breathing_led',
    title: 'PWM Hardware Fast Timer Optical Breathing LED (Gamma 2.2)',
    titleHu: 'PWM Hardveres Időzítő Optikai Lélegeztető LED (Gamma 2.2)',
    category: 'PWM & Timers',
    categoryHu: 'PWM & Időzítők',
    description: 'Configures Timer0 for 62.5kHz Fast PWM and generates an eye-pleasing optical breathing light curve.',
    descriptionHu: 'Beállítja a Timer0 regisztereket nagyfrekvenciás Fast PWM-re és szembarát exponenciális pulzálást hajt végre.',
    targetMcu: 'BREADBOARD',
    blocks: [
      {
        instanceId: 'b-pwm-cfg-t0',
        blockType: 'PWM_CONFIG_TIMER',
        params: { timer: 'TIMER0', mode: 'FAST_PWM', prescaler: '64', pin: '6' },
      },
      {
        instanceId: 'b-pwm-breathe',
        blockType: 'PWM_FADE_BREATHE',
        params: { pin: '6', stepDelayMs: '8', maxDuty: '255' },
      },
    ],
  },
  {
    id: 'pwm_hbridge_motor_servo_ctrl',
    title: 'PWM H-Bridge DC Motor & Precision Servo Positioner',
    titleHu: 'PWM H-Híd DC Motor & Precíziós Szervó Vezérlő',
    category: 'Actuators',
    categoryHu: 'Aktuátorok & PWM',
    description: 'Reads potentiometer on A0, maps to DC Motor PWM speed (D5) and sweeps Servo angle on D9.',
    descriptionHu: 'Potmétert olvas az A0-ról, kiszámolja a motor sebességét a D5 lábon, és a D9 szervó szögét.',
    targetMcu: 'MCU_A',
    blocks: [
      {
        instanceId: 'b-pwm-cfg-t1',
        blockType: 'PWM_CONFIG_TIMER',
        params: { timer: 'TIMER1', mode: 'FAST_PWM', prescaler: '64', pin: '9' },
      },
      {
        instanceId: 'b-read-pot-speed',
        blockType: 'ANALOG_READ_VAR',
        params: { pin: 'A0', varName: 'potSpeed' },
      },
      {
        instanceId: 'b-map-motor-pwm',
        blockType: 'MAP_RANGE',
        params: {
          targetVar: 'motorPwm',
          sourceVal: 'potSpeed',
          inMin: '0',
          inMax: '1023',
          outMin: '0',
          outMax: '255',
        },
      },
      {
        instanceId: 'b-drive-motor',
        blockType: 'PWM_MOTOR_HBRIDGE',
        params: {
          pwmPin: '5',
          dirPinA: '7',
          dirPinB: '8',
          speedVal: 'motorPwm',
          direction: 'FORWARD',
        },
      },
      {
        instanceId: 'b-set-servo',
        blockType: 'PWM_SERVO_ANGLE',
        params: { pin: '9', angleVal: '90' },
      },
      {
        instanceId: 'b-pwm-delay',
        blockType: 'DELAY_MS',
        params: { ms: 50 },
      },
    ],
  },
  {
    id: 'adc_precision_voltmeter_block',
    title: '10-bit Hardware ADC Precision Voltmeter & PWM LED Dimmer',
    titleHu: '10-bites Hardveres ADC Volt-Mérő & PWM LED Szabályzó',
    category: 'Sensors',
    categoryHu: 'Szenzorok & ADC',
    description: 'Configures 10-bit SAR ADC registers, reads A0 voltage in Volts, and maps to hardware PWM pin D3.',
    descriptionHu: 'Beállítja az ADC regisztereket, lebegőpontos feszültséget számol az A0-ról, és PWM kimenetre (D3) tükrözi.',
    targetMcu: 'MCU_A',
    blocks: [
      {
        instanceId: 'b-adc-cfg',
        blockType: 'ADC_CONFIG',
        params: { reference: 'DEFAULT', prescaler: '128', adlar: 'RIGHT' },
      },
      {
        instanceId: 'b-read-volt',
        blockType: 'ADC_READ_VOLTAGE',
        params: { pin: 'A0', vRef: 5.0, varName: 'inputVolts' },
      },
      {
        instanceId: 'b-read-pot-raw',
        blockType: 'ANALOG_READ_VAR',
        params: { pin: 'A0', varName: 'rawAdc' },
      },
      {
        instanceId: 'b-map-pwm',
        blockType: 'MAP_RANGE',
        params: {
          targetVar: 'pwmDuty',
          sourceVal: 'rawAdc',
          inMin: '0',
          inMax: '1023',
          outMin: '0',
          outMax: '255',
        },
      },
      {
        instanceId: 'b-delay-100',
        blockType: 'DELAY_MS',
        params: { ms: 50 },
      },
    ],
  },
  {
    id: 'adc_oversampled_filter_block',
    title: 'ADC 16x Oversampling Moving Average Filter (Noise Suppression)',
    titleHu: 'ADC 16x Túlmintavételező Átlagoló Zajszűrő',
    category: 'Sensors',
    categoryHu: 'Szenzorok & ADC',
    description: 'Performs 16 successive SAR ADC bursts to eliminate analog thermal noise and increase effective ENOB.',
    descriptionHu: '16 egymást követő SAR átalakítást végez és átlagol a termikus analóg zajok kiszűrésére.',
    targetMcu: 'BREADBOARD',
    blocks: [
      {
        instanceId: 'b-adc-flt',
        blockType: 'ADC_OVERSAMPLE_AVERAGE',
        params: { pin: 'A0', samples: '16', targetVar: 'smoothReading' },
      },
      {
        instanceId: 'b-oled-adc',
        blockType: 'OLED_PRINT_LINE',
        params: { lineIndex: '0', textContent: 'ADC FILTERED: OK' },
      },
      {
        instanceId: 'b-delay-80',
        blockType: 'DELAY_MS',
        params: { ms: 80 },
      },
    ],
  },
  {
    id: 'nrf24_transmitter_block',
    title: 'nRF24 2.4GHz Wireless Transmitter (Remote Joystick)',
    titleHu: 'nRF24 2.4GHz Vezeték Nélküli Távirányító (Adó)',
    category: 'Wireless',
    categoryHu: 'Vezeték nélküli',
    description: 'Reads Joystick X (A0) and button (D2), packages telemetry, and broadcasts to MCU B.',
    descriptionHu: 'Beolvassa a Joystick X (A0) és a nyomógomb (D2) állapotát, majd elküldi az MCU B-nek.',
    targetMcu: 'MCU_A',
    blocks: [
      {
        instanceId: 'b-init-rf',
        blockType: 'NRF24_INIT',
        params: { channel: 76, pipeAddress: 'NODE1', role: 'TX' },
      },
      {
        instanceId: 'b-read-joy',
        blockType: 'ANALOG_READ_VAR',
        params: { pin: 'A0', varName: 'joyX' },
      },
      {
        instanceId: 'b-map-joy',
        blockType: 'MAP_RANGE',
        params: {
          targetVar: 'servoTarget',
          sourceVal: 'joyX',
          inMin: '0',
          inMax: '1023',
          outMin: '0',
          outMax: '180',
        },
      },
      {
        instanceId: 'b-rf-send',
        blockType: 'NRF24_SEND_PACKET',
        params: {
          joyXSource: 'joyX',
          throttleSource: 'servoTarget',
          btnSource: 'digitalRead(2)',
        },
      },
      {
        instanceId: 'b-delay-40',
        blockType: 'DELAY_MS',
        params: { ms: 50 },
      },
    ],
  },
  {
    id: 'nrf24_receiver_block',
    title: 'nRF24 Wireless Robot Receiver & Steering Actuator',
    titleHu: 'nRF24 Vezeték Nélküli Vevő & Kormányszervó',
    category: 'Wireless',
    categoryHu: 'Vezeték nélküli',
    description: 'Receives radio packets from MCU A, controls Servo (D9) and turns on Headlights.',
    descriptionHu: 'Fogadja a rádiócsomagokat az MCU A-tól, vezérli a D9 szervót és a lámpákat.',
    targetMcu: 'MCU_B',
    blocks: [
      {
        instanceId: 'b-init-rf-rx',
        blockType: 'NRF24_INIT',
        params: { channel: 76, pipeAddress: 'NODE1', role: 'RX' },
      },
      {
        instanceId: 'b-rx-packet',
        blockType: 'NRF24_RECEIVE_PACKET',
        params: {},
        children: [
          {
            instanceId: 'b-set-servo',
            blockType: 'SERVO_WRITE',
            params: { pin: '9', angle: 'map(rxPayload.joyX, 0, 1023, 0, 180)' },
          },
          {
            instanceId: 'b-oled-print',
            blockType: 'OLED_PRINT_LINE',
            params: { lineIndex: '0', textContent: 'NRF24 RX: PACKET OK' },
          },
        ],
      },
      {
        instanceId: 'b-delay-20',
        blockType: 'DELAY_MS',
        params: { ms: 20 },
      },
    ],
  },
  {
    id: 'i2c_telemetry_block',
    title: 'I2C Master Telemetry & Remote Actuator Command',
    titleHu: 'I2C Mester Telemetria & Távoli Vezérlés',
    category: 'Sensors',
    categoryHu: 'Szenzorok',
    description: 'Reads master potentiometer, writes angle to slave at 0x48, updates OLED display.',
    descriptionHu: 'Beolvassa a potmétert, kiküldi az I2C címre (0x48), és frissíti az OLED kijelzőt.',
    targetMcu: 'MCU_A',
    blocks: [
      {
        instanceId: 'b-i2c-pot',
        blockType: 'ANALOG_READ_VAR',
        params: { pin: 'A0', varName: 'masterPot' },
      },
      {
        instanceId: 'b-i2c-map',
        blockType: 'MAP_RANGE',
        params: {
          targetVar: 'servoTarget',
          sourceVal: 'masterPot',
          inMin: '0',
          inMax: '1023',
          outMin: '0',
          outMax: '180',
        },
      },
      {
        instanceId: 'b-i2c-tx',
        blockType: 'I2C_MASTER_WRITE',
        params: { slaveAddr: '0x48', cmdByte: '0x01', dataVal: 'servoTarget' },
      },
      {
        instanceId: 'b-oled-i2c',
        blockType: 'OLED_PRINT_LINE',
        params: { lineIndex: '0', textContent: 'I2C WR 0x48: SERVO' },
      },
      {
        instanceId: 'b-delay-80',
        blockType: 'DELAY_MS',
        params: { ms: 80 },
      },
    ],
  },
  {
    id: 'smart_relay_thermostat',
    title: 'Smart Thermostat & Automatic Relay Safety Switch',
    titleHu: 'Okos Termosztát & Automata Védelmi Relé',
    category: 'Industrial',
    categoryHu: 'Ipari',
    description: 'Monitors temperature sensor; when above threshold, turns ON relay and sounds alarm.',
    descriptionHu: 'Figyeli a hőmérőt; küszöb felett bekapcsolja a hűtőrelét és vészjelzést ad.',
    targetMcu: 'BREADBOARD',
    blocks: [
      {
        instanceId: 'b-read-temp',
        blockType: 'ANALOG_READ_VAR',
        params: { pin: 'A0', varName: 'tempRaw' },
      },
      {
        instanceId: 'b-if-hot',
        blockType: 'IF_CONDITION',
        params: { leftVal: 'tempRaw', operator: '>', rightVal: '600' },
        children: [
          {
            instanceId: 'b-relay-on',
            blockType: 'RELAY_TOGGLE',
            params: { pin: '8', state: 'HIGH' },
          },
          {
            instanceId: 'b-buzzer-alert',
            blockType: 'BUZZER_TONE',
            params: { pin: '4', freqHz: 1200, durationMs: 150 },
          },
          {
            instanceId: 'b-rgb-red',
            blockType: 'RGB_SET_COLOR',
            params: { r: 255, g: 0, b: 0 },
          },
        ],
      },
      {
        instanceId: 'b-delay-150',
        blockType: 'DELAY_MS',
        params: { ms: 150 },
      },
    ],
  },
  {
    id: 'variables_data_types_edu',
    title: 'Variables & Data Types in SRAM (Byte, Int, Float, Bool)',
    titleHu: 'Változók & Adattípusok az SRAM-ban (Oktató Bemutató)',
    category: 'Educational',
    categoryHu: 'Oktató & Memória',
    description: 'Declares variables of different byte sizes (1, 2, 4 bytes), performs increments and math.',
    descriptionHu: 'Különböző bájt méretű változók deklarálása az SRAM-ban, értékadás és inkrementálás.',
    targetMcu: 'MCU_A',
    blocks: [
      {
        instanceId: 'b-decl-byte',
        blockType: 'VAR_DECLARE',
        params: { dataType: 'byte', varName: 'statusFlags', initValue: '1', scope: 'global' },
      },
      {
        instanceId: 'b-decl-int',
        blockType: 'VAR_DECLARE',
        params: { dataType: 'int', varName: 'counter', initValue: '0', scope: 'global' },
      },
      {
        instanceId: 'b-decl-float',
        blockType: 'VAR_DECLARE',
        params: { dataType: 'float', varName: 'voltage', initValue: '3.30', scope: 'global' },
      },
      {
        instanceId: 'b-decl-bool',
        blockType: 'VAR_DECLARE',
        params: { dataType: 'bool', varName: 'isOverheat', initValue: 'false', scope: 'global' },
      },
      {
        instanceId: 'b-read-pot',
        blockType: 'ANALOG_READ_VAR',
        params: { pin: 'A0', varName: 'rawAdc' },
      },
      {
        instanceId: 'b-calc-volt',
        blockType: 'SET_VARIABLE',
        params: { varName: 'voltage', operator: '=', expression: '(rawAdc * 5.0) / 1023.0' },
      },
      {
        instanceId: 'b-inc-cnt',
        blockType: 'VAR_INC_DEC',
        params: { varName: 'counter', op: '++' },
      },
      {
        instanceId: 'b-oled-vars',
        blockType: 'OLED_PRINT_LINE',
        params: { lineIndex: '0', textContent: 'VARS IN SRAM: ACTIVE' },
      },
      {
        instanceId: 'b-delay-100',
        blockType: 'DELAY_MS',
        params: { ms: 100 },
      },
    ],
  },
  {
    id: 'array_rolling_average_edu',
    title: 'Array Buffer & Circular Rolling Average Filter (DSP)',
    titleHu: 'Szenzor Mintatömb & Futóátlag Szűrő (8x Puffer)',
    category: 'Educational',
    categoryHu: 'Oktató & Memória',
    description: 'Fills an 8-element integer array in SRAM with analog samples, calculates continuous smoothed average.',
    descriptionHu: '8 elemű egészekből álló tömböt foglal le az SRAM-ban, és valós idejű futóátlaggal szűri a zajt.',
    targetMcu: 'MCU_A',
    blocks: [
      {
        instanceId: 'b-decl-arr',
        blockType: 'ARRAY_DECLARE',
        params: {
          arrayName: 'readings',
          dataType: 'int',
          size: 8,
          initValues: '0, 0, 0, 0, 0, 0, 0, 0',
          location: 'SRAM',
        },
      },
      {
        instanceId: 'b-decl-avg',
        blockType: 'VAR_DECLARE',
        params: { dataType: 'int', varName: 'smoothAvg', initValue: '0', scope: 'global' },
      },
      {
        instanceId: 'b-roll-filter',
        blockType: 'ARRAY_ROLLING_AVG',
        params: {
          arrayName: 'readings',
          size: 8,
          newSampleExpr: 'analogRead(A0)',
          resultVar: 'smoothAvg',
        },
      },
      {
        instanceId: 'b-oled-arr-out',
        blockType: 'OLED_PRINT_LINE',
        params: { lineIndex: '1', textContent: 'AVG FILTER ACTIVE' },
      },
      {
        instanceId: 'b-delay-50',
        blockType: 'DELAY_MS',
        params: { ms: 50 },
      },
    ],
  },
  {
    id: 'array_for_loop_traversal',
    title: 'Array Traversal with For Loop & Memory Address Stepping',
    titleHu: 'Tömb Bejárása For Ciklussal & Memóriacím Léptetés',
    category: 'Educational',
    categoryHu: 'Oktató & Memória',
    description: 'Demonstrates indexing an array sequentially, calculating element offsets (Base + i * sizeof).',
    descriptionHu: 'Szemlélteti a tömbelemek szekvenciális elérését, az indexelést és a bájt-léptetést.',
    targetMcu: 'MCU_A',
    blocks: [
      {
        instanceId: 'b-pattern-arr',
        blockType: 'ARRAY_DECLARE',
        params: {
          arrayName: 'ledPatterns',
          dataType: 'byte',
          size: 6,
          initValues: '1, 2, 4, 8, 16, 32',
          location: 'SRAM',
        },
      },
      {
        instanceId: 'b-for-each',
        blockType: 'ARRAY_FOR_LOOP',
        params: { indexVar: 'i', arrayName: 'ledPatterns', limitCount: 6 },
        children: [
          {
            instanceId: 'b-get-val',
            blockType: 'ARRAY_GET_ELEMENT',
            params: { targetVar: 'activeVal', arrayName: 'ledPatterns', index: 'i' },
          },
          {
            instanceId: 'b-servo-out',
            blockType: 'SERVO_WRITE',
            params: { pin: '9', angle: 'activeVal * 5' },
          },
          {
            instanceId: 'b-inner-delay',
            blockType: 'DELAY_MS',
            params: { ms: 100 },
          },
        ],
      },
    ],
  },
];
