import { McuInterruptVector } from '../types/mcu';

export const ATMEGA328P_INTERRUPT_VECTORS: McuInterruptVector[] = [
  {
    vectorNum: 1,
    address: '0x0000',
    symbol: 'RESET_vect',
    name: 'Reset (Power-On, Brown-Out, Watchdog)',
    nameHu: 'Hardveres Reset (Bekapcsolás, Barna-zavar, Watchdog)',
    source: 'Power / RESET pin / WDT / BOD',
    trigger: 'Power-on voltage threshold, low level on RESET pin, or WDT timeout',
    triggerHu: 'Bekapcsolási feszültségküszöb, alacsony szint a RESET lábon, vagy Watchdog időtúllépés',
    priority: 1,
    maskRegister: 'N/A (Non-maskable)',
    maskBit: '-',
    flagRegister: 'MCUSR',
    flagBit: 'PORF, EXTRF, BORF, WDRF',
    category: 'SYSTEM',
    description: 'Initializes the MCU hardware registers, stacks, and branches to .org 0x0000 entry point.',
    descriptionHu: 'Inicializálja a mikrovezérlő hardveres regisztereit, a vermet, és a 0x0000 címen lévő belépési pontra ugrik.',
    exampleCode: `.org 0x0000\n  rjmp main_init`,
  },
  {
    vectorNum: 2,
    address: '0x0002',
    symbol: 'INT0_vect',
    name: 'External Interrupt Request 0 (Pin PD2 / D2)',
    nameHu: '0. Külső Megszakítás Kérelem (PD2 / D2 Láb)',
    source: 'Pin PD2 (Arduino D2)',
    trigger: 'Configurable edge (Low level, Any change, Falling edge, Rising edge in EICRA)',
    triggerHu: 'Konfigurálható jelváltás (Alacsony szint, Bármely változás, Lefutó él, Felfutó él az EICRA-ban)',
    priority: 2,
    maskRegister: 'EIMSK',
    maskBit: 'INT0 (Bit 0)',
    flagRegister: 'EIFR',
    flagBit: 'INTF0 (Bit 0)',
    category: 'EXTERNAL',
    description: 'Fast asynchronous hardware interrupt for buttons, rotary encoders, and external sensors.',
    descriptionHu: 'Gyors aszinkron hardveres megszakítás nyomógombokhoz, forgó enkóderekhez és külső szenzorokhoz.',
    exampleCode: `// Arduino C\nattachInterrupt(digitalPinToInterrupt(2), isrInt0, FALLING);\n\n// AVR Assembly\nldi r16, 0x02  ; Falling edge\nout EICRA, r16\nsbi EIMSK, 0   ; Enable INT0\nsei`,
  },
  {
    vectorNum: 3,
    address: '0x0004',
    symbol: 'INT1_vect',
    name: 'External Interrupt Request 1 (Pin PD3 / D3)',
    nameHu: '1. Külső Megszakítás Kérelem (PD3 / D3 Láb)',
    source: 'Pin PD3 (Arduino D3)',
    trigger: 'Configurable edge (Low level, Any change, Falling edge, Rising edge in EICRA)',
    triggerHu: 'Konfigurálható él (Alacsony szint, Bármely változás, Lefutó él, Felfutó él az EICRA-ban)',
    priority: 3,
    maskRegister: 'EIMSK',
    maskBit: 'INT1 (Bit 1)',
    flagRegister: 'EIFR',
    flagBit: 'INTF1 (Bit 1)',
    category: 'EXTERNAL',
    description: 'Second dedicated external interrupt pin for high-priority external signals.',
    descriptionHu: 'Második dedikált külső megszakítási láb magas prioritású bemeneti jelekhez.',
    exampleCode: `// Arduino C\nattachInterrupt(digitalPinToInterrupt(3), isrInt1, RISING);`,
  },
  {
    vectorNum: 4,
    address: '0x0006',
    symbol: 'PCINT0_vect',
    name: 'Pin Change Interrupt Request 0 (PB0..PB7)',
    nameHu: 'Lábállapot-változás Megszakítás 0 (PB0..PB7 / D8..D13)',
    source: 'Port B Pins (PB0..PB7)',
    trigger: 'Any logic level transition on enabled PCINT0..7 pins',
    triggerHu: 'Bármely logikai szintváltás az engedélyezett PB lábakon',
    priority: 4,
    maskRegister: 'PCICR & PCMSK0',
    maskBit: 'PCIE0 & PCINT0..7',
    flagRegister: 'PCIFR',
    flagBit: 'PCIF0',
    category: 'EXTERNAL',
    description: 'Triggers when any configured pin on PORT B changes state (0->1 or 1->0).',
    descriptionHu: 'Megszakítást vált ki, ha a B port bármely engedélyezett lába állapotot vált.',
    exampleCode: `sbi PCICR, 0   ; Enable PCIE0\nldi r16, 0x20  ; Enable PB5\nsts PCMSK0, r16\nsei`,
  },
  {
    vectorNum: 5,
    address: '0x0008',
    symbol: 'PCINT1_vect',
    name: 'Pin Change Interrupt Request 1 (PC0..PC6)',
    nameHu: 'Lábállapot-változás Megszakítás 1 (PC0..PC6 / A0..A5)',
    source: 'Port C Pins (Analog A0..A5)',
    trigger: 'Any logic level transition on enabled PCINT8..14 pins',
    triggerHu: 'Bármely logikai szintváltás a C port analóg lábain',
    priority: 5,
    maskRegister: 'PCICR & PCMSK1',
    maskBit: 'PCIE1 & PCINT8..14',
    flagRegister: 'PCIFR',
    flagBit: 'PCIF1',
    category: 'EXTERNAL',
    description: 'Pin change interrupt for Analog Input port C pins.',
    descriptionHu: 'Lábállapot-változás megszakítás a C port analóg lábaihoz.',
    exampleCode: `sbi PCICR, 1   ; Enable PCIE1\nsts PCMSK1, 0x01 ; Enable A0\nsei`,
  },
  {
    vectorNum: 6,
    address: '0x000A',
    symbol: 'PCINT2_vect',
    name: 'Pin Change Interrupt Request 2 (PD0..PD7)',
    nameHu: 'Lábállapot-változás Megszakítás 2 (PD0..PD7 / D0..D7)',
    source: 'Port D Pins (PD0..PD7)',
    trigger: 'Any logic level transition on enabled PCINT16..23 pins',
    triggerHu: 'Bármely logikai szintváltás a D port lábain',
    priority: 6,
    maskRegister: 'PCICR & PCMSK2',
    maskBit: 'PCIE2 & PCINT16..23',
    flagRegister: 'PCIFR',
    flagBit: 'PCIF2',
    category: 'EXTERNAL',
    description: 'Pin change interrupt for digital port D pins.',
    descriptionHu: 'Lábállapot-változás megszakítás a D port digitális lábaihoz.',
    exampleCode: `sbi PCICR, 2   ; Enable PCIE2\nsts PCMSK2, 0x80 ; Enable PD7\nsei`,
  },
  {
    vectorNum: 7,
    address: '0x000C',
    symbol: 'WDT_vect',
    name: 'Watchdog Time-out Interrupt',
    nameHu: 'Watchdog Időzítő Túllépés Megszakítás',
    source: 'Internal 128 kHz Low Power RC Oscillator',
    trigger: 'Watchdog counter exceeds timeout period in Interrupt Mode',
    triggerHu: 'A Watchdog számláló eléri a beállított időkorlátot megszakítás módban',
    priority: 7,
    maskRegister: 'WDTCSR',
    maskBit: 'WDIE (Bit 6)',
    flagRegister: 'WDTCSR',
    flagBit: 'WDIF (Bit 7)',
    category: 'SYSTEM',
    description: 'Allows safe shutdown or telemetry dumping before an actual reset occurs.',
    descriptionHu: 'Lehetővé teszi az adatok mentését a hardveres újraindulás előtt.',
    exampleCode: `wdt_enable(WDTO_2S); // Enable 2s timeout`,
  },
  {
    vectorNum: 8,
    address: '0x000E',
    symbol: 'TIMER2_COMPA_vect',
    name: 'Timer/Counter2 Compare Match A',
    nameHu: 'Timer2 Összehasonlítás Egyezés A (OCR2A)',
    source: 'Timer2 (8-bit) Compare Unit A',
    trigger: 'TCNT2 counter matches OCR2A register value',
    triggerHu: 'A TCNT2 számláló eléri az OCR2A regiszter értékét',
    priority: 8,
    maskRegister: 'TIMSK2',
    maskBit: 'OCIE2A (Bit 1)',
    flagRegister: 'TIFR2',
    flagBit: 'OCF2A (Bit 1)',
    category: 'TIMER',
    description: 'Used for tone generation, periodic RTC ticks, and high-frequency CTC timing.',
    descriptionHu: 'Hanggenerálásra, időzített CTC mintavételezésre használható.',
    exampleCode: `sbi TIMSK2, 1  ; OCIE2A = 1\nsei`,
  },
  {
    vectorNum: 10,
    address: '0x0012',
    symbol: 'TIMER2_OVF_vect',
    name: 'Timer/Counter2 Overflow',
    nameHu: 'Timer2 Túlcsordulás Megszakítás',
    source: 'Timer2 (8-bit) Counter',
    trigger: 'TCNT2 rolls over from 0xFF (255) to 0x00',
    triggerHu: 'A TCNT2 számláló átfordul 0xFF-ről 0x00-ra',
    priority: 10,
    maskRegister: 'TIMSK2',
    maskBit: 'TOIE2 (Bit 0)',
    flagRegister: 'TIFR2',
    flagBit: 'TOV2 (Bit 0)',
    category: 'TIMER',
    description: 'Asynchronous 8-bit timer overflow, can run from external 32.768 kHz watch crystal.',
    descriptionHu: 'Aszinkron 8-bites időzítő túlcsordulás, külső 32.768 kHz-es órakvarccal is működtethető.',
    exampleCode: `sbi TIMSK2, 0  ; TOIE2 = 1\nsei`,
  },
  {
    vectorNum: 12,
    address: '0x0016',
    symbol: 'TIMER1_COMPA_vect',
    name: 'Timer/Counter1 Compare Match A (16-bit)',
    nameHu: 'Timer1 Összehasonlítás Egyezés A (16-bites OCR1A)',
    source: 'Timer1 (16-bit) Compare Unit A',
    trigger: 'TCNT1 (16-bit) matches OCR1A (0..65535)',
    triggerHu: 'A TCNT1 16-bites számláló eléri az OCR1A regiszter értékét',
    priority: 12,
    maskRegister: 'TIMSK1',
    maskBit: 'OCIE1A (Bit 1)',
    flagRegister: 'TIFR1',
    flagBit: 'OCF1A (Bit 1)',
    category: 'TIMER',
    description: 'High-precision 16-bit periodic timer for frequency generators, PID loops, and servo timing.',
    descriptionHu: 'Nagy pontosságú 16-bites időzítő periódusokhoz, PID szabályzóhoz és szervó vezérléshez.',
    exampleCode: `// Arduino C: 1 Hz Precise Interrupt Timer\nISR(TIMER1_COMPA_vect) {\n  digitalWrite(13, !digitalRead(13));\n}`,
  },
  {
    vectorNum: 14,
    address: '0x001A',
    symbol: 'TIMER1_OVF_vect',
    name: 'Timer/Counter1 Overflow (16-bit)',
    nameHu: 'Timer1 16-bites Túlcsordulás Megszakítás',
    source: 'Timer1 (16-bit) Counter',
    trigger: 'TCNT1 rolls over from 0xFFFF (65535) to 0x0000',
    triggerHu: 'A TCNT1 átfordul 0xFFFF-ről 0x0000-ra',
    priority: 14,
    maskRegister: 'TIMSK1',
    maskBit: 'TOIE1 (Bit 0)',
    flagRegister: 'TIFR1',
    flagBit: 'TOV1 (Bit 0)',
    category: 'TIMER',
    description: '16-bit overflow event occurring every 65536 timer clock ticks.',
    descriptionHu: '16-bites túlcsordulási esemény minden 65536 órajelciklusban.',
    exampleCode: `sbi TIMSK1, 0  ; TOIE1 = 1\nsei`,
  },
  {
    vectorNum: 15,
    address: '0x001C',
    symbol: 'TIMER0_COMPA_vect',
    name: 'Timer/Counter0 Compare Match A (8-bit)',
    nameHu: 'Timer0 Összehasonlítás Egyezés A (OCR0A)',
    source: 'Timer0 (8-bit) Compare Unit A',
    trigger: 'TCNT0 counter matches OCR0A value',
    triggerHu: 'A TCNT0 számláló eléri az OCR0A értékét',
    priority: 15,
    maskRegister: 'TIMSK0',
    maskBit: 'OCIE0A (Bit 1)',
    flagRegister: 'TIFR0',
    flagBit: 'OCF0A (Bit 1)',
    category: 'TIMER',
    description: '8-bit timer compare match interrupt on Timer 0.',
    descriptionHu: '8-bites összehasonlító megszakítás a 0-s időzítőn.',
    exampleCode: `sbi TIMSK0, 1  ; OCIE0A = 1\nsei`,
  },
  {
    vectorNum: 17,
    address: '0x0020',
    symbol: 'TIMER0_OVF_vect',
    name: 'Timer/Counter0 Overflow (millis() Timebase)',
    nameHu: 'Timer0 Túlcsordulás (Arduino millis() alapórajel)',
    source: 'Timer0 (8-bit) Counter',
    trigger: 'TCNT0 rolls over from 255 to 0 (Every 1.024 ms @ 16MHz with /64 prescaler)',
    triggerHu: 'TCNT0 átfordul 255-ről 0-ra (1.024 ms-onként 16MHz-en /64 előosztóval)',
    priority: 17,
    maskRegister: 'TIMSK0',
    maskBit: 'TOIE0 (Bit 0)',
    flagRegister: 'TIFR0',
    flagBit: 'TOV0 (Bit 0)',
    category: 'TIMER',
    description: 'The heartbeat of the Arduino framework! Powers millis(), micros(), and delay().',
    descriptionHu: 'Az Arduino környezet szívverése! Ez működteti a millis(), micros() és delay() függvényeket.',
    exampleCode: `// Arduino framework core ISR\nISR(TIMER0_OVF_vect) {\n  timer0_millis++;\n}`,
  },
  {
    vectorNum: 18,
    address: '0x0022',
    symbol: 'SPI_STC_vect',
    name: 'SPI Serial Transfer Complete',
    nameHu: 'SPI Soros Adatátvitel Kész',
    source: 'Hardware SPI Peripheral (MOSI, MISO, SCK)',
    trigger: '8 bits of data shifted in/out through SPDR register',
    triggerHu: '8 bit adat sikeresen ki- és betolva az SPDR regiszteren keresztül',
    priority: 18,
    maskRegister: 'SPCR',
    maskBit: 'SPIE (Bit 7)',
    flagRegister: 'SPSR',
    flagBit: 'SPIF (Bit 7)',
    category: 'COMMUNICATION',
    description: 'Signals that a hardware SPI byte transfer has completed.',
    descriptionHu: 'Jelzi, hogy egy 8 bites hardveres SPI adatátvitel befejeződött.',
    exampleCode: `ISR(SPI_STC_vect) {\n  uint8_t received = SPDR;\n}`,
  },
  {
    vectorNum: 19,
    address: '0x0024',
    symbol: 'USART_RX_vect',
    name: 'USART Rx Complete (Byte in UDR0)',
    nameHu: 'USART Fogadás Befejezve (Új bájt a UDR0-ban)',
    source: 'USART0 Receiver (Pin PD0 / RXD)',
    trigger: 'New unread byte received in the UART receive buffer',
    triggerHu: 'Új beérkező bájt érkezett az UART fogadó pufferébe',
    priority: 19,
    maskRegister: 'UCSR0B',
    maskBit: 'RXCIE0 (Bit 7)',
    flagRegister: 'UCSR0A',
    flagBit: 'RXC0 (Bit 7)',
    category: 'COMMUNICATION',
    description: 'Triggers immediately when a serial byte is received, preventing FIFO buffer overflow.',
    descriptionHu: 'Azonnal lefut, amint új soros bájt érkezik a PD0 (RX) lábon.',
    exampleCode: `ISR(USART_RX_vect) {\n  char c = UDR0;\n  Serial.print(c);\n}`,
  },
  {
    vectorNum: 20,
    address: '0x0026',
    symbol: 'USART_UDRE_vect',
    name: 'USART Data Register Empty',
    nameHu: 'USART Adatregiszter Üres (UDR0 küldésre kész)',
    source: 'USART0 Transmitter',
    trigger: 'UDR0 register is empty and ready to accept next transmit byte',
    triggerHu: 'Az UDR0 regiszter üres és készen áll a következő kiküldendő bájtra',
    priority: 20,
    maskRegister: 'UCSR0B',
    maskBit: 'UDRIE0 (Bit 5)',
    flagRegister: 'UCSR0A',
    flagBit: 'UDRE0 (Bit 5)',
    category: 'COMMUNICATION',
    description: 'Enables non-blocking background serial transmission rings.',
    descriptionHu: 'Blokkolásmentes soros körpufferes adattovábbítást tesz lehetővé.',
    exampleCode: `sbi UCSR0B, 5  ; UDRIE0 = 1`,
  },
  {
    vectorNum: 21,
    address: '0x0028',
    symbol: 'USART_TX_vect',
    name: 'USART Tx Complete',
    nameHu: 'USART Adás Befejezve',
    source: 'USART0 Shift Register',
    trigger: 'Entire frame shifted out of transmitter register and no new data in UDR0',
    triggerHu: 'A teljes keret kiküldésre került a shift regiszterből',
    priority: 21,
    maskRegister: 'UCSR0B',
    maskBit: 'TXCIE0 (Bit 6)',
    flagRegister: 'UCSR0A',
    flagBit: 'TXC0 (Bit 6)',
    category: 'COMMUNICATION',
    description: 'Useful for half-duplex RS-485 transceiver direction switching (switching to receive mode).',
    descriptionHu: 'Kifejezetten hasznos félduplex RS-485 adó-vevő irányváltáshoz.',
    exampleCode: `sbi UCSR0B, 6  ; TXCIE0 = 1`,
  },
  {
    vectorNum: 22,
    address: '0x002A',
    symbol: 'ADC_vect',
    name: 'ADC Conversion Complete',
    nameHu: 'ADC Analóg-Digitális Átalakítás Kész',
    source: '10-bit Successive Approximation ADC',
    trigger: '10-bit conversion finished; result updated in ADCL and ADCH registers',
    triggerHu: '10-bites mérés befejeződött; az eredmény beíródott az ADCL és ADCH regiszterekbe',
    priority: 22,
    maskRegister: 'ADCSRA',
    maskBit: 'ADIE (Bit 3)',
    flagRegister: 'ADCSRA',
    flagBit: 'ADIF (Bit 4)',
    category: 'ANALOG',
    description: 'Allows background asynchronous sensor sampling without blocking the CPU in busy-wait loops.',
    descriptionHu: 'Lehetővé teszi az analóg jelek háttérben történő mérését várakozási ciklusok nélkül.',
    exampleCode: `ISR(ADC_vect) {\n  uint16_t adcVal = ADC; // Read ADCL + ADCH\n}`,
  },
  {
    vectorNum: 23,
    address: '0x002C',
    symbol: 'EE_READY_vect',
    name: 'EEPROM Ready',
    nameHu: 'EEPROM Írás Kész',
    source: 'On-chip Non-Volatile EEPROM Controller',
    trigger: 'EEPROM programming cycle (~3.4 ms) has finished',
    triggerHu: 'Az EEPROM belső írási ciklusa (~3.4 ms) befejeződött',
    priority: 23,
    maskRegister: 'EECR',
    maskBit: 'EERIE (Bit 3)',
    flagRegister: 'EECR',
    flagBit: 'EEPE (Bit 1, cleared to 0)',
    category: 'SYSTEM',
    description: 'Informs CPU that the next EEPROM write or read operation can be safely started.',
    descriptionHu: 'Jelzi a CPU-nak, hogy a következő EEPROM művelet biztonságosan megkezdhető.',
    exampleCode: `sbi EECR, 3   ; EERIE = 1\nsei`,
  },
  {
    vectorNum: 24,
    address: '0x002E',
    symbol: 'ANALOG_COMP_vect',
    name: 'Analog Comparator',
    nameHu: 'Analóg Komparátor Megszakítás',
    source: 'Internal Analog Comparator (AIN0 / PD6 vs AIN1 / PD7)',
    trigger: 'Voltage difference comparison threshold crossing',
    triggerHu: 'Feszültségkülönbség komparálási küszöb átlépése',
    priority: 24,
    maskRegister: 'ACSR',
    maskBit: 'ACIE (Bit 3)',
    flagRegister: 'ACSR',
    flagBit: 'ACI (Bit 4)',
    category: 'ANALOG',
    description: 'Ultra fast analog threshold crossing interrupt without full ADC conversion overhead.',
    descriptionHu: 'Rendkívül gyors analóg feszültség-küszöb átlépés megszakítás.',
    exampleCode: `sbi ACSR, 3   ; ACIE = 1\nsei`,
  },
  {
    vectorNum: 25,
    address: '0x0030',
    symbol: 'TWI_vect',
    name: '2-Wire Serial Interface (I2C Bus)',
    nameHu: 'I2C / TWI 2-Vezetékes Soros Busz Esemény',
    source: 'Hardware I2C / TWI Module (SDA / PC4, SCL / PC5)',
    trigger: 'I2C START, STOP, SLA+W/R, or Data Byte ACK/NACK processed',
    triggerHu: 'I2C START, STOP, címzés vagy adatbájt ACK/NACK feldolgozva',
    priority: 25,
    maskRegister: 'TWCR',
    maskBit: 'TWIE (Bit 0)',
    flagRegister: 'TWCR',
    flagBit: 'TWINT (Bit 7)',
    category: 'COMMUNICATION',
    description: 'Handles non-blocking I2C bus state machine for RTCs, OLEDs, and external sensors.',
    descriptionHu: 'Kezeli az I2C busz állapotgépét RTC órákhoz, OLED kijelzőkhöz és szenzorokhoz.',
    exampleCode: `ISR(TWI_vect) {\n  uint8_t status = TWSR & 0xF8;\n}`,
  },
];
