import { ProtocolSpec, ProtocolType } from '../types/mcuProtocols';

export const PROTOCOL_SPECS: Record<ProtocolType, ProtocolSpec> = {
  // ==========================================
  // 1. DALLAS 1-WIRE
  // ==========================================
  ONE_WIRE: {
    id: 'ONE_WIRE',
    name: 'Dallas 1-Wire',
    nameHu: 'Dallas 1-Wire Protokoll',
    shortDescription: 'Single-wire bidirectional serial bus with parasitic power support and 64-bit unique factory ROM codes.',
    shortDescriptionHu: 'Egyetlen vezetékes kétirányú busz parazita tápellátással és egyedi 64-bites gyári ROM azonosítókkal.',
    inventor: 'Dallas Semiconductor (Maxim / Analog Devices)',
    year: 1990,
    physicalLines: ['DQ (Data + VPU)', 'GND'],
    topology: 'Single-Ended Master-Slave',
    topologyHu: 'Nyitott kollektoros egyvezetékes busz (Master-Slave)',
    signalingType: 'Single-Ended Open-Drain (Pull-Up)',
    signalingTypeHu: 'Open-Drain felhúzó ellenállással (4.7 kΩ)',
    wireCount: 2, // DQ + GND (or 3 with VCC)
    maxSpeed: '16.3 kbps (Standard) / 142 kbps (Overdrive)',
    maxDistance: '~100 - 300 m',
    duplexMode: 'Half-Duplex',
    multiMaster: false,
    typicalTransceiver: 'DS2482 / DS2480B / MCU Direct GPIO with 4.7kΩ Pull-up',
    typicalApplications: [
      'DS18B20 Digital Thermometers',
      'iButton Electronic Keys & Access Control',
      'Battery Authentication & EEPROM chips (DS2431)',
    ],
    typicalApplicationsHu: [
      'DS18B20 digitális precíziós hőmérők',
      'iButton beléptető és azonosító kulcsok',
      'Akkumulátor azonosítók és kisméretű EEPROM-ok (DS2431)',
    ],
    color: '#06B6D4', // Cyan
    presets: [
      {
        id: '1wire-temp-convert',
        title: 'DS18B20: Reset, Presence & Convert T (0x44)',
        titleHu: 'DS18B20: Reset, Presence és Convert T parancs (0x44)',
        description: 'Demonstrates 1-Wire bus Reset pulse (>480µs), Slave Presence response (60-240µs), Skip ROM (0xCC), and Convert Temperature command (0x44).',
        descriptionHu: '1-Wire Reset impulzus (>480µs), szolga Presence válasz (60-240µs), Skip ROM (0xCC) és Convert T parancs (0x44) átvitele.',
        defaultPayload: '0xCC, 0x44',
        baudRateKbps: 16.3,
        steps: [
          {
            stepIndex: 0,
            timeUs: 0,
            phaseName: 'Bus Idle (Pull-Up to 5V)',
            phaseNameHu: 'Busz Alapállapot (4.7kΩ Felhúzás 5V-ra)',
            category: 'IDLE',
            signals: { DQ: 1 },
            busVoltages: { DQ: 5.0 },
            explanation: 'The 1-Wire bus is held HIGH at 5V by the external 4.7kΩ pull-up resistor. No device is actively pulling the line to ground.',
            explanationHu: 'A vonalat a 4.7kΩ-os külső felhúzó ellenállás 5V magas szinten (HIGH) tartja. Egyetlen eszköz sem húzza le a vonalat.',
            masterAction: 'Tri-state / Input (Listening)',
            masterActionHu: 'Nagyimpedanciás bemenet (Figyelés)',
            slaveAction: 'Passive (Listening for Reset)',
            slaveActionHu: 'Passzív várakozás Reset impulzusra',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 1,
            timeUs: 10,
            phaseName: 'Master Reset Pulse (Drive LOW for 480µs)',
            phaseNameHu: 'Master Reset Impulzus (DQ lehúzása GND-re 480µs-ig)',
            category: 'RESET',
            signals: { DQ: 0 },
            busVoltages: { DQ: 0.1 },
            explanation: 'Master initiates communication by asserting a RESET pulse: pulling the DQ line to GND (0V) for minimum 480 microseconds.',
            explanationHu: 'A Master megkezdi a tranzakciót egy RESET impulzussal: a DQ vonalat földre (0V) húzza legalább 480 mikromásodpercre.',
            masterAction: 'Drive DQ = LOW (GND output)',
            masterActionHu: 'DQ láb lehúzása LOW-ra (GND)',
            slaveAction: 'Detects continuous LOW > 480µs; resets internal state machine',
            slaveActionHu: 'Érzékeli a hosszú LOW szintet; belső állapotgépét alaphelyzetbe állítja',
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 2,
            timeUs: 490,
            phaseName: 'Master Release & Pull-Up Recovery (15-60µs)',
            phaseNameHu: 'Master Felengedés & Felfutás (15-60µs várakozás)',
            category: 'RESET',
            signals: { DQ: 1 },
            busVoltages: { DQ: 5.0 },
            explanation: 'Master releases the line. The 4.7kΩ pull-up pulls DQ back up to 5V. Master switches to input mode to detect the slave.',
            explanationHu: 'A Master felengedi a vonalat, a felhúzó ellenállás visszahúzza 5V-ra. A Master bemenetre kapcsol és várja a szolga jelenléti jelét.',
            masterAction: 'Release DQ -> Input mode',
            masterActionHu: 'DQ felengedése -> Bemeneti mód',
            slaveAction: 'Waits 15-60µs before asserting Presence Pulse',
            slaveActionHu: '15-60µs-ig vár a válasz előtt',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 3,
            timeUs: 520,
            phaseName: 'Slave Presence Pulse (Pull LOW 60-240µs)',
            phaseNameHu: 'Szolga Jelenléti Impulzus (Presence Pulse 60-240µs)',
            category: 'PRESENCE',
            signals: { DQ: 0 },
            busVoltages: { DQ: 0.2 },
            explanation: 'DS18B20 detects rising edge and responds by pulling DQ LOW for 60 to 240µs. Master samples line at ~550µs and detects slave presence!',
            explanationHu: 'A DS18B20 érzékeli a felfutást, és a DQ vonalat földre húzza 60-240µs ideig. A Master mintavételezi a 0V-ot -> Szolga jelen van!',
            masterAction: 'Samples DQ line -> Reads logic 0 (PRESENCE CONFIRMED)',
            masterActionHu: 'Mintavételezi a vonalat -> Logikai 0-t olvas (SZOLGA JELENLÉT NYUGTÁZVA)',
            slaveAction: 'Drive DQ = LOW (Presence assertion)',
            slaveActionHu: 'DQ lehúzása GND-re (Jelenlét igazolása)',
            highlightNode: 'SLAVE_1',
          },
          {
            stepIndex: 4,
            timeUs: 760,
            phaseName: 'Presence Complete & Bus Recovery',
            phaseNameHu: 'Presence Vége & Busz Visszaállás',
            category: 'IDLE',
            signals: { DQ: 1 },
            busVoltages: { DQ: 5.0 },
            explanation: 'Slave releases DQ. Line returns to 5V. The 1-Wire bus is now ready for command byte transmission.',
            explanationHu: 'A szolga felengedi a vonalat, amely visszatér 5V-ra. A busz készen áll az első parancsbájt fogadására.',
            masterAction: 'Prepares Write-0 and Write-1 time slots',
            masterActionHu: 'Előkészíti a parancsbitek időréseit (Time Slots)',
            slaveAction: 'Ready to decode command bits',
            slaveActionHu: 'Készen áll a parancsbitek dekódolására',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 5,
            timeUs: 800,
            phaseName: 'Write-0 Time Slot (Pull LOW 60-120µs)',
            phaseNameHu: 'Write-0 Időrés (Lehúzás 60-120µs hosszan)',
            category: 'DATA',
            signals: { DQ: 0 },
            busVoltages: { DQ: 0.1 },
            explanation: 'To write a logic 0, Master pulls DQ LOW and holds it LOW for at least 60µs (up to 120µs). Slave samples at 15-30µs and reads bit 0.',
            explanationHu: 'Logikai 0 írásához a Master földre húzza a DQ vonalat és legalább 60µs-ig lent tartja. A szolga a 15-30. µs között mintavételezi -> Bit 0.',
            masterAction: 'Hold DQ = LOW for 70µs (Bit = 0)',
            masterActionHu: 'DQ lent tartása 70µs-ig (Bit = 0)',
            slaveAction: 'Samples at 25µs -> Decodes Logic 0',
            slaveActionHu: 'Mintavétel a 25. µs-nál -> Logikai 0 elmentése',
            activeBytes: { txByte: 0xcc, bitIndex: 0, byteName: 'Skip ROM (0xCC)' },
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 6,
            timeUs: 880,
            phaseName: 'Write-1 Time Slot (Pull LOW 1-15µs then Release)',
            phaseNameHu: 'Write-1 Időrés (Rövid lehúzás 1-15µs, majd felengedés)',
            category: 'DATA',
            signals: { DQ: 1 },
            busVoltages: { DQ: 5.0 },
            explanation: 'To write a logic 1, Master pulls DQ LOW briefly (<15µs) and releases it. Line rises to 5V before the 15-30µs sample point.',
            explanationHu: 'Logikai 1 írásához a Master csak 2-5µs-ig húzza le a vonalat, majd felengedi. A mintavétel pillanatában (25µs) a vonal már 5V -> Bit 1.',
            masterAction: 'Pulse DQ LOW for 3µs, then release to 5V',
            masterActionHu: 'DQ rövid lehúzása 3µs-ig, majd felengedés 5V-ra',
            slaveAction: 'Samples at 25µs -> Decodes Logic 1',
            slaveActionHu: 'Mintavétel a 25. µs-nál -> Logikai 1 elmentése',
            activeBytes: { txByte: 0xcc, bitIndex: 1, byteName: 'Skip ROM (0xCC)' },
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 7,
            timeUs: 960,
            phaseName: 'Command Byte 0x44: Convert Temperature',
            phaseNameHu: '0x44 Parancsbájt: Hőmérséklet Mérés Indítása',
            category: 'DATA',
            signals: { DQ: 1 },
            busVoltages: { DQ: 5.0 },
            explanation: 'Master finishes sending 0x44 (Convert T). The DS18B20 internal ADC initiates a 12-bit temperature conversion cycle (750ms).',
            explanationHu: 'A Master befejezi a 0x44 parancs kiküldését. A DS18B20 belső precíziós ADC-je megkezdi a 12-bites hőmérséklet-átalakítást (750ms).',
            masterAction: 'Enables Strong Pull-up or polls for completion',
            masterActionHu: 'Erős felhúzást biztosít vagy periodikusan lekérdez',
            slaveAction: 'Converts thermal sensor voltage to digital scratchpad registers',
            slaveActionHu: 'A hőszenzor analóg feszültségét 12-bites digitális adattá konvertálja',
            activeBytes: { txByte: 0x44, byteName: 'Convert T (0x44)' },
            highlightNode: 'SLAVE_1',
          },
        ],
      },
    ],
  },

  // ==========================================
  // 2. I2C (INTER-INTEGRATED CIRCUIT)
  // ==========================================
  I2C: {
    id: 'I2C',
    name: 'I2C (Inter-Integrated Circuit)',
    nameHu: 'I2C (Kétvezetékes Busz / TWI)',
    shortDescription: 'Synchronous, multi-master, multi-slave 2-wire serial bus with addressing, clock stretching and hardware ACK/NACK.',
    shortDescriptionHu: 'Szinkron, multi-master, címzett 2-vezetékes soros busz hardveres ACK nyugtázással és órajel-nyújtással.',
    inventor: 'Philips Semiconductors (NXP)',
    year: 1982,
    physicalLines: ['SDA (Serial Data)', 'SCL (Serial Clock)', 'VCC', 'GND'],
    topology: 'Open-Drain Multi-Master',
    topologyHu: 'Nyitott kollektoros kétirányú busz (SDA + SCL) felhúzó ellenállásokkal',
    signalingType: 'Single-Ended Open-Drain (Pull-Up)',
    signalingTypeHu: 'Open-Drain felhúzókkal (2.2kΩ - 4.7kΩ)',
    wireCount: 4, // SDA, SCL, VCC, GND
    maxSpeed: '100 kbps (Standard) / 400 kbps (Fast) / 3.4 Mbps (High-Speed)',
    maxDistance: '~1 - 3 m (on-board / intra-enclosure)',
    duplexMode: 'Half-Duplex',
    multiMaster: true,
    typicalTransceiver: 'Native MCU GPIO Open-Drain / PCA9548A / PCF8574',
    typicalApplications: [
      'DS3231 RTC Real-Time Clocks (0x68)',
      'SSD1306 OLED & HD44780 LCD I2C Backpacks (0x3C / 0x27)',
      'AT24C32 EEPROM Memories (0x57)',
      'MPU6050 Accelerometer / Gyroscope (0x68)',
    ],
    typicalApplicationsHu: [
      'DS3231 valós idejű órák (RTC - 0x68)',
      'SSD1306 OLED és 16x2 LCD I2C illesztők (0x3C / 0x27)',
      'AT24C32 EEPROM memóriák (0x57)',
      'MPU-6050 6-tengelyes giroszkóp és gyorsulásmérő (0x68)',
    ],
    color: '#8B5CF6', // Purple
    presets: [
      {
        id: 'i2c-write-rtc',
        title: 'I2C Master Write to DS3231 RTC (0x68)',
        titleHu: 'I2C Master Írás a DS3231 RTC-be (Cím: 0x68, Reg: 0x00)',
        description: 'Visualizes START condition, 7-bit Address (0x68) + Write bit (0), Slave ACK on 9th clock, Register Pointer (0x00) + ACK, and STOP condition.',
        descriptionHu: 'START állapot, 7-bites cím (0x68) + Írás bit (0), szolga ACK válasz a 9. órajelre, regiszter pointer (0x00) + ACK és STOP állapot.',
        defaultPayload: 'ADDR: 0x68, REG: 0x00, DATA: 0x45',
        addressHex: '0x68',
        baudRateKbps: 100,
        steps: [
          {
            stepIndex: 0,
            timeUs: 0,
            phaseName: 'Bus Idle (SCL=HIGH, SDA=HIGH)',
            phaseNameHu: 'Busz Alapállapot (SCL=1, SDA=1)',
            category: 'IDLE',
            signals: { SCL: 1, SDA: 1 },
            busVoltages: { SCL: 5.0, SDA: 5.0 },
            explanation: 'Both SCL and SDA lines are held HIGH at 5V by external 4.7kΩ pull-up resistors. Bus is idle and available.',
            explanationHu: 'Mind a vezérlő órajel (SCL), mind az adatvonal (SDA) 5V magas szinten áll a felhúzó ellenállások miatt.',
            masterAction: 'Line released (HIGH)',
            masterActionHu: 'Vonalak elengedve (Magas szint)',
            slaveAction: 'Passive monitoring of SDA transitions',
            slaveActionHu: 'Passzív SDA és SCL figyelés',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 1,
            timeUs: 10,
            phaseName: 'START Condition (SDA goes LOW while SCL is HIGH)',
            phaseNameHu: 'START Állapot (SDA lefut, miközben az SCL MAGAS)',
            category: 'START',
            signals: { SCL: 1, SDA: 0 },
            busVoltages: { SCL: 5.0, SDA: 0.1 },
            explanation: 'CRITICAL RULE: Data on SDA may ONLY change when SCL is LOW. An SDA falling edge while SCL is HIGH signals a unique START condition to all slaves!',
            explanationHu: 'ALAPSZABÁLY: Az SDA csak akkor változhat, ha az SCL ALACSONY. Ha az SDA úgy vált LOW-ra, hogy az SCL MAGAS, az a globális START jelzés!',
            masterAction: 'Pulls SDA = LOW while keeping SCL = HIGH',
            masterActionHu: 'SDA lehúzása földre, miközben az SCL még 5V-on van',
            slaveAction: 'All slaves wake up and arm address decoders',
            slaveActionHu: 'Minden I2C szolga felébred és felkészül a 7-bites cím fogadására',
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 2,
            timeUs: 20,
            phaseName: 'Address Bit 6 (1): SCL Clock Pulse 1',
            phaseNameHu: 'Cím 6. Bit (1): SCL 1. Órajel Impulzus',
            category: 'ADDRESS',
            signals: { SCL: 1, SDA: 1 },
            busVoltages: { SCL: 5.0, SDA: 5.0 },
            explanation: 'Master puts Bit 6 (Value=1 for 0x68) on SDA while SCL is LOW, then pulses SCL HIGH. All slaves sample SDA.',
            explanationHu: 'A Master a 6. bitet (1-es érték a 0x68 címből) kiteszi az SDA-ra miközben SCL=0, majd SCL=1-re vált a mintavételhez.',
            masterAction: 'Drive SDA = 1, Pulse SCL HIGH',
            masterActionHu: 'SDA = 1 beállítása, SCL magasba léptetése',
            slaveAction: 'Samples SDA = 1',
            slaveActionHu: 'Mintavételezi: SDA = 1',
            activeBytes: { txByte: 0x68, bitIndex: 6, byteName: 'Slave Address (0x68)' },
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 3,
            timeUs: 30,
            phaseName: 'Address Bits 5..0 + R/W Bit (0 = WRITE): SCL Pulses 2..8',
            phaseNameHu: 'Címbitek 5..0 + R/W Bit (0 = ÍRÁS): SCL 2..8 Órajelek',
            category: 'ADDRESS',
            signals: { SCL: 1, SDA: 0 },
            busVoltages: { SCL: 5.0, SDA: 0.1 },
            explanation: 'Master transmits remaining bits of 0x68 (0b1101000) followed by 8th bit R/W=0 (Master intends to write data into slave).',
            explanationHu: 'A Master elküldi a 0x68 (0b1101000) cím többi bitjét, végül a 8. bitként a R/W=0 értéket (Master írni kíván a szolga felé).',
            masterAction: 'Transmits bits 1,1,0,1,0,0,0 + W(0)',
            masterActionHu: 'Bitek kiküldése: 1,1,0,1,0,0,0 + W(0)',
            slaveAction: 'Address matching: DS3231 (0x68) detects match! Other slaves ignore.',
            slaveActionHu: 'Címillesztés: A DS3231 (0x68) egyezést talál! A többi szolga inaktívvá válik.',
            activeBytes: { txByte: 0xd0, bitIndex: 0, byteName: '0x68 << 1 | 0 (0xD0)' },
            highlightNode: 'SLAVE_1',
          },
          {
            stepIndex: 4,
            timeUs: 40,
            phaseName: 'Slave ACK on 9th Clock (DS3231 Pulls SDA LOW)',
            phaseNameHu: 'Szolga ACK a 9. Órajelre (A DS3231 lehúzza az SDA-t LOW-ra)',
            category: 'ACK',
            signals: { SCL: 1, SDA: 0 },
            busVoltages: { SCL: 5.0, SDA: 0.15 },
            explanation: 'Master releases SDA to HIGH. On the 9th SCL clock, the targeted slave (DS3231) actively pulls SDA LOW to acknowledge (ACK)!',
            explanationHu: 'A Master felengedi az SDA-t. A 9. SCL órajel alatt a megcímzett szolga (DS3231) lehúzza az SDA-t földre -> ACK (Nyugtázva)!',
            masterAction: 'Releases SDA, samples logic 0 -> ACK RECEIVED',
            masterActionHu: 'SDA felengedése, mintavételezés -> ACK SIKERES',
            slaveAction: 'Drive SDA = LOW (Assert ACK response)',
            slaveActionHu: 'SDA aktív lehúzása (ACK válasz kiadása)',
            highlightNode: 'SLAVE_1',
          },
          {
            stepIndex: 5,
            timeUs: 50,
            phaseName: 'Data Byte: Register Address 0x00 (Seconds) + Slave ACK',
            phaseNameHu: 'Adatbájt: 0x00 Regiszter Cím (Másodpercek) + Szolga ACK',
            category: 'DATA',
            signals: { SCL: 1, SDA: 0 },
            busVoltages: { SCL: 5.0, SDA: 0.1 },
            explanation: 'Master sends 8 data bits (0x00) pointing to the DS3231 internal seconds register. DS3231 acknowledges with a 2nd ACK.',
            explanationHu: 'A Master elküldi a 0x00 bájtot, ami a DS3231 belső másodperc-számláló regiszterére mutat. A szolga újra ACK-t ad.',
            masterAction: 'Transmits 0x00, reads ACK',
            masterActionHu: '0x00 kiküldése, szolga ACK fogadása',
            slaveAction: 'Updates internal register address pointer to 0x00',
            slaveActionHu: 'Belső regiszter mutató beállítása 0x00-ra',
            activeBytes: { txByte: 0x00, byteName: 'Reg Address 0x00' },
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 6,
            timeUs: 60,
            phaseName: 'STOP Condition (SDA goes HIGH while SCL is HIGH)',
            phaseNameHu: 'STOP Állapot (SDA felfut, miközben az SCL MAGAS)',
            category: 'STOP',
            signals: { SCL: 1, SDA: 1 },
            busVoltages: { SCL: 5.0, SDA: 5.0 },
            explanation: 'Master terminates communication: while SCL is held HIGH, Master releases SDA so it transitions from LOW to HIGH. Bus returns to IDLE.',
            explanationHu: 'A Master lezárja a tranzakciót: miközben az SCL MAGAS, az SDA alacsonyból magasba vált -> STOP állapot. A busz felszabadul.',
            masterAction: 'Releases SDA while SCL is HIGH (STOP assertion)',
            masterActionHu: 'SDA felengedése MAGAS SCL mellett (STOP állapot)',
            slaveAction: 'Completes transaction and stores received register byte',
            slaveActionHu: 'Lezárja a vételt és rögzíti a kapott adatokat',
            highlightNode: 'MASTER',
          },
        ],
      },
    ],
  },

  // ==========================================
  // 3. SPI (SERIAL PERIPHERAL INTERFACE)
  // ==========================================
  SPI: {
    id: 'SPI',
    name: 'SPI (Serial Peripheral Interface)',
    nameHu: 'SPI (Szinkron Soros Periféria Interfész)',
    shortDescription: 'High-speed, 4-wire synchronous full-duplex protocol using Master-In-Slave-Out and Master-Out-Slave-In shift registers.',
    shortDescriptionHu: 'Nagysebességű, 4-vezetékes szinkron full-duplex protokoll eltoló regiszterekkel (MOSI/MISO) és Chip Select (CS) lábbal.',
    inventor: 'Motorola',
    year: 1979,
    physicalLines: ['MOSI (Master Out Slave In)', 'MISO (Master In Slave Out)', 'SCK (Serial Clock)', 'CS/SS (Chip Select)'],
    topology: 'Full-Duplex Master-Slave',
    topologyHu: '4-vezetékes pont-pont vagy dedikált CS vonalas csillag/kaszkád topológia',
    signalingType: 'Single-Ended CMOS / TTL',
    signalingTypeHu: 'Push-Pull CMOS / TTL jelszintek (0V / 3.3V vagy 5V)',
    wireCount: 4, // MOSI, MISO, SCK, CS (+ VCC, GND)
    maxSpeed: '10 Mbps - 80+ Mbps (Very High Speed)',
    maxDistance: '~10 - 50 cm (Short distance on-board)',
    duplexMode: 'Full-Duplex',
    multiMaster: false,
    typicalTransceiver: 'Direct MCU Hardware SPI Controller (SPCR, SPSR, SPDR)',
    typicalApplications: [
      'nRF24L01+ 2.4GHz RF Transceivers',
      'SPI Flash Memories (W25Q64 64Mbit)',
      'ST7789 / ILI9341 Color TFT LCDs',
      'SD Cards (SPI Mode)',
    ],
    typicalApplicationsHu: [
      'nRF24L01+ 2.4GHz vezeték nélküli adó-vevők',
      'SPI Flash memória chipek (W25Q128 / Winbond)',
      'ST7789 és ILI9341 színes TFT LCD kijelzők',
      'SD kártyák SPI módú illesztése',
    ],
    color: '#10B981', // Emerald
    presets: [
      {
        id: 'spi-full-duplex-exchange',
        title: 'SPI Mode 0 Full-Duplex Byte Exchange (MOSI: 0x9F -> MISO: 0xEF)',
        titleHu: 'SPI Mód 0 Full-Duplex Bájtreszelés (MOSI: 0x9F -> MISO: 0xEF)',
        description: 'Demonstrates simultaneous 8-bit bidirectional shift register transfer under SPI Mode 0 (CPOL=0, CPHA=0) with CS pulled LOW.',
        descriptionHu: 'Szimultán 8-bites kétirányú adatcsere SPI Mód 0 (CPOL=0, CPHA=0) mellett aktív alacsony CS (Chip Select) vezérléssel.',
        defaultPayload: 'TX (MOSI): 0x9F (Read JEDEC ID), RX (MISO): 0xEF (Winbond ID)',
        baudRateKbps: 8000,
        steps: [
          {
            stepIndex: 0,
            timeUs: 0,
            phaseName: 'CS = HIGH (Slave Deselected, MISO High-Z)',
            phaseNameHu: 'CS = 1 (Szolga Inaktív, MISO lebeg / High-Z)',
            category: 'IDLE',
            signals: { CS: 1, SCK: 0, MOSI: 0, MISO: 0 },
            busVoltages: { CS: 5.0, SCK: 0.0, MOSI: 0.0, MISO: 2.5 },
            explanation: 'Chip Select (CS) is HIGH (inactive). The slave device disconnects its MISO driver, leaving the line in High-Impedance (tri-state).',
            explanationHu: 'A CS (Chip Select) MAGAS szinten inaktív. A szolga lekapcsolja a MISO kimenetét (nagyimpedanciás lebegő állapot).',
            masterAction: 'Holds CS = 1, SCK = 0 (CPOL=0 idle level)',
            masterActionHu: 'CS = 1 tartása, SCK = 0 (CPOL=0 alapértelmezett órajel)',
            slaveAction: 'MISO in tri-state (High-Z)',
            slaveActionHu: 'MISO vonal tri-state (High-Z) állapotban',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 1,
            timeUs: 1,
            phaseName: 'Chip Select Asserted (CS = LOW)',
            phaseNameHu: 'Chip Select Aktiválás (CS = 0)',
            category: 'START',
            signals: { CS: 0, SCK: 0, MOSI: 1, MISO: 1 },
            busVoltages: { CS: 0.0, SCK: 0.0, MOSI: 5.0, MISO: 5.0 },
            explanation: 'Master asserts CS to LOW. Slave wakes up, connects its output buffer to MISO, and loads its internal shift register.',
            explanationHu: 'A Master LOW (0V) szintre húzza a CS lábat. A szolga felébred, aktiválja MISO meghajtóját és betölti belső Shift regiszterét.',
            masterAction: 'Pulls CS = 0, prepares Bit 7 on MOSI (1 for 0x9F)',
            masterActionHu: 'CS = 0 lehúzása, 7. bit előkészítése a MOSI-n (1 a 0x9F-ből)',
            slaveAction: 'Enables MISO output driver, puts Bit 7 on MISO (1 for 0xEF)',
            slaveActionHu: 'Aktiválja a MISO kimenetet, kiteszi a 7. bitet (1 a 0xEF-ből)',
            highlightNode: 'SLAVE_1',
          },
          {
            stepIndex: 2,
            timeUs: 2,
            phaseName: 'Clock Edge 1 Rising: Bit 7 Sampled (MOSI=1, MISO=1)',
            phaseNameHu: '1. Felfutó Órajel Éle: 7. Bit Mintavételezés (MOSI=1, MISO=1)',
            category: 'DATA',
            signals: { CS: 0, SCK: 1, MOSI: 1, MISO: 1 },
            busVoltages: { CS: 0.0, SCK: 5.0, MOSI: 5.0, MISO: 5.0 },
            explanation: 'SCK rises HIGH. In Mode 0 (CPHA=0), both devices sample incoming data on the RISING edge: Master reads MISO=1, Slave reads MOSI=1.',
            explanationHu: 'SCK 5V-ra vált. Mód 0 (CPHA=0) esetén a FELFUTÓ élre mindkét fél mintát vesz: Master olvas MISO=1, Szolga olvas MOSI=1.',
            masterAction: 'Samples MISO -> Bit 7 = 1',
            masterActionHu: 'MISO mintavétel -> 7. bit = 1',
            slaveAction: 'Samples MOSI -> Bit 7 = 1',
            slaveActionHu: 'MOSI mintavétel -> 7. bit = 1',
            activeBytes: { txByte: 0x9f, rxByte: 0xef, bitIndex: 7, byteName: 'Bit 7 Exchange' },
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 3,
            timeUs: 3,
            phaseName: 'Clock Edge 1 Falling: Shift Next Bit (MOSI=0, MISO=1)',
            phaseNameHu: '1. Lefutó Órajel Éle: Következő Bit Léptetése (MOSI=0, MISO=1)',
            category: 'DATA',
            signals: { CS: 0, SCK: 0, MOSI: 0, MISO: 1 },
            busVoltages: { CS: 0.0, SCK: 0.0, MOSI: 0.0, MISO: 5.0 },
            explanation: 'SCK falls back to LOW. Both shift registers advance: Master shifts out Bit 6 (0), Slave shifts out Bit 6 (1).',
            explanationHu: 'SCK visszatér 0V-ra. A shift regiszterek léptetnek: Master kiadja a 6. bitet (0), Szolga kiadja a 6. bitet (1).',
            masterAction: 'Sets MOSI = 0 (Bit 6 of 0x9F)',
            masterActionHu: 'MOSI = 0 beállítása (0x9F 6. bitje)',
            slaveAction: 'Sets MISO = 1 (Bit 6 of 0xEF)',
            slaveActionHu: 'MISO = 1 beállítása (0xEF 6. bitje)',
            activeBytes: { txByte: 0x9f, rxByte: 0xef, bitIndex: 6, byteName: 'Bit 6 Setup' },
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 4,
            timeUs: 8,
            phaseName: '8 Clock Cycles Complete: Full Byte Swapped',
            phaseNameHu: '8 Órajel Ciklus Kész: Teljes Bájt Kicserélve',
            category: 'DATA',
            signals: { CS: 0, SCK: 0, MOSI: 1, MISO: 1 },
            busVoltages: { CS: 0.0, SCK: 0.0, MOSI: 5.0, MISO: 5.0 },
            explanation: 'After 8 clock pulses, Master has transferred 0x9F to Slave, and simultaneously received 0xEF from Slave inside SPDR register!',
            explanationHu: '8 órajelciklus alatt a Master elküldte a 0x9F bájtot, és pontosan egyidejűleg fogadta a 0xEF bájtot az SPDR regiszterébe!',
            masterAction: 'Stores received byte 0xEF in SPDR register; sets SPIF flag',
            masterActionHu: '0xEF elmentése az SPDR-be; SPIF megszakításjelző bit beállítása',
            slaveAction: 'Executes JEDEC ID command (0x9F); prepares next response byte',
            slaveActionHu: 'Feldolgozza a 0x9F parancsot; előkészíti a következő azonosító bájtot',
            activeBytes: { txByte: 0x9f, rxByte: 0xef, byteName: 'Full-Duplex Result' },
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 5,
            timeUs: 9,
            phaseName: 'CS De-asserted (CS = HIGH)',
            phaseNameHu: 'CS Felengedése (CS = 1, Vége)',
            category: 'STOP',
            signals: { CS: 1, SCK: 0, MOSI: 0, MISO: 0 },
            busVoltages: { CS: 5.0, SCK: 0.0, MOSI: 0.0, MISO: 2.5 },
            explanation: 'Master brings CS back to HIGH. Slave returns to idle and releases MISO to High-Z.',
            explanationHu: 'A Master a CS vonalat visszahúzza 5V-ra. A szolga inaktívvá válik, MISO vonala újra lebeg (High-Z).',
            masterAction: 'Sets CS = 1 (Transaction finished)',
            masterActionHu: 'CS = 1 beállítása (Tranzakció befejezve)',
            slaveAction: 'Disconnects MISO driver',
            slaveActionHu: 'Lekapcsolja a MISO kimenetet',
            highlightNode: 'BUS',
          },
        ],
      },
    ],
  },

  // ==========================================
  // 4. CAN BUS (CONTROLLER AREA NETWORK)
  // ==========================================
  CAN: {
    id: 'CAN',
    name: 'CAN Bus (ISO 11898)',
    nameHu: 'CAN Busz (Gépjármű és Ipari Hálózat)',
    shortDescription: 'Robust differential multi-master fieldbus with non-destructive bitwise arbitration, 120Ω termination, and hardware CRC.',
    shortDescriptionHu: 'Nagy megbízhatóságú differenciális busz roncsolásmentes arbitrációval (CAN_H / CAN_L), 120Ω lezárással és hardveres CRC-vel.',
    inventor: 'Robert Bosch GmbH',
    year: 1986,
    physicalLines: ['CAN_H (CAN High)', 'CAN_L (CAN Low)', 'Shield / GND'],
    topology: 'Differential Multi-Master',
    topologyHu: 'Differenciális sodrott érpár (Twisted Pair) 120Ω véglezárásokkal mindkét végén',
    signalingType: 'Differential Voltage (CAN_H - CAN_L)',
    signalingTypeHu: 'Differenciális: Domináns 0 (ΔV=2.0V) vs Recesszív 1 (ΔV=0.0V)',
    wireCount: 2, // CAN_H, CAN_L
    maxSpeed: '1 Mbps (CAN 2.0B) / 5-8 Mbps (CAN FD)',
    maxDistance: '~40 m @ 1 Mbps / ~1000 m @ 50 kbps',
    duplexMode: 'Half-Duplex',
    multiMaster: true,
    typicalTransceiver: 'MCP2551 / TJA1050 / SN65HVD230 (Connected to MCP2515 / CAN Controller)',
    typicalApplications: [
      'Automotive ECUs (Engine, ABS, Airbag, BCM, Dashboard)',
      'OBD-II Vehicle Diagnostics',
      'Industrial Automation & Robotics (CANopen / DeviceNet)',
      'Aerospace and Drone Avionics (UAVCAN / DroneCAN)',
    ],
    typicalApplicationsHu: [
      'Gépjármű vezérlőegységek (Motorvezérlő, ABS, Légzsák, Műszerfal)',
      'OBD-II gépjármű diagnosztikai interfész',
      'Ipari robotika és gyártósori automatizálás (CANopen)',
      'Repülőgép és drón fedélzeti rendszerek (DroneCAN)',
    ],
    color: '#F59E0B', // Amber
    presets: [
      {
        id: 'can-arbitration-frame',
        title: 'CAN 2.0A Frame & Non-Destructive Arbitration (ID 0x120 vs ID 0x128)',
        titleHu: 'CAN 2.0A Keret & Roncsolásmentes Arbitráció (ID 0x120 vs 0x128)',
        description: 'Demonstrates CAN differential signaling (Dominant 0 vs Recessive 1), Bit Stuffing, Collision Arbitration where higher priority node wins without corrupted data.',
        descriptionHu: 'CAN differenciális szintek (Domináns 0 vs Recesszív 1), Bit Stuffing, és arbitráció, ahol a magasabb prioritású Node 1 nyer adatvesztés nélkül.',
        defaultPayload: 'ID: 0x120, DLC: 2, DATA: [0x41, 0x58]',
        baudRateKbps: 500,
        steps: [
          {
            stepIndex: 0,
            timeUs: 0,
            phaseName: 'Bus Idle (Recessive: CAN_H = 2.5V, CAN_L = 2.5V, ΔV = 0.0V)',
            phaseNameHu: 'Busz Alapállapot (Recesszív: CAN_H = 2.5V, CAN_L = 2.5V, ΔV = 0.0V)',
            category: 'IDLE',
            signals: { CAN_H: 1, CAN_L: 1, DIFF: 0 },
            busVoltages: { CAN_H: 2.5, CAN_L: 2.5, DIFF: 0.0 },
            explanation: 'When no node is transmitting, 120Ω termination resistors keep both CAN_H and CAN_L at nominal 2.5V (Differential voltage ΔV = 0.0V = Logic 1 / Recessive).',
            explanationHu: 'Amikor egyetlen csomópont sem ad, a 120Ω-os lezáró ellenállások mindkét vonalat 2.5V-on tartják (ΔV = 0.0V = Logikai 1 / Recesszív).',
            masterAction: 'Listening (Transceiver in Receiver Mode)',
            masterActionHu: 'Figyelés (Adó-vevő Vevő módban)',
            slaveAction: 'Listening',
            slaveActionHu: 'Figyelés',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 1,
            timeUs: 2,
            phaseName: 'Start of Frame (SOF): Dominant 0 (CAN_H=3.5V, CAN_L=1.5V, ΔV=2.0V)',
            phaseNameHu: 'Keret Kezdete (SOF): Domináns 0 (CAN_H=3.5V, CAN_L=1.5V, ΔV=2.0V)',
            category: 'START',
            signals: { CAN_H: 1, CAN_L: 0, DIFF: 1 },
            busVoltages: { CAN_H: 3.5, CAN_L: 1.5, DIFF: 2.0 },
            explanation: 'Node 1 transmits SOF by driving CAN_H to 3.5V and CAN_L to 1.5V. The resulting 2.0V differential voltage creates a DOMINANT 0 that overrides recessive state!',
            explanationHu: 'A Node 1 a CAN_H-t 3.5V-ra, a CAN_L-t 1.5V-ra húzza. A keletkező 2.0V differenciális feszültség DOMINÁNS 0 szintet hoz létre!',
            masterAction: 'Drives Dominant 0 (SOF bit)',
            masterActionHu: 'Domináns 0 kiadása (SOF bit)',
            slaveAction: 'Synchronizes bit clock on dominant falling edge',
            slaveActionHu: 'Szinkronizálja a belső órajelét a lefutó élhez',
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 2,
            timeUs: 4,
            phaseName: 'Identifier Arbitration: Node 1 (0x120) vs Node 2 (0x128)',
            phaseNameHu: 'Azonosító Arbitráció: Node 1 (0x120) vs Node 2 (0x128)',
            category: 'ARBITRATION',
            signals: { CAN_H: 1, CAN_L: 0, DIFF: 1 },
            busVoltages: { CAN_H: 3.5, CAN_L: 1.5, DIFF: 2.0 },
            explanation: 'Both nodes transmit IDs bit-by-bit. At bit 3, Node 1 sends Dominant 0 while Node 2 sends Recessive 1. Dominant 0 wins on the bus! Node 2 immediately switches to receiver without corrupting frame.',
            explanationHu: 'Mindkét node egyszerre adja az ID bitjeit. A 3. bitnél a Node 1 domináns 0-t ad, a Node 2 recesszív 1-et. A domináns 0 győz! A Node 2 visszalép vevő módba adatvesztés nélkül.',
            masterAction: 'Sends Dominant 0 -> Wins bus priority!',
            masterActionHu: 'Domináns 0-t ad -> Megnyeri az arbitrációt!',
            slaveAction: 'Senses Dominant 0 while transmitting Recessive 1 -> Loses arbitration, becomes listener',
            slaveActionHu: 'Recesszív 1 helyett Domináns 0-t érzékel -> Elveszíti az arbitrációt, átvált hallgató módba',
            activeBytes: { txByte: 0x120, byteName: 'Arbitration Winner: 0x120' },
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 3,
            timeUs: 14,
            phaseName: 'Control Field (RTR=0 Data, IDE=0 Standard 11-bit, DLC=2 Bytes)',
            phaseNameHu: 'Vezérlőmező (RTR=0 Adat, IDE=0 Standard 11-bit, DLC=2 Bájt)',
            category: 'ADDRESS',
            signals: { CAN_H: 1, CAN_L: 0, DIFF: 1 },
            busVoltages: { CAN_H: 3.5, CAN_L: 1.5, DIFF: 2.0 },
            explanation: 'Node 1 sends Data Length Code (DLC = 2). Receivers prepare to receive exactly 2 data payload bytes.',
            explanationHu: 'A Node 1 kiküldi a DLC adatbájtok számát (2 bájt). A vevők felkészülnek pontosan 2 adatbájt fogadására.',
            masterAction: 'Transmits RTR=0, IDE=0, DLC=0010 (2 Bytes)',
            masterActionHu: 'RTR=0, IDE=0, DLC=0010 (2 Bájt) kiküldése',
            slaveAction: 'Allocates buffer for 2 payload bytes',
            slaveActionHu: 'Puffert foglal 2 adatbájt számára',
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 4,
            timeUs: 20,
            phaseName: 'Data Payload: 0x41 (\'A\') and 0x58 (\'X\')',
            phaseNameHu: 'Adatmező: 0x41 (\'A\') és 0x58 (\'X\')',
            category: 'DATA',
            signals: { CAN_H: 1, CAN_L: 0, DIFF: 1 },
            busVoltages: { CAN_H: 3.5, CAN_L: 1.5, DIFF: 2.0 },
            explanation: '16 payload data bits are transmitted sequentially with automatic hardware bit-stuffing (opposite polarity bit inserted after 5 consecutive identical bits).',
            explanationHu: '16 adatbit kerül átvitelre automatikus bit-stuffinggal (5 azonos bit után automatikusan 1 ellentétes beszúrt bit védi a szinkront).',
            masterAction: 'Shifts out payload bytes 0x41 0x58',
            masterActionHu: 'Kiküldi a 0x41 0x58 bájtokat',
            slaveAction: 'Stores payload bytes into receive FIFO',
            slaveActionHu: 'Vételi FIFO pufferbe másolja az adatbájtokat',
            activeBytes: { txByte: 0x41, byteName: 'Payload Byte 1' },
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 5,
            timeUs: 32,
            phaseName: '15-Bit Hardware CRC Field & CRC Delimiter',
            phaseNameHu: '15-Bites Hardveres CRC Ellenőrző Mező',
            category: 'CRC',
            signals: { CAN_H: 1, CAN_L: 1, DIFF: 0 },
            busVoltages: { CAN_H: 2.5, CAN_L: 2.5, DIFF: 0.0 },
            explanation: 'Transmitter outputs 15-bit Cyclic Redundancy Checksum. All receiving nodes verify the checksum locally.',
            explanationHu: 'Az adó kiküldi a 15-bites CRC ellenőrző összeget. Minden vevő ellenőrzi a helyességet.',
            masterAction: 'Transmits calculated CRC-15',
            masterActionHu: 'Kiszámított CRC-15 ellenőrzőösszeg kiküldése',
            slaveAction: 'Calculates CRC: MATCH CONFIRMED (No bit errors)',
            slaveActionHu: 'Helyi CRC számítás: EGYEZIK (Hibátlan adat)',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 6,
            timeUs: 35,
            phaseName: 'ACK Slot: All Receivers Assert Dominant 0',
            phaseNameHu: 'ACK Időrés: Minden Vevő Domináns 0-t Ad',
            category: 'ACK',
            signals: { CAN_H: 1, CAN_L: 0, DIFF: 1 },
            busVoltages: { CAN_H: 3.5, CAN_L: 1.5, DIFF: 2.0 },
            explanation: 'Transmitter sends Recessive 1 during ACK slot. All receivers that correctly verified the CRC drive the bus DOMINANT 0 simultaneously!',
            explanationHu: 'Az adó recesszív 1-et ad az ACK résben. Minden vevő, amely sikeresen ellenőrizte a CRC-t, egyszerre húzza domináns 0-ra a buszt!',
            masterAction: 'Transmits Recessive 1; reads back Dominant 0 -> ACK SUCCESS!',
            masterActionHu: 'Recesszív 1-et ad; Domináns 0-t olvas vissza -> SIKERES NYUGTÁZÁS!',
            slaveAction: 'Drives Dominant 0 (ACK confirmation)',
            slaveActionHu: 'Domináns 0 kiadása (ACK visszaigazolás)',
            highlightNode: 'SLAVE_1',
          },
          {
            stepIndex: 7,
            timeUs: 38,
            phaseName: 'End of Frame (EOF: 7 Recessive Bits)',
            phaseNameHu: 'Keret Vége (EOF: 7 Recesszív Bit)',
            category: 'STOP',
            signals: { CAN_H: 1, CAN_L: 1, DIFF: 0 },
            busVoltages: { CAN_H: 2.5, CAN_L: 2.5, DIFF: 0.0 },
            explanation: '7 continuous recessive bits mark the end of the frame. The bus returns to idle state.',
            explanationHu: '7 egymást követő recesszív bit jelzi a keret végét. A busz visszatér alaphelyzetbe.',
            masterAction: 'Frame complete; frees bus controller',
            masterActionHu: 'Keret sikeresen elküldve; busz felszabadítva',
            slaveAction: 'Passes verified frame to application layer interrupt',
            slaveActionHu: 'A hitelesített csomagot átadja az alkalmazás rétegnek',
            highlightNode: 'BUS',
          },
        ],
      },
    ],
  },

  // ==========================================
  // 5. RS-485 (TIA/EIA-485)
  // ==========================================
  RS485: {
    id: 'RS485',
    name: 'RS-485 (TIA/EIA-485-A)',
    nameHu: 'RS-485 Ipari Differenciális Busz',
    shortDescription: 'Industrial differential half-duplex multi-drop bus with high common-mode noise immunity and up to 1200m range.',
    shortDescriptionHu: 'Ipari kétvezetékes differenciális fél-duplex multi-drop busz nagy zavarvédettséggel és akár 1200 méteres hatótávval.',
    inventor: 'Telecommunications Industry Association (TIA)',
    year: 1983,
    physicalLines: ['A / Data+ (Non-Inverting)', 'B / Data- (Inverting)', 'GND / Shield'],
    topology: 'Differential Half-Duplex',
    topologyHu: 'Differenciális multi-drop lánc (akár 32 / 128 eszköz) 120Ω véglezárásokkal',
    signalingType: 'Differential Voltage (A - B)',
    signalingTypeHu: 'Differenciális: VA - VB > +200mV (Mark/1) vagy VA - VB < -200mV (Space/0)',
    wireCount: 2, // A, B (+ GND)
    maxSpeed: '10 Mbps (@ 12m) / 100 kbps (@ 1200m)',
    maxDistance: '~1200 m (4000 ft)',
    duplexMode: 'Half-Duplex',
    multiMaster: false,
    typicalTransceiver: 'MAX485 / SN75176 / ADM485 / SP3485 (Controlled by MCU UART TX/RX + DE pin)',
    typicalApplications: [
      'Modbus RTU Industrial Fieldbus',
      'DMX512 Stage Lighting Control',
      'HVAC Building Automation (BACnet MS/TP)',
      'Security Access & Security Camera PTZ (Pelco-D)',
    ],
    typicalApplicationsHu: [
      'Modbus RTU ipari terepibusz kommunikáció',
      'DMX512 színpadi világítás- és fényvezérlés',
      'Épületautomatizálás és HVAC rendszerek (BACnet)',
      'Biztonságtechnika és PTZ kameravezérlés (Pelco-D)',
    ],
    color: '#EC4899', // Pink
    presets: [
      {
        id: 'rs485-modbus-frame',
        title: 'RS-485 Half-Duplex Byte Transmission with DE (Driver Enable)',
        titleHu: 'RS-485 Fél-Duplex Bájtátvitel DE (Driver Enable) Vezérléssel',
        description: 'Demonstrates Driver Enable (DE=1) assertion, differential A/B line polarities (VA - VB), UART framing (Start, 8-bit, Stop), and transceiver tri-state release.',
        descriptionHu: 'Driver Enable (DE=1) engedélyezés, differenciális A és B vonalfeszültségek, UART keretezés (Start, 8 adatbit, Stop) és Tri-State lebegtetés.',
        defaultPayload: '0x01 (Modbus Slave Addr) + 0x03 (Read Holding Registers)',
        baudRateKbps: 9.6,
        steps: [
          {
            stepIndex: 0,
            timeUs: 0,
            phaseName: 'Bus Idle & Tri-State (DE = 0 Receiver Mode, Fail-Safe Bias)',
            phaseNameHu: 'Busz Alapállapot & Tri-State (DE = 0 Vevő Mód, Fail-Safe Előfeszítés)',
            category: 'IDLE',
            signals: { DE: 0, A: 1, B: 0, DIFF: 1 },
            busVoltages: { DE: 0.0, A: 2.7, B: 2.3, DIFF: 0.4 },
            explanation: 'Transceiver Driver Enable (DE) is LOW (0V). Line driver is in high-impedance (tri-state). Fail-safe bias resistors hold VA - VB > +200mV (Logic 1 / Mark).',
            explanationHu: 'A MAX485 Driver Enable (DE) lába 0V-on van (Adó lekapcsolva, vevő aktív). A vonalat az előfeszítés VA > VB (Mark/1) állapotban tartja.',
            masterAction: 'DE = 0 (Listening / Tri-State)',
            masterActionHu: 'DE = 0 (Hallgató mód / Tri-State lebegés)',
            slaveAction: 'DE = 0 (Listening)',
            slaveActionHu: 'DE = 0 (Hallgató mód)',
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 1,
            timeUs: 10,
            phaseName: 'Master Asserts DE = 1 (Driver Enabled)',
            phaseNameHu: 'Master DE = 1 Aktiválás (Adómeghajtó Bekapcsolása)',
            category: 'START',
            signals: { DE: 1, A: 1, B: 0, DIFF: 1 },
            busVoltages: { DE: 5.0, A: 3.8, B: 1.2, DIFF: 2.6 },
            explanation: 'Master MCU drives GPIO pin HIGH to enable the RS-485 transceiver output driver (DE = 1, /RE = 1).',
            explanationHu: 'A Master mikrokontroller HIGH szintre billenti a DE lábat: a MAX485 meghajtó aktívvá válik és átveszi a vonal vezérlését.',
            masterAction: 'Asserts DE = 1; takes control of differential bus',
            masterActionHu: 'DE = 1 beállítása; differenciális busz meghajtásának átvétele',
            slaveAction: 'Receiver senses line driven to active Mark state',
            slaveActionHu: 'A szolga érzékeli az aktív meghajtott Mark állapotot',
            highlightNode: 'MASTER',
          },
          {
            stepIndex: 2,
            timeUs: 20,
            phaseName: 'UART START Bit (Space: VA < VB, A=1.2V, B=3.8V, ΔV=-2.6V)',
            phaseNameHu: 'UART START Bit (Space: VA < VB, A=1.2V, B=3.8V, ΔV=-2.6V)',
            category: 'START',
            signals: { DE: 1, A: 0, B: 1, DIFF: 0 },
            busVoltages: { DE: 5.0, A: 1.2, B: 3.8, DIFF: -2.6 },
            explanation: 'Master UART transmits START bit (Logic 0 / Space). The transceiver inverts differential polarity: Line A drops to 1.2V, Line B rises to 3.8V (ΔV = -2.6V < -200mV).',
            explanationHu: 'A Master UART START bitet (Logikai 0 / Space) ad ki. A MAX485 megfordítja a polaritást: A=1.2V, B=3.8V (ΔV = -2.6V < -200mV).',
            masterAction: 'UART TX = 0 -> Drives Line A < Line B',
            masterActionHu: 'UART TX = 0 -> A vonal < B vonal meghajtása',
            slaveAction: 'Receiver detects differential polarity flip -> START bit confirmed',
            slaveActionHu: 'A differenciális komparátor érzékeli a polaritáscserét -> START bit regisztrálva',
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 3,
            timeUs: 40,
            phaseName: 'Data Bits 0..7 (Modbus Slave ID = 0x01: LSB First)',
            phaseNameHu: 'Adatbitek 0..7 (Modbus Szolga Cím = 0x01: LSB-First)',
            category: 'DATA',
            signals: { DE: 1, A: 1, B: 0, DIFF: 1 },
            busVoltages: { DE: 5.0, A: 3.8, B: 1.2, DIFF: 2.6 },
            explanation: '8 data bits (0b00000001) are transmitted LSB-first. Any common-mode noise coupled into the twisted pair equally affects both A and B, canceling out completely!',
            explanationHu: '8 adatbit (0x01) kerül átvitelre LSB-first sorrendben. A sodrott érpárba jutó külső elektromágneses zaj mindkét eret azonosan éri, így a különbségképzés kiejti a zajt!',
            masterAction: 'Transmits bit sequence: 1, 0, 0, 0, 0, 0, 0, 0',
            masterActionHu: 'Bitminta kiküldése: 1, 0, 0, 0, 0, 0, 0, 0',
            slaveAction: 'Samples differential voltage at middle of bit times',
            slaveActionHu: 'A bitidők közepén mintavételezi a differenciális feszültséget',
            activeBytes: { txByte: 0x01, byteName: 'Slave Address 0x01' },
            highlightNode: 'BUS',
          },
          {
            stepIndex: 4,
            timeUs: 120,
            phaseName: 'STOP Bit (Mark: VA > VB) & Release DE = 0',
            phaseNameHu: 'STOP Bit (Mark: VA > VB) & DE = 0 Felengedése',
            category: 'STOP',
            signals: { DE: 0, A: 1, B: 0, DIFF: 1 },
            busVoltages: { DE: 0.0, A: 2.7, B: 2.3, DIFF: 0.4 },
            explanation: 'Master transmits STOP bit (Logic 1), waits for UART shift register empty (TXC), then immediately drops DE = 0 so other slaves can respond on the shared pair.',
            explanationHu: 'A Master kiadja a STOP bitet (Logikai 1), megvárja az utolsó bit kifutását (TXC), majd azonnal DE = 0-ra vált, felszabadítva a vonalat a válasznak.',
            masterAction: 'Waits for TX Complete -> Sets DE = 0 (Switches to Receiver)',
            masterActionHu: 'Megvárja a TX Complete állapotot -> DE = 0-ra állítja (Vevőre vált)',
            slaveAction: 'Decodes Modbus Address 0x01; prepares response packet',
            slaveActionHu: 'Dekódolja a 0x01-es címet; előkészíti a válaszcsomagot',
            highlightNode: 'SLAVE_1',
          },
        ],
      },
    ],
  },

  // ==========================================
  // 6. RS-422 (TIA/EIA-422-B)
  // ==========================================
  RS422: {
    id: 'RS422',
    name: 'RS-422 (TIA/EIA-422-B)',
    nameHu: 'RS-422 Full-Duplex Differenciális Vonal',
    shortDescription: 'Differential 4-wire full-duplex point-to-multipoint standard designed for high-speed noise-immune long-range communications.',
    shortDescriptionHu: '4-vezetékes differenciális full-duplex pont-multipont szabvány nagy sebességű, zajvédett, hosszú távú adatátvitelre.',
    inventor: 'Telecommunications Industry Association (TIA)',
    year: 1975,
    physicalLines: ['TX+ / TX-', 'RX+ / RX-', 'GND / Shield'],
    topology: 'Differential Full-Duplex',
    topologyHu: '4-vezetékes differenciális dedikált TX és RX érpárok (Master -> Slave-ek adás, visszirányú vétel)',
    signalingType: 'Differential Voltage (A - B)',
    signalingTypeHu: 'Differenciális feszültség: V(TX+) - V(TX-) és V(RX+) - V(RX-)',
    wireCount: 4, // TX+, TX-, RX+, RX- (+ GND)
    maxSpeed: '10 Mbps (@ 12m) / 100 kbps (@ 1200m)',
    maxDistance: '~1200 m (4000 ft)',
    duplexMode: 'Full-Duplex',
    multiMaster: false,
    typicalTransceiver: 'MAX490 / MAX488 / SN75179 (Full-Duplex RS-422 Driver/Receiver)',
    typicalApplications: [
      'Broadcast Video & Audio Equipment Control (Sony 9-Pin Protocol)',
      'NMEA 0183 Marine Navigation & GPS Equipment',
      'Industrial CNC & Motion Control Encoders',
      'Telecom Base Station Control Links',
    ],
    typicalApplicationsHu: [
      'Stúdiótechnikai videó és audiomagnó vezérlés (Sony 9-Pin protokoll)',
      'NMEA 0183 hajózási és tengeri GPS navigáció',
      'Ipari CNC vezérlők és inkrementális útmérők',
      'Távközlési bázisállomások vezérlőkapcsolatai',
    ],
    color: '#3B82F6', // Blue
    presets: [
      {
        id: 'rs422-full-duplex-stream',
        title: 'RS-422 Simultaneous Bidirectional Full-Duplex Transmission',
        titleHu: 'RS-422 Szimultán Kétirányú Full-Duplex Adatátvitel',
        description: 'Demonstrates simultaneous differential transmission on independent TX (TX+/TX-) and RX (RX+/RX-) pairs without direction switching.',
        descriptionHu: 'Egyidejű differenciális adás és vétel független TX+/TX- és RX+/RX- érpárokon irányváltás (DE láb) nélkül.',
        defaultPayload: 'Master TX: "CMD:STATUS", Slave RX: "ACK:READY"',
        baudRateKbps: 115.2,
        steps: [
          {
            stepIndex: 0,
            timeUs: 0,
            phaseName: 'Both Differential Channels Idle (TX+ > TX- and RX+ > RX-)',
            phaseNameHu: 'Mindkét Differenciális Csatorna Alapállapotban (TX+ > TX- és RX+ > RX-)',
            category: 'IDLE',
            signals: { 'TX+': 1, 'TX-': 0, 'RX+': 1, 'RX-': 0 },
            busVoltages: { 'TX+': 3.8, 'TX-': 1.2, 'RX+': 3.8, 'RX-': 1.2 },
            explanation: 'Both dedicated TX and RX pairs are permanently driven in Mark state (Logic 1). No direction switching or line turnaround delay is required.',
            explanationHu: 'Mind a dedikált TX, mind az RX érpár állandóan Mark (Logikai 1) állapotban van meghajtva. Nincs szükség irányváltási késleltetésre.',
            masterAction: 'TX Pair = Mark (1), RX Pair = Listening',
            masterActionHu: 'TX érpár = Mark (1), RX érpár = Hallgató mód',
            slaveAction: 'TX Pair = Mark (1), RX Pair = Listening',
            slaveActionHu: 'TX érpár = Mark (1), RX érpár = Hallgató mód',
            highlightNode: 'BUS',
          },
          {
            stepIndex: 1,
            timeUs: 5,
            phaseName: 'Simultaneous START Bits (TX: Space, RX: Space)',
            phaseNameHu: 'Egyidejű START Bitek (TX: Space, RX: Space)',
            category: 'START',
            signals: { 'TX+': 0, 'TX-': 1, 'RX+': 0, 'RX-': 1 },
            busVoltages: { 'TX+': 1.2, 'TX-': 3.8, 'RX+': 1.2, 'RX-': 3.8 },
            explanation: 'Master transmits command START bit on TX pair while Slave simultaneously transmits status telemetry START bit on RX pair.',
            explanationHu: 'A Master parancsot küld a TX érpáron, miközben a Szolga pontosan egyidejűleg telemetriát küld vissza az RX érpáron.',
            masterAction: 'Transmits START bit on TX pair (TX+ < TX-)',
            masterActionHu: 'START bit kiadása a TX érpáron (TX+ < TX-)',
            slaveAction: 'Transmits START bit on RX pair (RX+ < RX-)',
            slaveActionHu: 'START bit kiadása az RX érpáron (RX+ < RX-)',
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 2,
            timeUs: 15,
            phaseName: 'Full-Duplex Data Streaming (Zero Collision / Dedicated Pairs)',
            phaseNameHu: 'Full-Duplex Adatfolyam (Zéró Ütközés / Független Érpárok)',
            category: 'DATA',
            signals: { 'TX+': 1, 'TX-': 0, 'RX+': 1, 'RX-': 0 },
            busVoltages: { 'TX+': 3.8, 'TX-': 1.2, 'RX+': 3.8, 'RX-': 1.2 },
            explanation: 'Data flows concurrently in both directions at maximum baud rate over kilometers of cable thanks to differential CMRR (Common Mode Rejection Ratio).',
            explanationHu: 'Az adatok szimultán mindkét irányban maximális sebességgel áramlanak akár több kilométeren át a differenciális zajkioltásnak köszönhetően.',
            masterAction: 'Streams command bytes to slave',
            masterActionHu: 'Parancsbájtok folyamatos adása a szolga felé',
            slaveAction: 'Streams response data to master',
            slaveActionHu: 'Válaszadatok folyamatos adása a master felé',
            activeBytes: { txByte: 0x53, rxByte: 0x4f, byteName: 'Full-Duplex Stream' },
            highlightNode: 'BUS',
          },
        ],
      },
    ],
  },

  // ==========================================
  // 7. RS-232 (EIA/TIA-232)
  // ==========================================
  RS232: {
    id: 'RS232',
    name: 'RS-232 (EIA/TIA-232-F)',
    nameHu: 'RS-232 Klasszikus Soros Port (COM)',
    shortDescription: 'Classic point-to-point bipolar voltage standard (±3V to ±15V) with hardware flow control handshaking lines.',
    shortDescriptionHu: 'Klasszikus pont-pont bipoláris feszültségű szabvány (±12V / ±5V) hardveres kézfogásos (RTS/CTS) vonalakkal.',
    inventor: 'Electronic Industries Association (EIA)',
    year: 1960,
    physicalLines: ['TXD (Transmit Data)', 'RXD (Receive Data)', 'RTS (Request to Send)', 'CTS (Clear to Send)', 'GND'],
    topology: 'Single-Ended Bipolar Point-to-Point',
    topologyHu: 'Egyvégű pont-pont összeköttetés (DTE - DCE terminál kapcsolat)',
    signalingType: 'Single-Ended Inverted Bipolar (±12V)',
    signalingTypeHu: 'Invertált Bipoláris: Logikai 0 = +12V (Space), Logikai 1 = -12V (Mark)',
    wireCount: 3, // TXD, RXD, GND (or 9 with full DB9 handshake)
    maxSpeed: '115.2 kbps (Standard) / up to 1 Mbps with modern drivers',
    maxDistance: '~15 m (50 ft)',
    duplexMode: 'Full-Duplex',
    multiMaster: false,
    typicalTransceiver: 'MAX232 / MAX3232 (Charge pump DC-DC step up from +5V to ±10V)',
    typicalApplications: [
      'PC COM Ports & Serial Terminals (VT100, PuTTY)',
      'Router / Switch Console Debugging Ports',
      'Industrial Barcode Scanners & Scales',
      'Modem / Satellite Transceiver Links',
    ],
    typicalApplicationsHu: [
      'PC COM portok és soros terminálok (PuTTY, TeraTerm)',
      'Hálózati routerek és switchek konzol portjai',
      'Ipari vonalkódolvasók, mérlegek és kijelzők',
      'Modemek és műholdas adó-vevők',
    ],
    color: '#6366F1', // Indigo
    presets: [
      {
        id: 'rs232-ascii-frame',
        title: 'RS-232 Bipolar Frame: Character \'M\' (0x4D) with MAX232 Charge Pump',
        titleHu: 'RS-232 Bipoláris Keret: \'M\' Karakter (0x4D) és MAX232 Töltéspumpa',
        description: 'Demonstrates inverted bipolar voltages (Logic 0 = +12V "Space", Logic 1 = -12V "Mark"), MAX232 level translation from TTL 0-5V, and 8-N-1 UART framing.',
        descriptionHu: 'Invertált bipoláris szintek (Logikai 0 = +12V "Space", Logikai 1 = -12V "Mark"), MAX232 szintillesztés TTL 5V-ról és 8-N-1 UART keret.',
        defaultPayload: 'ASCII Character \'M\' (0x4D = 0b01001101)',
        baudRateKbps: 9.6,
        steps: [
          {
            stepIndex: 0,
            timeUs: 0,
            phaseName: 'Line Idle: Mark State (-12V Bipolar / TTL 5V)',
            phaseNameHu: 'Vonal Alapállapot: Mark Szint (-12V Bipoláris / TTL 5V)',
            category: 'IDLE',
            signals: { 'TTL_TX': 1, 'RS232_TX': 1 },
            busVoltages: { 'TTL_TX': 5.0, 'RS232_TX': -12.0 },
            explanation: 'INVERTED BIPOLAR RULE: Logic 1 ("Mark") is represented by negative voltage (-3V to -15V, typically -12V). The TTL input is at +5V.',
            explanationHu: 'INVERTÁLT BIPOLÁRIS SZABÁLY: A logikai 1 ("Mark") negatív feszültség (-3V .. -15V, tipikusan -12V). A mikrokontroller TTL lábán ez +5V.',
            masterAction: 'MCU UART TX = 5V -> MAX232 outputs -12V to RS-232 cable',
            masterActionHu: 'MCU UART TX = 5V -> A MAX232 -12V-ot ad ki a kábelre',
            slaveAction: 'Receiver detects negative voltage -> Senses idle line',
            slaveActionHu: 'A vevő negatív feszültséget lát -> Alapállapotot érzékel',
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 1,
            timeUs: 104,
            phaseName: 'START Bit: Space State (+12V Bipolar / TTL 0V)',
            phaseNameHu: 'START Bit: Space Szint (+12V Bipoláris / TTL 0V)',
            category: 'START',
            signals: { 'TTL_TX': 0, 'RS232_TX': 0 },
            busVoltages: { 'TTL_TX': 0.0, 'RS232_TX': +12.0 },
            explanation: 'To signal START, MCU drops TTL to 0V. The MAX232 charge pump drives the RS-232 line positive to +12V ("Space"). Receiver triggers on positive edge.',
            explanationHu: 'A START bithez az MCU TTL 0V-ra vált. A MAX232 töltéspumpája a kábelt pozitív +12V-ra ("Space") emeli. A vevő a pozitív élre szinkronizál.',
            masterAction: 'MCU TX = 0V -> MAX232 outputs +12V (START bit)',
            masterActionHu: 'MCU TX = 0V -> MAX232 +12V-ot ad ki (START bit)',
            slaveAction: 'Receiver detects transition from -12V to +12V -> Starts baud timer',
            slaveActionHu: 'A vevő érzékeli a -12V -> +12V váltást -> Elindítja a belső időzítőt',
            highlightNode: 'TRANSCEIVER',
          },
          {
            stepIndex: 2,
            timeUs: 208,
            phaseName: 'Data Bit 0 (1 = -12V "Mark")',
            phaseNameHu: '0. Adatbit (1 = -12V "Mark")',
            category: 'DATA',
            signals: { 'TTL_TX': 1, 'RS232_TX': 1 },
            busVoltages: { 'TTL_TX': 5.0, 'RS232_TX': -12.0 },
            explanation: 'Bit 0 of \'M\' (0x4D = 0b01001101) is 1. TTL is 5V -> Line is -12V. Receiver samples at center of bit period.',
            explanationHu: 'Az \'M\' karakter (0x4D = 0b01001101) 0. bitje 1-es. TTL = 5V -> Kábel = -12V. A vevő a bit közepén mintavételezi.',
            masterAction: 'Outputs Bit 0 = 1 (-12V)',
            masterActionHu: '0. bit kiadása: 1 (-12V)',
            slaveAction: 'Samples -12V -> Decodes Bit 0 = 1',
            slaveActionHu: '-12V mintavétel -> 0. bit = 1 dekódolása',
            activeBytes: { txByte: 0x4d, bitIndex: 0, byteName: 'Char \'M\' (0x4D)' },
            highlightNode: 'BUS',
          },
          {
            stepIndex: 3,
            timeUs: 312,
            phaseName: 'Data Bit 1 (0 = +12V "Space")',
            phaseNameHu: '1. Adatbit (0 = +12V "Space")',
            category: 'DATA',
            signals: { 'TTL_TX': 0, 'RS232_TX': 0 },
            busVoltages: { 'TTL_TX': 0.0, 'RS232_TX': +12.0 },
            explanation: 'Bit 1 of \'M\' is 0. TTL is 0V -> Line is +12V. Receiver reads positive voltage -> Logic 0.',
            explanationHu: 'Az \'M\' 1. bitje 0-s. TTL = 0V -> Kábel = +12V. A vevő pozitív feszültséget olvas -> Logikai 0.',
            masterAction: 'Outputs Bit 1 = 0 (+12V)',
            masterActionHu: '1. bit kiadása: 0 (+12V)',
            slaveAction: 'Samples +12V -> Decodes Bit 1 = 0',
            slaveActionHu: '+12V mintavétel -> 1. bit = 0 dekódolása',
            activeBytes: { txByte: 0x4d, bitIndex: 1, byteName: 'Char \'M\' (0x4D)' },
            highlightNode: 'BUS',
          },
          {
            stepIndex: 4,
            timeUs: 1040,
            phaseName: 'STOP Bit: Mark State (-12V Bipolar for 1-2 Bit Times)',
            phaseNameHu: 'STOP Bit: Mark Szint (-12V Bipoláris 1-2 Bitidőig)',
            category: 'STOP',
            signals: { 'TTL_TX': 1, 'RS232_TX': 1 },
            busVoltages: { 'TTL_TX': 5.0, 'RS232_TX': -12.0 },
            explanation: 'Master transmits STOP bit (-12V). Receiver finishes assembling the 8-bit ASCII character \'M\' (0x4D) into its UART buffer.',
            explanationHu: 'A Master kiadja a STOP bitet (-12V). A vevő befejezi a teljes 8-bites ASCII \'M\' (0x4D) karakter összeállítását.',
            masterAction: 'Outputs STOP bit (-12V); frame complete',
            masterActionHu: 'STOP bit (-12V) kiadása; keret kész',
            slaveAction: 'Loads 0x4D into UART RX FIFO; triggers byte-received interrupt',
            slaveActionHu: 'Betölti a 0x4D bájtot a vételi FIFO-ba; megszakítást generál',
            activeBytes: { txByte: 0x4d, byteName: 'Received: \'M\' (0x4D)' },
            highlightNode: 'SLAVE_1',
          },
        ],
      },
    ],
  },
};
